nitro-shim/scripts/start-proxies.sh
=> Add missing slash prefix.

go.mod, go.sum, promotion/claim.go
check for nil claim creds and error if nil
=> bugfix claim creds

promotion/claim.go, utils/clients/ratios/client.go
=> update parameters to use coingecko route for ratios

utils/clients/client.go
=> fix the replacement redactions

docker-compose.yml
Prior to this change docker-compose didn't work on 12.3.1 macOS.
=> docker-compose fix for m1

rewards/controllers_test.go, rewards/service.go, utils/clients/ratios/client.go
=> Fix parameters ratios

promotion/drain.go, wallet/datastore.go
=> adding counters to instrument the withdrawal limits

promotion/datastore.go, promotion/drain.go, wallet/datastore.go
adding prom counters for unusual activity
=> Metrics for Drains/Linkings

promotion/datastore.go
altering cust limits with custodian log
=> altering cust limits with custodian log

docker-compose.yml
=> fix: update cbr kafka envars

skus/datastore.go
resolves #1474 - handle invalid point CBR condition
- [c] Bug fix
=> Handle RunOrderCreds Job Error Condition

rewards/service.go
set the context to passed in context in creation of s3 client
=> set the context to passed in context in creation of s3 client

utils/clients/cbr/client_test.go, utils/clients/client.go
adding more logging about client errors
=> additional logging on client errors

skus/datastore.go, skus/service.go, utils/clients/cbr/client_test.go, utils/clients/client.go
Adds additional logging to grants.
=> production 2022-07-12_1

utils/clients/gemini/client.go, utils/errors/errors.go, utils/wallet/provider/uphold/uphold.go, utils/wallet/wallet.go, wallet/controllers_v3.go
adding prom metric to tabulate anonymous transfer geo information.  Fixes: https://github.com/brave-intl/bat-go/issues/1485
=> Uphold Geo Instrumentation

cmd/serve/grant.go, utils/context/keys.go, utils/wallet/provider/uphold/uphold.go
require country data from uphold
=> require country data from uphold

cmd/serve/grant.go, utils/context/keys.go, utils/wallet/provider/uphold/uphold.go
require country data from uphold (#1492)
=> production 2022-07-18_1

utils/wallet/provider/uphold/uphold.go
also include successful country linkings in counter
=> Uphold Country Validation Success Instrumentation

nitro-shim/scripts/start-proxies.sh, nitro-shim/tools/utils/utils.go
Add [star-randsrv](https://github.com/brave-experiments/star-randsrv) as a service and fix a minor issue.
=> Nitro utils

go.mod, go.sum
=> updated dependencies

utils/wallet/provider/uphold/uphold.go
country information is in destination.node.user not in destination
=> Correct Location for Country Uphold TX

utils/wallet/provider/uphold/uphold.go
=> correct prom tag for tx_geo counter

utils/clients/gemini/client.go, utils/clients/gemini/instrumented_client.go, utils/clients/gemini/mock/mock.go, utils/clients/reputation/client.go, utils/clients/reputation/instrumented_client.go, utils/clients/reputation/mock/mock.go, wallet/controllers_v3_test.go, wallet/datastore.go, wallet/datastore_test.go, wallet/instrumented_datastore.go, wallet/service.go
=> pass country result to rep

wallet/service.go
=> adding bf geo reporting

cmd/serve/grant.go
adding /v1/declaregeo to reverse proxy pass those requests to reputation
=> declare geo passthrough

utils/clients/reputation/client.go
fixing query string parameters for reputation linking request
=> fixing query string parameters for reputation linking request

cmd/serve/grant.go, utils/clients/reputation/client.go
declare geo passthrough (#1515)
=> production 2022-07-26_1

utils/clients/reputation/client_test.go, utils/wallet/provider/uphold/uphold.go, wallet/service.go
=> using wrong value of country for check

cmd/merchant/README.md, cmd/merchant/new_keys.go, main.go, utils/clients/reputation/client_test.go, utils/cryptography/attenutated_credential.md, utils/wallet/provider/uphold/uphold.go, wallet/service.go
adding documentation about merchant keys
correcting where to get the rep params from in linking
=> production 2022-07-29_1

utils/clients/reputation/client.go, wallet/datastore.go, wallet/service.go
Geo reset different cohort unique error
=> Geo reset different cohort

utils/clients/reputation/client.go, wallet/datastore.go, wallet/service.go
Geo reset different cohort (#1527)
=> production 2022-08-01_1

wallet/service.go
temporarily use mismatched wallet error for geo reset
=> temporarily use mismatched wallet error for geo reset

wallet/service.go
temporarily use mismatched wallet error for geo reset (#1529)
=> production 2022-08-01_2

utils/errors/errors.go, utils/wallet/provider/uphold/uphold.go
specific error for lack of identity country
=> specific error for lack of identity country

wallet/service.go
correcting the error for mismatched regions
=> correcting the error for mismatched regions

skus/controllers.go, skus/controllers_test.go, skus/datastore.go, skus/datastore_test.go, skus/input.go, skus/instrumented_datastore.go, skus/mockdatastore.go, skus/service.go
=> adding playstore webhook

wallet/service.go
=> new connect endpoints, moving away from claim endpoints

nitro-shim/scripts/start-proxies.sh
We're expecting incoming connections to port 1080; not 80.
=> Fix incoming SOCKS port.

libs/go.mod, services/promotion/controllers.go
=> update containerd, for some reason it is required by golang-migrate

main.go
=> adding grants entrypoint to main

services/wallet/datastore.go
=> nulls out the account provider on disconnect

services/grant/cmd/grant.go, services/wallet/cmd/rest_run.go, services/wallet/cmd/wallets.go, services/wallet/service.go
=> feat: wallet creation for rewards 2.5

services/ratios/service.go
=> [ratios] Add prometheus counter to track cache hit rate for GetRelative (coingecko)

services/wallet/controllers_v4.go, services/wallet/geolocation.go, services/wallet/service.go
Reward wallet creation adds more logging to endpoint
=> Reward wallet creation

libs/context/keys.go, services/grant/cmd/grant.go, services/skus/input.go, services/skus/receipt.go
utilizes the shared app password for receipt validation for iap rails.
=> iOS receipt validation fixes

services/ratios/service.go
I tested passing 500 coins and 5 vsCurrencies params to Coingecko's /simple/price and didn't hit any limits and request latency was reasonable.
=> [ratios] Increase number of coins to cache from 25 to 500

services/ratios/cmd/rest_run.go, services/ratios/middleware.go
=> [ratios] Add metrics for presence of header

services/ratios/cmd/rest_run.go, services/ratios/middleware.go
=> [ratios] Add metrics for presence of header (#1595)

libs/custodian/regions.go, services/wallet/service.go
adds valid struct tags for custodian regions structure.
=> Hotfix custodian regions

.github/workflows/sam-dev.yml
Update `sam-dev.yml` github Actions
=> Update SAM Development Github Actions YAML

.github/workflows/sam-dev.yml
Explicitly define location of SAM template.
=> Add Template variable to SAM Build

.github/workflows/sam-dev.yml
Explicitly define template.yaml file for SAM deploy
=> Update SAM Deploy to use defined template file location

serverless/email/template.yaml
Update CodeUri location for lambdas.
=> Update CodeUri Location for Lambdas

.github/workflows/sam-dev.yml
Set debug flag for SAM build and deploy to triage code upload
=> Set SAM debug flag

.github/workflows/sam-dev.yml, serverless/email/template.yaml
Updated SAM template and Github Actions YAML
=> Deployment Configuration Updates

.github/workflows/sam-dev.yml, serverless/email/template.yaml
Add missing Parameter definition to SAM template.
=> Update SAM deployment template to allow for deployment environment

.github/workflows/sam-dev.yml
Removed redundant `aws-actions/setup-sam` declaration; updated `aws-actions/setup-sam` to `v2`
=> Update setup-sam declaration in Github Action

serverless/email/template.yaml
Fix to resolve the following error:
```
Error: Failed to create changeset for the stack: bravex-frontend, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Unresolved resource dependencies [ServerlessRestApi] in the Outputs block of the template
```
=> Update SAM Deployment Outputs for API Gateway Endpoints

serverless/email/template.yaml
Removed outputs for Lambda Function Role ARNs because they are passed into the template via SSM Parameter Store variables.
=> Remove Extra Outputs from SAM Template

serverless/email/template.yaml
Update SAM template output to fix the following Cloudformation error:
```
Requested attribute ServerlessRestApi does not exist in schema for AWS::Lambda::Function. Rollback requested by user.
```
=> Update SAM Template Outputs

serverless/email/template.yaml
Added DynamoDB endpoint for Lambdas
=> Add DynamoDB Endpoint Environment Variable for Lambdas

.github/workflows/sam-dev.yml, serverless/email/template.yaml
Added flag for enabling X-Ray Tracing to help triage Webhook Lambda.
=> Enable Webhook X-Ray Tracing

serverless/email/template.yaml
Test removing VPC configuration for Webhook and Unsubscribe Lambdas
=> Remove VPC Config for Webhook and Unsubscribe Lambdas

serverless/email/template.yaml
Add SES Domain Identity ARN for Webhook Lambda
=> Add SES Domain Identity Environment Variable for Webhook Lambda

serverless/email/webhook/main.go
=> Remove ReturnPathArn Argument from Webhook Email Template

serverless/email/webhook/main.go
=> Remove Config Set Argument from Webhook

serverless/email/template.yaml
Updated SAM Template to contain information for Events Lambda
=> Update SAM Template for Events Lambda

serverless/email/template.yaml
Merge updates to SAM template for Events Lambda
=> Update SAM template for Events Lambda (#1627)

serverless/email/template.yaml
=> Fix for SAM template

serverless/email/template.yaml
=> Remove Unused SAM parameters

.github/workflows/sam-dev.yml, serverless/email/template.yaml
=> Add X-Ray Flags to Lambdas and API Gateway

serverless/email/status/main.go
=> Properly set up dynamo db using STS

serverless/email/template.yaml
- Adds Tags to resources
- Creates CloudWatch Log groups managed by SAM
=> SAM Template Improvements

go.mod, go.sum, go.work.sum, tools/go.mod, tools/go.sum
=> updating vault deps

libs/custodian/regions.go, libs/custodian/regions_test.go, libs/wallet/provider/uphold/uphold.go, services/wallet/controllers_v3.go, services/wallet/service.go
updates to logic around allow/blocklist verdicts.
=> fixing up allow list/block list

docker-compose.yml, go.mod, go.sum, go.work.sum, libs/custodian/regions.go, libs/custodian/regions_test.go, libs/wallet/provider/uphold/uphold.go, services/wallet/controllers_v3.go, services/wallet/controllers_v4_test.go, services/wallet/service.go, tools/go.mod, tools/go.sum
=> production 2022-09-29_1

serverless/email/events/status_delivery_event.json, serverless/email/events/status_send_event.json, serverless/email/template.yaml
- Updated SAM template to support Lambda Safe Deployments (depends on https://github.com/brave-intl/bsg-infra/issues/551)
- Added generation events for Status Send and Status Delivery
https://github.com/brave-intl/bsg-infra/issues/551
=> Added Lambda Safe Deployment Resources; Generation Events for Status Lambda

services/skus/controllers.go, services/skus/service.go
[Fix Sentry logging webhook noise #1658](https://github.com/brave-intl/bat-go/issues/1658)
=> Sentry issue

serverless/email/template.yaml
Associated to https://github.com/brave/devops/pull/8430
=> Add Variables for HMAC Sig Support

serverless/email/template.yaml
=> Update FTX Header Key Value

services/promotion/datastore.go
cleaning up sentry logs for job runner.
=> no need to sentry log these errors

libs/handlers/healthcheck.go, services/cmd/serve.go, services/grant/cmd/grant.go
health check to inform wallet linking status
=> have health-check inform service degredation for wallet

libs/clients/gemini/client.go, services/wallet/datastore.go, services/wallet/instrumented_datastore.go, services/wallet/instrumented_read_only_datastore.go, services/wallet/service.go
check if this wallet was linked before prior to geo failure
fixes: https://github.com/brave-intl/tickets-ledger/issues/65
=> custodian linkage check geo

services/skus/controllers.go, services/skus/order.go, services/skus/service.go
adding payment processor to order metadata
=> adding payment processor to order metadata

services/wallet/controllers_v3_test.go, services/wallet/service.go
hotfix for prior-link-geo peer review items
=> hotfix for prior-link-geo peer review items

libs/clients/gemini/client.go, libs/handlers/healthcheck.go, libs/kafka/dialer.go, services/cmd/serve.go, services/grant/cmd/grant.go, services/promotion/datastore.go, services/skus/controllers.go, services/skus/order.go, services/skus/service.go, services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/instrumented_datastore.go, services/wallet/instrumented_read_only_datastore.go, services/wallet/service.go
=> production 2022-10-12_1

services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/service.go
exclude no rows exceptions for prior linking attempt
=> exclude no rows exceptions for prior linking attempt

services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/service.go
exclude no rows exceptions for prior linking attempt (#1679)
=> production 2022-10-12_2

nitro-shim/tools/viproxy/main.go
Fix a warning (and presumed output problem) by using the formatted version of and error when a format string is passed.
=> viproxy: Use formatted error output.

Makefile
fixing the settlement build make instruction
=> fixing the settlement build make instruction

libs/clients/reputation/client.go, libs/clients/reputation/instrumented_client.go, libs/clients/reputation/mock/mock.go, libs/datastore/postgres.go, migrations/0046_verified_wallet_outbox.down.sql, migrations/0046_verified_wallet_outbox.up.sql, services/ratios/cmd/rest_run.go, services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/datastore_test.go, services/wallet/instrumented_datastore.go, services/wallet/service.go
added reputation client and undated link/unlink code
resolves [#71](https://github.com/brave-intl/tickets-ledger/issues/71)
=> Send wallet verification state to reputation

services/wallet/controllers_v3_test.go, services/wallet/datastore.go
added verified wallet to disconnected call
resolves [#71](https://github.com/brave-intl/tickets-ledger/issues/71)
=> Rewards 2.5 verified wallet 

services/wallet/service.go
Sets the v4 endpoints rate limit value
resolves https://github.com/brave-intl/bat-go/issues/1703
=> added explicit rate limit values for wallet endpoints

libs/context/keys.go, services/rewards/service.go, services/wallet/controllers_v3_test.go, services/wallet/keystore_test.go, services/wallet/service.go
fixing caching of custodian regions in parameters service and wallet service
fixes: https://github.com/brave-intl/tickets-ledger/issues/64
=> caching custodian regions

services/wallet/controllers_v3_test.go, services/wallet/datastore.go
Removes the disconnect/unverified call to rep
=> Remove reputation disconnect wallet call

services/wallet/controllers_v4.go, services/wallet/controllers_v4_test.go
Add logging to unwrap error bundle 
resolves https://github.com/brave-intl/bat-go/issues/1715
=> log error bundle create wallet v4

libs/handlers/healthcheck.go, services/cmd/serve.go, services/grant/cmd/grant.go
=> Health check improvements

libs/clients/client.go, libs/handlers/healthcheck.go, services/cmd/serve.go, services/grant/cmd/grant.go, services/skus/controllers_test.go, services/skus/datastore.go, services/wallet/controllers_v4.go, services/wallet/controllers_v4_test.go
Fixes cbr error handling. Increased logging.  New Healthcheck handler.
=> production 2022-12-29_1

migrations/0050_cred_request_downloaded_undo.down.sql, migrations/0050_cred_request_downloaded_undo.up.sql, services/skus/controllers.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/service.go
remove downloaded at, revert constraint back to per order creds, allow subscriptions to manage the ability to add more devices
=> revert downloaded at and request id for order creds download

services/rewards/cmd/rest_run.go
=> fix transition in api.rewards/parameters

services/ratios/controllers.go, services/ratios/controllers_test.go, services/ratios/inputs.go
Fix Ratios request validation
* Make sure to catch all the errors from DecodeAndValidate in the
controllers so that 400s are pass to the client instead of the catch all
500s
* Add tests for these validation errors
=> Fix Ratios request validation

services/wallet/controllers_v3.go
fixes: https://github.com/brave-intl/tickets-ledger/issues/76
=> return empty map instead of nil for success cases

services/skus/service.go
fixes: https://github.com/brave-intl/bat-go/issues/1739
=> do not overwrite the subscription id, lookup sub id if missing

services/go.sum
=> missed this indirect

services/skus/service.go
if subscription do not check checkout session for updates
=> order status update on get order

services/ratios/mapping.go
fixing mapping for ratios compund coin
=> fixing mapping for ratios compund coin

services/wallet/controllers_v3_test.go, services/wallet/datastore.go
fixes: https://github.com/brave-intl/tickets-ledger/issues/75 remove linking_id from update query
=> double custodian linkings

libs/datastore/postgres.go, migrations/0047_claimable_until_promotion.down.sql, migrations/0047_claimable_until_promotion.up.sql, services/promotion/datastore.go, services/promotion/promotion.go
fix for specifying alternate claimable_until value on promotion
=> alternate claimable_until

libs/datastore/postgres.go, migrations/0047_claimable_until_promotion.down.sql, migrations/0047_claimable_until_promotion.up.sql, services/promotion/datastore.go, services/promotion/promotion.go, services/ratios/mapping.go, services/wallet/controllers_v3_test.go, services/wallet/datastore.go
fixing mapping for ratios compund coin (#1753)
=> production 2023-02-07_1

libs/datastore/postgres.go, migrations/0052_claim_drain_pending_idx.down.sql, migrations/0052_claim_drain_pending_idx.up.sql, migrations/0053_vote_drain_processed_erred_idx.down.sql, migrations/0053_vote_drain_processed_erred_idx.up.sql, migrations/0054_suggestion_drain_not_erred_idx.down.sql, migrations/0054_suggestion_drain_not_erred_idx.up.sql, migrations/0055_order_creds_batch_proof_null_idx.down.sql, migrations/0055_order_creds_batch_proof_null_idx.up.sql, migrations/0056_signing_order_request_outbox_created_at_submitted_at_isnull_idx.down.sql, migrations/0056_signing_order_request_outbox_created_at_submitted_at_isnull_idx.up.sql, services/promotion/datastore.go
=> production 2023-02-16_1

services/skus/controllers_test.go, services/skus/credentials.go
=> verify number of blinded creds in submission

services/skus/controllers.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/service.go
=> Check external id receipt

services/skus/controllers.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/service.go
* check if the external id alread exists for receipt submission
* fixing return value
* add a method on the service
* fixing function name
=> Check external id receipt (#1785)

services/skus/datastore.go
=> fixing external id existance query

services/skus/datastore.go
=> fixing external id existance query (#1787)

services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/service.go
remove run next order job, fixes #1541
=> remove run next order job, fixes #1541

services/skus/controllers.go, services/skus/credentials.go, services/skus/credentials_test.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/order.go, services/skus/service.go
This PR adds logic to prevent order creds from being deleted when they are in the process of being signed
fixes #1778
=> fix single use credentials unique constraint violation

services/skus/controllers.go, services/skus/controllers_test.go, services/skus/service.go, services/skus/transaction.go
=> get creds by order item id

services/skus/controllers.go, services/skus/controllers_test.go, services/skus/credentials.go, services/skus/credentials_test.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/order.go, services/skus/service.go, services/skus/transaction.go
=> production 2023-03-15_1

services/skus/credentials.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go
This PR adds a check to make sure orders creds have not been deleted whilst they are being signed
fixes #1794
=> check order creds have not been deleted during signing

services/skus/controllers_test.go, services/skus/datastore.go, services/skus/datastore_test.go
=> filter out creds past order expiry from being inserted

services/skus/controllers_test.go, services/skus/credentials.go, services/skus/datastore.go, services/skus/datastore_test.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go
=> production 2023-03-24_1

services/ratios/mapping.go
Deploy https://github.com/brave-intl/bat-go/pull/1799 to the production environment.
=> Add coingecko mapping for BOO token on Solana (#1799)

nitro-shim/scripts/start-proxies.sh
=> change port number for gvproxy

services/promotion/datastore.go, services/promotion/drain.go
Adds some logging to help debug
https://github.com/brave-intl/tickets-ledger/issues/117
=> Investigate failing bitFlyer drains

nitro-shim/scripts/build.sh, nitro-shim/scripts/run.sh
=> Parameterize cpu count/memory in nitro shim

services/grant/cmd/grant.go, services/skus/controllers_test.go, services/skus/credentials_test.go, services/skus/datastore.go, services/skus/datastore_test.go, services/skus/db/repository/order_history.go, services/skus/db/repository/order_item.go, services/skus/db/repository/repository.go, services/skus/key_test.go, services/skus/model/model.go, services/skus/order_test.go, services/skus/vote_test.go
=> Decouple Operations on Order Data From The Rest 03

services/grant/cmd/grant.go, services/skus/controllers_test.go, services/skus/credentials_test.go, services/skus/datastore.go, services/skus/datastore_test.go, services/skus/db/repository/order_history.go, services/skus/db/repository/order_item.go, services/skus/db/repository/repository.go, services/skus/key_test.go, services/skus/model/model.go, services/skus/order_test.go, services/skus/vote_test.go
=> Decouple Operations on Order Data From The Rest 02

services/grant/cmd/grant.go
This PR adds the play integrity route
=> register route play integrity

services/skus/input.go
=> parse the request body from the ios hook appropriately

services/skus/input.go
parse the request body from the ios hook appropriately (#1840)
=> production 2023-05-24_1

services/skus/input.go
=> Ios webhook parse request

services/skus/input.go
parse the request body from the ios hook appropriately (#1847)
=> production 2023-05-25_1

services/wallet/service.go
Adds further logging to create wallet
fixes #1849
=> add logging for wallet creation

services/skus/receipt.go, services/skus/service.go, services/wallet/service.go
=> production 2023-05-26_1

tools/settlement/settlement.go
Fail permanently on Uphold 404 response on commit
Closes #1854
=> Fail permanently on Uphold 404 response on commit

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, Makefile
This PR configures CodeQL and speeds it up by a factor of ~4 (depending on GitHub), bringing the time down from around 18–23 minutes to 6–7. It also updates settings for the CI step. Combined, this means that the overall run time for a full CI run on a push a PR branch is now down from 22 minutes on average to about 12, which is almost 2 times faster.
CodeQL runs a sequence of steps prior to actually running queries against the code base. Most notably, there is the default `autobuild` step, which, unless configured properly, won't do the right thing in our case. This step is supposed to prepare (download) dependencies and build the binary.
When used, the `autobuild` step for Go projects attempts to find a `Makefile`, and runs `make`. In our case, it results in running what is defined in …
=> Configure CodeQL

services/wallet/controllers_v3.go, services/wallet/inputs.go, services/wallet/service.go
This PR provides my review feedback for #1876. Feel free to merge if agree.
=> Patches For 1876.

docker-compose.yml
This PR improves the startup sequence of the local environment defined in `docker-compose.yml`, fixes a few missing configuration variables for the `web` service, and tidies up the file a bit.
More specifically, the PR addresses the following issues:
- The `web` container would fail to start with a panic due to missing topic configuration such as `GRANT_CBP_SIGN_CONSUMER_TOPIC` and friends.
- The `web` container would fail to start because some dependencies might be unavailable. For instance, Postgres, which takes longer than an instant to start, as well as Kafka.
- Overall, merely listing a service in `depends_on` is not enough to guarantee anything beyond the fact that a container was attempted to be started. Whenever we need to ensure that A starts prior to B, the recommended way is to …
=> Ensure Local Env Starts Well and Tidy Up

services/wallet/controllers_v3_test.go
This PR fixes tests for #1881.
=> Patches For 1881

services/wallet/controllers_v3.go, services/wallet/controllers_v3_test.go, services/wallet/inputs.go, services/wallet/service.go
remove deposit id from linking for xyzabc, fix json for linkingInfo in payload
=> xyzabc fix linking payload

libs/datastore/postgres.go, migrations/0061_wallet_custodian_check_custodian.down.sql, migrations/0061_wallet_custodian_check_custodian.up.sql, services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/inputs.go, services/wallet/service.go
=> production 2023-07-13_1

services/wallet/controllers_v3.go, services/wallet/controllers_v4.go, services/wallet/service.go
remove wallet disconnect routes, add v4 uphold balance check to httpsignature
=> remove wallet disconnect route

tools/payments/report.go
This PR adds a duplicate deposit destination check when validating a report
resolves #1827
=> added duplicate deposit destination to validate report

tools/payments/cmd/authorize/main.go, tools/payments/cmd/prepare/main.go
added payout id param to prepare and authorize commands
resolves #1891
=> added payout id param to prepare and authorize commands

libs/clients/gemini/client.go
This PR adds valid documents to the Gemini account validate endpoint response
resolves #1890
=> Add valid documents to gemini account valid endpoint response

tools/payments/go.mod, tools/payments/go.sum, tools/payments/report.go, tools/payments/report_test.go
Just noticed #1893, and decided I would suggest a couple of things:
- Use `map[string]struct{}` instead of `map[string]bool` because it's a tiny bit more idiomatic.
- Expressed the change as behaviour on the report types. This helps to stay focussed on what's being accomplished rather than how it's being done.
- Added trivial tests to ensure that it does indeed do that.
- Fixed a minor typo in messaging.
=> Suggestions For 1893

tools/payments/cmd/authorize/main.go, tools/payments/cmd/prepare/main.go
Updates the logging for the prepare and authorize commands to avoid confusion with worker report uploading
resolves #1908
=> update command log output

libs/clients/gemini/client.go, libs/clients/gemini/clientx_test.go
This PR adds a feature flag for issuing country
resolves #1913
=> added issuing country feature flag

docker-compose.yml, libs/clients/gemini/client.go, libs/clients/gemini/clientx_test.go, nitro-shim/Dockerfile, nitro-shim/scripts/build.sh, nitro-shim/tools/eifbuild/Makefile, nitro-shim/tools/eifbuild/go.mod, nitro-shim/tools/eifbuild/main.go, services/skus/controllers.go, services/skus/controllers_test.go, services/skus/handler/handler.go, services/skus/handler/handler_test.go, services/skus/model/model.go, services/skus/order.go, services/skus/service.go, tools/payments/cmd/authorize/main.go, tools/payments/cmd/prepare/main.go
=> production 2023-07-23_1

services/promotion/order.go, services/skus/datastore.go, services/skus/datastore_test.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/model/model.go, services/skus/model/model_test.go, services/skus/order.go, services/skus/order_test.go, services/skus/service.go, services/skus/storage/repository/order_item_test.go, services/skus/storage/repository/repository.go, services/skus/storage/repository/repository_test.go
This PR refactors payment methods. I am doing this prior to adding another endpoint for creating orders which will result in more code using the presently-suboptimal implementation (of `Methods`).
Payment methods is a slice of strings. It may or may not be `NULL` in the database, as well as `nil` at runtime. The simplest way to represent this when working with Postgres in Go (and using the `lib/pq` driver) is to use `pq.StringArray`. It supports nullability, and is a handy type exists for representing `text[]`.
The previously existing `Methods` type has had a number of issues:
1. It used pointers where just a value variable or value receiver would suffice.
2. The `Value` method should have had a value receiver type (since it has to work for pointers and values).
3. The `Equal` method had …
=> Bundles – Refactor Payment Methods

libs/context/keys.go, migrations/0061_wallet_custodian_check_custodian.up.sql, services/grant/cmd/grant.go, services/wallet/controllers_v3.go, services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/inputs.go, services/wallet/service.go
updates custodian name for linking endpoints
=> update custodian name

services/wallet/datastore.go, services/wallet/service.go
This PR make wallet call reputation directly
=> Update wallet to call reputation directly during linking

libs/context/keys.go, migrations/0061_wallet_custodian_check_custodian.up.sql, services/grant/cmd/grant.go, services/promotion/order.go, services/skus/datastore.go, services/skus/datastore_test.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/model/model.go, services/skus/model/model_test.go, services/skus/order.go, services/skus/order_test.go, services/skus/service.go, services/skus/storage/repository/order_item_test.go, services/skus/storage/repository/repository.go, services/skus/storage/repository/repository_test.go, services/wallet/controllers_v3.go, services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/inputs.go, services/wallet/service.go
=> production 2023-08-01_1

services/go.mod, services/wallet/controllers_v3_test.go, services/wallet/service.go
=> performing token validations

services/go.mod, services/wallet/controllers_v3_test.go, services/wallet/service.go
performing token validations (#1926)
=> production 2023-08-03_1

services/rewards/service.go
=> set transition to false

services/rewards/service.go
=> Production 2023-08-04_1

services/rewards/parameters.go, services/rewards/service.go
=> Remove vbat params

services/rewards/parameters.go, services/rewards/service.go
=> Production 2023-08-07_1

services/grant/cmd/grant.go, services/skus/controllers.go, services/skus/controllers_test.go, services/skus/credentials_test.go, services/skus/key.go, services/skus/key_test.go
This PR updates the way routing is initialised for SKUs, and adds a new route – `/v1/orders-new`.
=> Improve SKUs Routing Initialisation

services/ratios/mapping.go
Deploy #1935 to production. Tested OK on staging environment.
```sh
$ curl -s https://ratios.rewards.brave.software/v2/relative/provider/coingecko/neon/usd/1d | jq '.payload.neon.usd'
0.056881  # ✅
```
=> Add Neon mapping to ratios service (#1935)

services/wallet/controllers_v3.go
This PR adds extra logging around linking Gemini wallets
resolves #1940
=> added logging to gemini link wallets

services/grant/cmd/grant.go
=> add disable zebpay linking parameters

services/wallet/controllers_v3_test.go, services/wallet/service.go
check that isValid is true on the linking info jwt.
=> zebpay isValid check

services/wallet/controllers_v3_test.go, services/wallet/service.go
* checking isValid on linking_info
* fix tests and add a failing test for isValid
zebpay isValid check (#1947)
=> production 2023-08-14_1

libs/clients/gemini/client.go, libs/clients/gemini/clientx_test.go
This PR refines the Gemini accepted document types and adds a metric to track document types by country
=> Refine gemini accepted document types and add metric

libs/clients/gemini/client.go, libs/clients/gemini/clientx_test.go
Update accepted document type for Gemini
=> updated accepted document types

services/grant/cmd/grant.go, services/grant/cmd/grant_test.go
This PR adds Zebpay status to the service status output. Additionally, it now has a simple test.
=> Add Zebpay To Health Check

services/wallet/controllers_v3.go, services/wallet/controllers_v3_test.go, services/wallet/inputs.go, services/wallet/service.go, services/wallet/service_test.go
fixes returned error code: https://github.com/brave-intl/payment-services/issues/139
=> propogates 403 back to caller for kyc error

services/wallet/controllers_v3_test.go, services/wallet/service.go, services/wallet/service_test.go
fixes [#159](https://github.com/brave-intl/payment-services/issues/159)
=> implement country code check for zebpay on linking

services/wallet/controllers_v3.go, services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/service.go
This PR -
* Changed error message removing the word reputation
* Renamed linking function
* Removed unused feature toggle
* Improved comment
fixes [#132](https://github.com/brave-intl/payment-services/issues/132)
=> fix: add internal server error for linking failure caused by reputation

services/grant/cmd/grant.go, services/skus/controllers.go, services/skus/controllers_test.go, services/skus/credentials.go, services/skus/credentials_test.go, services/skus/datastore.go, services/skus/datastore_test.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/model/model.go, services/skus/order.go, services/skus/order_test.go, services/skus/service.go, services/skus/storage/repository/issuer.go, services/skus/storage/repository/issuer_test.go, services/skus/storage/repository/mock.go, services/skus/storage/repository/repository_test.go, services/wallet/controllers_v3.go, services/wallet/controllers_v3_test.go, services/wallet/datastore.go, services/wallet/service.go
=> Production 2023-09-13_01

libs/payments/payment_state.go, services/payments/datastore.go, services/payments/datastore_test.go, services/payments/security_review_statemachine_bitflyer_test.go, services/payments/security_review_statemachine_gemini_test.go, services/payments/security_review_statemachine_uphold_test.go, services/payments/security_review_test.go, services/payments/service.go
Temporarily ignore the payment service pubkey to unblock testing.
=> Ignore Public Key for Testing

services/payments/service.go, services/payments/templates/sign-policy.tmpl
fixes signing key creation by specifying `KeySpec` and `KeyUsage`, also ensures policy grants `Sign` permissions to the enclave not `Decrypt`.
=> fix nitro signing key creation

services/payments/service.go
fix signing hopefully by switching to `ECC_NIST_P256` which should be compatible with `ECDSA_SHA_256`
=> switch to ECC_NIST_P256 for nitro signing

libs/context/keys.go, services/nitro/nitro.go, services/payments/security_review_test.go, services/payments/service.go
=> Set context variables from env

services/payments/datastore.go
fix transaction insert by calling next on result
=> fix transaction insert by calling next on result

services/payments/service.go
=> Add missing error cause in log

services/payments/datastore.go
=> Only create index if we create the table successfully

services/payments/datastore.go
=> Unmarshal into a pointer instead of a variable directly

services/payments/datastore.go
=> make DocumentID a public field

services/skus/service.go
=> Patches For 1995

libs/payments/qldb_types.go, services/payments/security_review_statemachine_bitflyer_test.go, services/payments/security_review_statemachine_gemini_test.go, services/payments/security_review_statemachine_uphold_test.go, services/payments/security_review_test.go
=> Update tests for new QLDB type

cmd/macaroon/brave-firewall-vpn/premium_dev_time_limited_v2.yaml, cmd/macaroon/brave-skus/free_time_limited_v2_dev.yaml, cmd/root.go
removed unrelated changes from nitro-payments-dev
=> try to cleanup changes that are unrelated to the nitro work

services/payments/service.go
=> adding kms key aliasing to fix issue with new key on reboot

services/payments/service.go
=> check the exact key policy before using the key

libs/payments/authenticated_payment_state.go, libs/payments/qldb_types.go
=> Remove slices.contains

services/payments/service.go
=> Return PCR2 instead of the document digest

services/payments/service.go
=> Warn for key not found instead of fail

services/payments/service.go
=> Check NotFoundException string instead of code

services/payments/service.go
=> Name key aliases according to AWS requirements

services/rewards/service.go
=> updates to allow for configurable vbat expiry and transition variables

services/rewards/service.go
…s (#2052)
* updates to allow for configurable vbat expiry and transition variables
* vbat-deadline type correction
=> production 2023-10-02_1

services/payments/authorize.go, services/payments/controllers.go, services/payments/datastore.go, services/payments/qldb_types.go, services/payments/security_review_statemachine_bitflyer_test.go, services/payments/security_review_test.go, services/payments/service.go, services/payments/statemachine.go, services/payments/statemachine_bitflyer.go, services/payments/statemachine_dryrun.go, services/payments/statemachine_gemini.go, services/payments/statemachine_uphold.go
=> Remove dot imports for the payment library

libs/logging/logging.go, main/main.go
wait for zerolog logs on exit by closing the writer
=> wait for zerolog logs on exit by closing the writer

services/payments/datastore.go
fix error return and make QLDB hash verification a warning
=> fix error return and make QLDB hash verification a warning

libs/payments/errors.go, services/payments/controllers.go, services/payments/statemachine.go
fix insufficient authorizers case, the early return results in it not being written to QLDB
=> fix insufficient authorizers case

libs/httpsignature/httpsignature.go, libs/middleware/http_signed.go, libs/payments/errors.go, services/nitro/nitro.go, services/payments/controllers.go, services/payments/service.go, services/payments/statemachine.go
fix remaining issues in order to test dry-run prepare and authorize. since we are still working on initial config / bootstrap, I moved the vault unseal to be non-blocking.
=> fix remaining issues in order to test dry-run prepare and authorize

services/payments/statemachine.go
fix for DriveTransaction, check the correct error. previously we were returning 500 in response to the first authorization when we should have been returning 200 ( to halt retries by the worker. )
=> fix for DriveTransaction, check the correct error

libs/redisconsumer/consumer.go, services/payments/controllers.go
fix worker resuming consumer and response status for non-finalized state
=> fix worker resuming consumer and response status for non-finalized state

libs/clients/zebpay/client.go
=> Change ZebPay codes to match documentation

libs/nitro/aws/sdk.go
=> pin amazon roots

services/payments/secrets.go
=> setup env variables from secrets for zebpay

libs/payments/state.go
=> Add Zebpay to JSON validation

services/payments/secrets.go, tools/payments/attestation.go, tools/payments/client.go, tools/payments/cmd/bootstrap/main.go
add prefix to operator shares based on pcr2, fixes #2083
edit: also fixes #2062
=> add prefix to operator shares based on pcr2, fixes #2083

libs/nitro/log.go, libs/nitro/vsock.go, services/payments/controllers.go
=> cleanup the nitro enclave logs a bit

nitro-shim/Dockerfile, nitro-shim/tools/eifbuild/.gitignore, nitro-shim/tools/eifbuild/README.md, nitro-shim/tools/eifbuild/main.go
=> add instructions for locally reproducing the PCR of a given docker image

services/payments/statemachine.go
=> Add zebpay to state machine initialization

services/skus/controllers.go, services/skus/service.go
time limited v2 multi redeem
* change method parameter name from req to cred
* log in controller
=> refactor: tlv2 multi redeem

libs/nitro/aws/sdk.go, services/nitro/nitro.go
=> capture and log panic within nitro enclave

services/payments/state_verifier.go
=> fix assignment to nil map

libs/middleware/date.go, libs/nitro/handlers.go
=> set log level for health-check handler message to debug

services/payments/security_review_statemachine_zebpay_test.go, services/payments/statemachine.go, services/payments/statemachine_zebpay.go
=> Log error if present when Drive fails in state machine

libs/nitro/attestation.go
=> attest to sha256 of message

services/payments/controllers.go, services/payments/service.go, services/payments/statemachine.go
=> use vsock http transport for zebpay client instantiation

services/skus/controllers.go, services/skus/service.go
Reverts brave-intl/bat-go#2100
=> Revert "Production 2023-11-10_01"

services/payments/datastore.go
make prepare idempotent, fixes #2027
=> make prepare idempotent, fixes #2027

services/payments/secrets.go, services/payments/statemachine.go
function to check if secrets are loaded in nitro-payments service; fixes: https://github.com/brave-intl/bat-go/issues/2066
=> is nitro service conigured with secrets

tools/payments/cmd/authorize/main.go, tools/payments/cmd/prepare/main.go
perform comparison reports for validation of authorize and prepare; fixes: https://github.com/brave-intl/bat-go/issues/2118
=> validate prepare/authorize

services/payments/authorize.go
=> add actual operator public keys

services/payments/authorize.go
=> Add missing comma

services/payments/service.go, services/payments/templates/decrypt-policy.tmpl
=> allow for templating node and developer roles

services/payments/authorize.go
=> Replace public key

libs/payments/api.go, services/payments/worker.go, tools/payments/client.go, tools/payments/cmd/bootstrap/main.go
=> have worker use payments uri depending on environment

libs/redisconsumer/consumer.go
=> make consumer process messages in parallel

libs/httpsignature/nitro_test.go, libs/nitro/attestation.go, libs/payments/crypto.go, libs/payments/state.go, services/payments/datastore.go, services/payments/state_verifier.go
=> verify nitro attestations were valid when written versus now

services/payments/state_verifier.go
=> Add PCR for run with state transition changes

services/payments/state_verifier.go
=> update pcr list with last value

libs/clients/zebpay/client.go, services/payments/statemachine_zebpay.go
=> no error on checkstatus if there was a response

services/payments/mocked_zebpay_test.go, services/payments/statemachine_zebpay.go
=> Remove drive recursion

libs/clients/client.go, services/payments/worker.go
=> extend timeout for nitro worker HTTP client

services/skus/controllers.go, services/skus/controllers_test.go, services/skus/credentials.go, services/skus/datastore.go, services/skus/model/model.go, services/skus/order.go, services/skus/service_nonint_test.go
=> Production Release 2023-10-26

libs/wallet/provider/uphold/uphold.go
Update prod and sandbox cert fingerprint
The new fingerprint was taken by executing helper `./bat-go get-cert-fingerprint api.uphold.com:443`
fixes: [#174](https://github.com/brave-intl/payment-services/issues/174)
related issue [#1969](https://github.com/brave-intl/bat-go/pull/1969)
=> fix: update uphold cert fingerprint

services/payments/authorize.go
Allow environment-specific authorizer keys. closes #2159
=> Allow environment-specific authorizer keys

services/payments/controllers.go, tools/payments/cmd/bootstrap/main.go
fixes: #2189 environment from enclave bootstrap check
=> fixes: #2189 environment from enclave bootstrap check

tools/payments/cmd/authorize/main.go, tools/payments/cmd/prepare/main.go
Feature/fail missing args non dev. closes #2137
=> Fail missing args non dev

libs/payments/requests.go, services/payments/controllers.go
Add PaymentDetails to SubmitResponse. closes #2154
=> Add PaymentDetails to SubmitResponse

nitro-shim/Dockerfile
fixes: https://github.com/brave-intl/bat-go/issues/2124
=> reduced down to 647MB the nitro-shim image

libs/middleware/upgrade_required.go, libs/middleware/upgrade_required_test.go, services/grant/cmd/grant.go, services/promotion/controllers.go
adding vbat expiry with default val of 11/2/2023
=> adding vbat expiry with default val of 11/2/2023

libs/middleware/upgrade_required.go, libs/middleware/upgrade_required_test.go, services/grant/cmd/grant.go, services/promotion/controllers.go
adding vbat expiry with default val of 11/2/2023 (#2193)
=> production 2023-11-01_1

libs/httpsignature/httpsignature.go, tools/payments/report.go, tools/payments/report_test.go
=> Add transaction amount validation and tests

tools/payments/client.go
=> Use response date in verification 

libs/payments/api.go
=> Bypass statging ALB

libs/payments/api.go
=> Bytpass staging ALB

nitro-shim/Dockerfile
=> Add awscli to shim container

nitro-shim/Dockerfile
=> Add openssl to shim

services/payments/state_verifier.go
=> Add working PCR to valid past PCRs

services/payments/service.go
=> fix kms key reuse

services/payments/service.go
=> Kms key init

services/skus/model/model.go, services/skus/service.go
This PR updates the new `CreateOrder` method with the functionality for Radom from the legacy `CreateOrderFromRequest` method. The functionality is added as it currently is (although some of the Radom stuff is incomplete, and some needs improvement after the initial implementation).
=> Bundles – Backport Radom to CreateOrder

services/skus/controllers.go, services/skus/service.go
This PR is a result of me familiarising myself with order cancellation and Stripe webhook handling, and tidying it up in the process. There are no functional/behavioural changes.
=> Tidy Up Order Cancellation Code

.github/workflows/ci.yml, .github/workflows/golangci-lint.yml, .golangci.yaml, Dockerfile, docker-compose.dev-refresh.yml, services/rewards/docker-compose.yml, services/skus/docker-compose.payment-refresh.yml, services/skus/docker-compose.yml, services/wallet/docker-compose.yml, tools/Dockerfile
Subj.
Also, dependency updates from #2250 are failing due to missing features from Go 1.19 because we are still on 1.18.
=> Update Go Build and Runtime to 1.19

.github/CODEOWNERS
=> attempt to lock down authorizers keys in nitro payments

libs/wallet/provider/uphold/uphold.go
updated cert fingerprints for uphold
=> updated cert fingerprints for uphold

services/ratios/mapping.go
Add bonk mapping for ratios service (#2283)
=> production 2024-01-10_1

services/skus/controllers.go
This release includes
* https://github.com/brave-intl/bat-go/pull/2285
=> Production 2024-01-10_01

services/wallet/controllers_v4.go, services/wallet/controllers_v4_test.go, services/wallet/outputs.go, services/wallet/service.go
This release includes 
* https://github.com/brave-intl/bat-go/pull/2287
=> Production 2024-01-10_02

services/skus/controllers.go
Remove extra validation check from submit receipt endpoint
resolves [#186](https://github.com/brave-intl/payment-services/issues/186)
=> Remove extra validation check from submit receipt endpoint

services/skus/controllers.go
Add enhanced logging to submit receipt endpoint
=> fix: add logging to submit receipt

services/wallet/controller_v3_test.go, services/wallet/controllers_v3.go, services/wallet/model/model.go, services/wallet/storage/storage.go, services/wallet/storage/storage_test.go
Add specific challenge not found error
resolves #2292
=> refactor: add specific challenge not found error

services/wallet/controllers_v3.go
Use generic internal server error on sol link endpoint.
resolves [#188](https://github.com/brave-intl/payment-services/issues/188)
=> refactor: use generic internal server error on sol link endpoint

services/grant/cmd/grant.go, services/wallet/cmd/rest_run.go, services/wallet/controllers_v3.go, services/wallet/controllers_v3_pvt_test.go, services/wallet/controllers_v3_test.go, services/wallet/controllers_v4_test.go, services/wallet/datastore_test.go, services/wallet/service.go
This release includes:
* https://github.com/brave-intl/bat-go/pull/2300
* https://github.com/brave-intl/bat-go/pull/2299
=> Production 2024-01-15_01

services/grant/cmd/grant.go
This PR fixes the method used for creating orders in `local` environment. I forgot to update it since have not used this environment for a while. Other environments use the correct method.
=> Fix: Use Proper Handler Method in Local Env

services/wallet/controllers_v3_test.go, services/wallet/service.go
This PR adds option endpoints for use with challenge and connect Solana.
This should cover any CORS pre-flight requests to the endpoints `v3/wallet/challenges` and `v3/wallet/solana/{paymentID}/connect`.
resolves #2303
=> feat: add option endpoints for challenge and connect solana

services/grant/cmd/grant.go, services/wallet/controllers_v3_test.go, services/wallet/service.go
* https://github.com/brave-intl/bat-go/pull/2304
* https://github.com/brave-intl/bat-go/pull/2302
=> Production 2024-01-18_01

services/skus/controllers.go
=> Production 2024-01-19_01

services/wallet/service.go
This PR increases the rate limit for `GET v4/wallets` to seven.
resolves [#201](https://github.com/brave-intl/payment-services/issues/201)
=> feat: increase rate limit on get v4 wallets

services/go.mod, services/skus/controllers.go, services/skus/controllers_test.go, services/skus/receipt.go, services/skus/service.go
This PR presents a refactor for the receipt validation code as I will need to re-use some parts in the upcoming feature work.
Main points:
- Tidied up the `SubmitReceipt` function (use of proper context, early error handling, etc).
- Got rid of the nasty global state such as the clients and the map with functions.
- Reimplemented the validation functions in a way that enables further testing.
- Removed unnecessary type erasure (the use of empty interface for passing receipts). That is unnecessary as we only have one type, and even if it needed to be extended later, there are better ways to do so.
=> Refactor: Improve Receipt Validation

services/go.mod, services/skus/controllers.go, services/skus/controllers_test.go, services/skus/receipt.go, services/skus/service.go, services/wallet/controllers_v4.go, services/wallet/controllers_v4_test.go, services/wallet/model/model.go, services/wallet/model/model_test.go, services/wallet/service.go, services/wallet/storage/storage.go, services/wallet/storage/storage_test.go
- #2307
- #2311
- #2310
- #2306
=> Production 2024-01-23_01

libs/wallet/provider/uphold/uphold.go
=> fix: update uphold intermediate certs

libs/wallet/provider/uphold/uphold.go
=> Production 2024-29-01_01

services/skus/controllers.go, services/skus/controllers_pvt_test.go, services/skus/controllers_test.go, services/skus/input.go, services/skus/service.go
This PR adds authentication to the Android webhook endpoint.
Note: there is a separate PR to fix the other issues with the endpoint and cleanup the code. While this is being fixed extra logging is in place which will be cleaned up later.
resolves [#196](https://github.com/brave-intl/payment-services/issues/196)
=> feat: add jwt validation to android webhook

services/skus/controllers.go, services/skus/controllers_pvt_test.go, services/skus/controllers_test.go, services/skus/input.go, services/skus/service.go
=> Production 2024-29-01_02

libs/handlers/handlers.go, services/skus/controllers.go, services/skus/controllers_noint_test.go, services/skus/controllers_test.go, services/skus/input.go, services/skus/model/model.go, services/skus/receipt.go, services/skus/response.go, services/skus/service.go, services/skus/service_nonint_test.go, services/skus/skus.go, services/skus/skus_test.go, services/skus/storage/repository/mock.go
=> Production 2024-01-30_01

services/skus/controllers.go, services/skus/handler/handler.go, services/skus/model/model.go, services/skus/receipt.go, services/skus/service.go, services/skus/service_nonint_test.go, services/skus/skus.go, services/skus/skus_test.go
=> Production 2024-02-02_01

services/wallet/controllers_v3.go, services/wallet/datastore.go, services/wallet/datastore_pvt_test.go
This PR adds a specific linking limit error for Solana.
resolves [#2333](https://github.com/brave-intl/bat-go/issues/2333)
=> feat: add specific linking limit error for solana

services/skus/model/model.go
=> Production 2024-02-06_01

services/skus/model/model.go
=> fix: return orderId instead of order_id json

services/skus/model/model.go
=> Production 2024-02-06_02

services/wallet/controllers_v3.go
Changes include:
* https://github.com/brave-intl/bat-go/pull/2339
=> Production Release 2024-02-06_01

.github/workflows/generalized-deployments.yaml
=> build nitro-payments-dev docker image

services/skus/order.go
=> fix: do not delete credentials upon order renewal

libs/redisconsumer/consumer.go, libs/redisconsumer/consumer_test.go, tools/payments/client.go
fixes https://github.com/brave-intl/bat-go/issues/2218
=> Chunk messages when enqueuing into Redis

Makefile
build: update docker compose command in makefile
=> build: update docker compose command in makefile

Makefile, services/skus/controllers.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/model/model.go, services/skus/service.go
=> Production 2024-02-23_01

services/skus/controllers.go, services/skus/controllers_noint_test.go, services/skus/receipt.go, services/skus/receipt_test.go
This PR fixes the validate google submit receipt checks and also removes the unnecessary dependency on the awa lib. To fully remove the lib we will also need to refactor validate IOS in a separate PR.
**Linking Conditions:**
We should not allow a user to link when their subscription is either in a pending or expired state.
=> fix: validate google submit receipt

services/skus/controllers.go, services/skus/controllers_noint_test.go, services/skus/receipt.go, services/skus/receipt_test.go
This PR reapplies validate google submit receipt after reverting to release
=> fix: reapply validate google submit receipt

services/skus/controllers.go, services/skus/controllers_noint_test.go, services/skus/receipt.go, services/skus/receipt_test.go
=> Production 2024-02-26_02

libs/redisconsumer/consumer.go, services/payments/worker.go
=> Add nitro URI env var and smaller chunk size

libs/redisconsumer/consumer.go, services/payments/worker.go
=> Remove unneeded import

Dockerfile
this PR removes `payments` as a separate build target since it is not necessary and makes automated builds more difficult. previously it was needed because we had no way to override the entrypoint / command of the enclave image, however we now can and do specify it via `EIF_COMMAND`.
=> remove separate payments docker build target

libs/clients/zebpay/client.go
=> Add response data to zebpay status check error

services/skus/service_nonint_test.go, services/skus/skus.go, services/skus/skus_test.go
This PR updates the price for Leo monthly to 14.99.
This is mainly to keep the systems up to date, as this pricing is only kept in the order data linked for mobile, as desktop subscriptions receive their pricing from a different source.
=> feat: update leo monthly price to 14.99

libs/clients/zebpay/client.go, services/payments/live_zebpay_test.go, services/payments/statemachine_zebpay.go
- Change Zebpay Pay function to proceed with submission when checking
the status of a transaction results in a 404.
- Update live Zebpay test to work correctly with the new changes.
=> Update Zebpay State Machine

services/skus/receipt.go
This PR fixes two issues:
- the old code assumed there would only be one in-app purchase, which is wrong – there are users who have more than one in-app purchase with us;
- checks that the supplied product name is actually valid – since the receipt is decoded and validated by Apple, we can trust it.
Will add tests later.
=> fix: check ios purchase carefully

services/skus/receipt.go
=> Production 2024-03-22_01

libs/payments/state.go, services/payments/statemachine_solana.go
=> Add field to persist external idempotency data for Solana

libs/wallet/provider/uphold/uphold.go
=> Update CA Certs for Uphold

services/payments/live_solana_test.go, services/payments/statemachine.go, services/payments/statemachine_solana.go
=> Solana integration tests improvement

services/payments/live_solana_test.go, services/payments/statemachine.go, services/payments/statemachine_solana.go
=> WIP integration test

services/skus/controllers_test.go, services/skus/receipt.go, services/skus/receipt_test.go
=> Production 2024-04-03_01

services/payments/live_solana_test.go, services/payments/statemachine_solana.go
=> Sign and persist transaction data in Authorize

services/skus/receipt.go, services/skus/receipt_test.go, services/skus/skus.go, services/skus/skus_test.go
=> Production 2024-04-16_01

services/skus/datastore.go, services/skus/receipt.go, services/skus/receipt_test.go, services/skus/service.go
=> Production 2024-04-24_01

services/payments/controllers.go
=> Expose public key on info endpoint

tools/payments/cmd/disaster/main.go
=> Update DR CLI help text

services/payments/secrets.go
=> Add context to setEnvFromSecrets

services/payments/secrets.go, services/payments/statemachine.go, services/payments/statemachine_solana.go
=> Preserve solana key and improve logging

services/payments/worker.go
=> Speed up worker

Makefile, nitro-shim/tools/eifbuild/README.md, nitro-shim/tools/eifbuild/go.mod, nitro-shim/tools/eifbuild/go.sum, nitro-shim/tools/eifbuild/main.go, tools/payments/Makefile
- makefile: new `pcrs` target combining chained reproducible image build and enclave build
- eifbuild: allow for direct enclave build without pulling from image registry
- makefile: add cache used during reproducible image builds
- eifbuild: split command if passed as a single string
- eifbuild: prompt on empty env or command
=> PCR reproducibility improvements

services/payments/state_verifier.go
=> PCRs from Environment Variables

tools/payments/README.md, tools/payments/ipython-profile/.gitignore, tools/payments/ipython-profile/ipython_config.py, tools/payments/ipython-profile/startup/00-setup.py
=> Add ipython profile implementing payments shell

.dockerignore, .gitignore
=> ignore enclave build artifacts and vendored tools

services/payments/statemachine_solana.go
=> Decrease fee max

services/payments/statemachine_solana.go
=> Increase compute unit limit

services/skus/controllers.go
This PR updates logging in iOS webhook handling with granular levels and messaging.
=> chore: improve logging in ios webhook handling

services/skus/controllers.go
=> Production 2024-05-16_01

services/payments/statemachine_solana.go
=> Increase priority fee

libs/wallet/provider/uphold/uphold.go
=> Update Uphold CA

libs/wallet/provider/uphold/uphold.go
=> Update Uphold CA (#2535)

services/skus/service.go
Subj. After releasing to Dev, found that I forgot to attach the TLV2 repository to the service, which resulted in panics.
=> fix: attach forgotten tlv2 repository

services/skus/service.go
=> fix: attach forgotten tlv2 repository (#2542)

services/payments/statemachine_solana.go
=> Solana limit change

services/payments/statemachine.go
=> Do not update ExternalIdempotency if it's already set

services/promotion/service.go
promotion.Service.hotWallet is not used after the initialization. Thus the role of the relevant initialization code is reduced to verifying the grant wallet environment. But this is done in IsUserKYC in any case. So remove the relevant code.
- [ x] Development
- [ x] Does your code build cleanly without any errors or warnings?
- [ x] Have you squashed all intermediate commits?
- [ x] Is there a clear title that explains what the PR does?
- [ x] Have you performed a self review of this PR?
=> chore: remove promotion.Service.hotWallet

services/skus/controllers.go, services/skus/controllers_noint_test.go, services/skus/playstore.go, services/skus/playstore_test.go, services/skus/receipt.go, services/skus/receipt_test.go
This PR improves receipt verification for Android and cleans it up prior to improving webhooks, as this code will also be used in there.
This PR brings back most of the ideas from #2392 which had been reverted in #2427 (for reasons not related to the code).
=> fix: improve and simplify android receipt verification

libs/nitro/handlers.go
it's very noisy and otherwise can overwhelms the nitro settlement logs when debugging
=> move nitro healthcheck logging to trace level

Makefile, tools/payments/ipython-profile/ipython_config.py, tools/payments/ipython-profile/startup/00-setup.py
we needed to opt into copy layer caching and also ensure the `mtime` of the files were normalized in order for it to work properly. to do so I changed the `docker-reproducible` command to always create a new clean temporary clone of the repository and set mtime based on git changes.
=> improve kaniko caching and add to payments shell

tools/payments/ipython-profile/startup/00-setup.py
=> print out maximum payout value when loading into settlement shell

tools/payments/Makefile
=> Add report to top-level make commands

libs/clients/client.go, services/payments/controllers.go, tools/payments/report.go
=> Add basic maximum payment value protections in tooling and enclave

libs/payments/streams.go, libs/payments/transitions.go, libs/redisconsumer/consumer.go, services/payments/worker.go
=> payments worker: keep a counter of settlement final statuses

services/payments/service.go
=> Panic on failed policy match to force container reboot

services/payments/controllers.go, services/payments/live_solana_test.go, services/payments/statemachine_solana.go
=> Remove unused import

tools/payments/cmd/authorize/main.go
=> Hard code custodial batch size by custodian

.github/workflows/generalized-deployments.yaml
With Flux upgraded, reproducible builds can be enabled.
=> Update actions, enable reproducible builds

services/payments/statemachine.go
=> Retain existing LastError if it's non-nil and the new state has no LastError

tools/payments/cmd/chain-account/go.mod, tools/payments/cmd/report/go.mod
Fix typos in module names in go.mod files.
=> go mod typos fix

libs/clients/reputation/client.go
Remove unused cohort vars
resolves https://github.com/brave-intl/payment-services/issues/225
=> refactor: remove unused cohort vars

main/go.mod, main/go.sum, services/go.mod, services/go.sum, tools/go.mod, tools/go.sum
Subj.
Fixes https://github.com/brave-intl/bat-go/security/dependabot/131 and https://github.com/brave-intl/bat-go/security/dependabot/132.
=> chore: update dependencies

libs/clients/reputation/client.go, libs/clients/reputation/instrumented_client.go, libs/clients/reputation/mock/mock.go, services/wallet/controllers_v3.go, services/wallet/controllers_v3_test.go, services/wallet/service.go
This PR adds a check against the wallet geo country and parameters allow/block list when linking Solana addresses.
If the wallet geo county does not pass the [allow/block list check](https://github.com/brave-intl/bat-go/pull/2580/files#diff-9751b7432d0f485eae824a65612112872a8159b20c5ef1dd38484ec015dc4a84R749) it should not be able to link.
resolves https://github.com/brave-intl/payment-services/issues/222
=> feat: reject linkings based on wallet geo country

Dockerfile
Currently we are hitting a docker hub rate limit on builds in bat-go. 
This PR uses AWS ecr public image for docker images to get around the rate limit.
=> build: use aws ecr public image for docker images

services/skus/skus.go, services/skus/skus_test.go
Subj. Support for these new products has been requested:
- `beta.braveleo.monthly`
- `nightly.braveleo.monthly`
- `beta.braveleo.yearly`
- `nightly.braveleo.yearly`
=> feat: add new products for iOS

services/skus/skus.go, services/skus/skus_test.go
Subj. Support for these new products has been requested:
- `beta.braveleo.monthly`
- `nightly.braveleo.monthly`
- `beta.braveleo.yearly`
- `nightly.braveleo.yearly`
=> feat: add new products for ios nightly and beta

services/skus/playstore.go
Subj. Forgot one place, and the review of #2560 did not catch it.
=> fix: use pointer receiver instead of value

.github/workflows/ci.yml, services/skus/appstore.go, services/skus/appstore_test.go, services/skus/controllers.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/model/model.go, services/skus/order.go, services/skus/playstore.go, services/skus/playstore_test.go, services/skus/receipt.go, services/skus/receipt_test.go, services/skus/service.go, services/skus/service_nonint_test.go, services/skus/skus.go, services/skus/skus_test.go, services/skus/storage/repository/mock.go
This PR updates the endpoint for creating orders (with mobile receipts) to use the expiry date from the vendor's subscription instead of the hardcoded 1 month. This will address the issues that come from inaccurate expiry date, most notably – for annual products.
- `handleCreateOrderFromReceipt` endpoint now uses the expiry date from the receipt instead of 1 month.
- although `handleSubmitReceipt` has not been used, it's been updated accordingly;
- `handleCheckOrderReceipt` has been updated as well;
- CI will run on pull requests to any branch other than `nitro-payments-dev`;
- cleaned a bunch of old code from `Service` and `Datastore`;
- the code for receipt validation now returns relevant data from receipt, such as expiry time;
- the receipt validation code for iOS now also checks the …
=> fix: set proper order expiration upon linking

.github/workflows/ci.yml, Dockerfile
Subj. To avoid rate limiting by Docker.
=> feat: use docker login

services/skus/appstore.go, services/skus/controllers.go, services/skus/playstore.go
This PR adds the package name (and bundle id for iOS) to log output when processing mobile webhooks.
=> feat: log package in mobile webhooks

.github/workflows/ci.yml, Dockerfile, services/skus/appstore.go, services/skus/controllers.go, services/skus/playstore.go
=> Production 2024-07-18_02

.github/workflows/ci.yml, services/skus/appstore.go, services/skus/appstore_test.go, services/skus/controllers.go, services/skus/datastore.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go, services/skus/model/model.go, services/skus/order.go, services/skus/playstore.go, services/skus/playstore_test.go, services/skus/receipt.go, services/skus/receipt_test.go, services/skus/service.go, services/skus/service_nonint_test.go, services/skus/storage/repository/mock.go
=> Production 2024-07-18_03

services/skus/appstore.go, services/skus/controllers.go, services/skus/order.go, services/skus/playstore.go, services/skus/playstore_test.go, services/skus/receipt.go, services/skus/service.go, services/skus/service_nonint_test.go, services/skus/stripe.go, services/skus/stripe_test.go, services/skus/testdata/stripe_invoice_paid.json, services/skus/testdata/stripe_sub_deleted.json
=> Production 2024-07-23_01

services/skus/controllers.go
Add logging to endpoints get order creds and get order creds by id.
resolves #2613
=> refactor: add logging to endpoints get order creds and get order creds by id

libs/wallet/provider/uphold/uphold.go
=> fix: update uphold cert

libs/wallet/provider/uphold/uphold.go, services/skus/controllers.go
* https://github.com/brave-intl/bat-go/pull/2614
* https://github.com/brave-intl/bat-go/pull/2615
=> Production 2024-07-24_01

services/skus/skus.go, services/skus/skus_test.go
Remove ios leo monthly and annual for beta
=> refactor: remove ios leo monthly and annual for beta

services/skus/skus.go, services/skus/skus_test.go
=> Production 2024-07-25_01

services/skus/service.go
This PR resolves the unreachable condition error we are seeing on the get order credential endpoint.
It seems there was a race condition between fetching the single use credentials [here](https://github.com/brave-intl/bat-go/compare/fix-unreachable-condition-error?expand=1#diff-225dad392327a49c7aa0c5287edf78e66ae94759a42c08d4207299c0e0d6e895L1196) and checking whether the signing had been completed [here](https://github.com/brave-intl/bat-go/compare/fix-unreachable-condition-error?expand=1#diff-225dad392327a49c7aa0c5287edf78e66ae94759a42c08d4207299c0e0d6e895L1220). This resulted in the credentials being signed in between the two calls, hence `completedAt` is not equal to null and we hit the unreachable condition.
resolves https://github.com/brave-intl/bat-go/issues/2621
=> fix: resolve get order creds unreachable condition error

services/skus/credentials.go, services/skus/model/model.go, services/skus/service_nonint_test.go, services/skus/storage/repository/tlv2_test.go
Correct typo in req id mismatch
=> refactor: correct typo in req id mismatch

.github/workflows/ci.yml
Update docker compose command in ci.yml to use new command.
=> build: update docker compose command in ci.yml

.github/workflows/ci.yml, libs/context/keys.go, services/skus/appstore.go, services/skus/appstore_test.go, services/skus/credentials.go, services/skus/model/model.go, services/skus/receipt.go, services/skus/receipt_test.go, services/skus/service.go, services/skus/service_nonint_test.go, services/skus/storage/repository/tlv2_test.go
* https://github.com/brave-intl/bat-go/pull/2622
* https://github.com/brave-intl/bat-go/pull/2624
* https://github.com/brave-intl/bat-go/pull/2626
* https://github.com/brave-intl/bat-go/pull/2628
* #2629
=> Production 2024-08-06_01

services/skus/xstripe/xstripe.go
Forgot one small thing which is not to use the stupid helper from the `stripe` package.
=> fix: don't use stripe helper

services/skus/credentials.go, services/skus/service.go, services/skus/service_nonint_test.go, services/skus/storage/repository/mock.go, services/skus/storage/repository/tlv2.go, services/skus/storage/repository/tlv2_test.go
=> Production 2024-08-22_01

services/skus/controllers.go, services/skus/service.go
=> fix: use leo annual issuer if redemption fails for regular leo (#2647)

services/skus/credentials.go, services/skus/datastore.go, services/skus/datastore_test.go, services/skus/instrumented_datastore.go, services/skus/mockdatastore.go
=> Production 2024-08-28_01

services/skus/credentials.go, services/skus/credentials_noint_test.go, services/skus/model/model.go, services/skus/model/model_test.go, services/skus/service.go, services/skus/service_nonint_test.go, services/skus/service_test.go, services/skus/skus.go, services/skus/skus_test.go, services/skus/storage/repository/mock.go, services/skus/storage/repository/tlv2.go, services/skus/storage/repository/tlv2_test.go
=> Production 2024-09-10_01

services/skus/model/model.go, services/skus/skus.go, services/skus/skus_test.go
=> Production 2024-09-17_01

libs/wallet/provider/uphold/uphold.go
=> fix: update cert for uphold

services/skus/datastore.go, services/skus/service.go, services/skus/service_test.go
=> fix: change order of get tlv2 credentials

services/skus/datastore.go, services/skus/service.go, services/skus/service_test.go
- https://github.com/brave-intl/bat-go/pull/2664
=> Production 2024-10-16_01

services/skus/service.go
This PR adds logging for the error case I need to debug.
=> fix: log when issuer id does not match

services/skus/service.go
=> Production 2024-10-18_01

services/skus/service.go
This PR fixes (in a hacky way) the wrong issuer sent by the client for annual products.
=> fix: fix incorrect issuer received from client

services/skus/service.go
=> Production 2024-10-18_02

services/skus/skus.go, services/skus/skus_test.go
=> Production 2024-10-24_01

services/skus/service.go
* https://github.com/brave-intl/bat-go/pull/2676
=> Production 2024-10-25_02

.github/workflows/generalized-deployments.yaml, services/skus/skus.go, services/skus/skus_test.go
=> Production 2024-10-29_01

services/rewards/controllers_test.go, services/rewards/service.go
This PR disables/removes the TOS from the `GET /parameters` response until it is required.
N.B. This is not live in production at this time.
=> refactor: disable tos

services/skus/stripe.go
This PR fixes a type in the stripe no invoice error.
The error message is only logged and returned to Stripe so there should not be a dependency on the text.
=> refactor: fix typo in stripe error

services/rewards/controllers.go, services/rewards/controllers_test.go, services/rewards/service.go
This PR removes the s3Client interface from rewards and cleans up some of the logging.
N.B. a subsequent [ticket](https://github.com/brave-intl/bat-go/issues/2691) will remove the dependency on the AWS base config in libs.
resolves: https://github.com/brave-intl/bat-go/issues/2689
=> refactor: remove s3Client interface from rewards and cleanup

services/skus/service.go
This PR updates order linking such that when an existing order is found, it is also updated with the most recent expiry date.
The current behaviour (prior to this PR) has been unchanged for a while, and resulted in issues such as when someone attempted linking again (example: during the issues with handling annual from mobile), the existing order would be returned even though it had already expired.
A more correct way of handling such situations is to update the order expiry date to the most recent date taken from the mobile receipt before returning. Doing so will solve issues possibly experienced by those who linked annual VPN from mobile before July 2024, _if they attempt to link again_, and will make QA process slightly easier.
=> fix: update order expiry when found one during linking

libs/wallet/provider/uphold/uphold.go
Renew Uphold intermediate cert
=> fix: renew uphold cert

libs/wallet/provider/uphold/uphold.go
* https://github.com/brave-intl/bat-go/pull/2716
=> fix: renew uphold cert (#2716)

services/skus/service.go
This PR partially revers https://github.com/brave-intl/bat-go/pull/2709, it brings back the special handling, but keeps the added tests.
=> fix: bring back special handling for leo

libs/wallet/provider/uphold/uphold.go
=> Update uphold fingerprint

services/skus/service_test.go
Use static value for time now in test
=> test: use static value for time now in test

services/skus/service.go
Remove redundant word in comment
=> chore: remove redundant word in comment

services/rewards/cmd/rest_run.go, services/rewards/service.go, services/rewards/service_test.go
- https://github.com/brave-intl/bat-go/pull/2750
=> Production 2025-01-29_02

services/skus/controllers.go
This PR adds improved logging the get creds by id endpoint
=> Imprv get cred logging

.github/workflows/ci.yml, .github/workflows/generalized-deployments.yaml, services/skus/controllers.go
Changes Include:
* https://github.com/brave-intl/bat-go/pull/2755
=> Production 2025-02-05_01

services/skus/controllers.go
=> fix: log correct http status

services/skus/service.go, services/skus/service_nonint_test.go, services/skus/stripe.go, services/skus/xstripe/mock.go, services/skus/xstripe/xstripe.go
Cancel monthly sub when upgrade to annual.
=> feat: cancel monthly sub when upgrade to annual

services/skus/service.go, services/skus/service_nonint_test.go, services/skus/stripe.go, services/skus/xstripe/mock.go, services/skus/xstripe/xstripe.go
* https://github.com/brave-intl/bat-go/pull/2769
=> Production Release 2025-02-03_01

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/generalized-deployments.yaml, .github/workflows/golangci-lint.yml, services/ratios/controllers.go, services/ratios/controllers_test.go, services/ratios/inputs.go, services/ratios/service.go
* https://github.com/brave-intl/bat-go/pull/2771
* Some renovate updates
=> Production Release 2025-03-06_01

services/grant/cmd/grant.go, services/skus/controllers.go
The following endpoints are being removed:
/transactions/uphold
/transactions/gemini
/votes
=> refactor: removing multiple endpoints to disable auto contribution

services/grant/cmd/grant.go, services/skus/controllers.go
The following endpoints are being removed: 
/transactions/uphold
/transactions/gemini
/votes
=> Production Release 2025-03-11_01

.github/workflows/ci.yml
docker compose is now included in docker-cli
=> ci.yml: docker compose is now included in docker-cli

services/rewards/cmd/rest_run.go, services/rewards/cmd/rewards.go, services/rewards/controllers_test.go, services/rewards/service.go
Use config rather than retrieving the param bucket from from ctx
closes https://github.com/brave-intl/bat-go/issues/2692
=> refactor: rewards remove param from ctx

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml
=> fix: autopin dependencies

services/skus/service.go
This PR uses a specific radomSubscriptionId instead of external id
closes https://github.com/brave-intl/bat-go/issues/2798
=> refactor: use radomSubscriptionId instead of external id

services/skus/radom/radom.go, services/skus/service.go, services/skus/service_nonint_test.go
This PR adds a discount for using BAT tokens when creating Radom checkout sessions.
closes #2816
=> refactor: add discount for radom bat

services/skus/controllers.go, services/skus/controllers_test.go, services/skus/model/model.go, services/skus/radom/radom.go, services/skus/radom/radom_test.go, services/skus/service.go, services/skus/service_nonint_test.go
This PR adds Radom checkout session to get orders flow.
closes https://github.com/brave-intl/bat-go/issues/2820
=> Add Radom checkout session to get orders flow

.github/workflows/ci.yml
=> go 1.19 remove

services/wallet/controllers_v3_int_test.go, services/wallet/service.go
=> refactor: add toggle for solana address checker

services/wallet/controllers_v3_int_test.go, services/wallet/service.go
Changes Include:
* https://github.com/brave-intl/bat-go/pull/2850
=> Production Release 2025-05-21

services/skus/radom/notification.go, services/skus/radom/notification_test.go, services/skus/service.go, services/skus/service_nonint_test.go
This PR handles payment failure and overdue subscription events for Radom.
closes https://github.com/brave-intl/bat-go/issues/2852
=> refactor: record subscription payment failures for radom

libs/wallet/provider/uphold/uphold.go, libs/wallet/provider/uphold/uphold_test.go, services/skus/radom/notification.go, services/skus/radom/notification_test.go, services/skus/service.go, services/skus/service_nonint_test.go
* https://github.com/brave-intl/bat-go/pull/2856
* https://github.com/brave-intl/bat-go/pull/2853
* https://github.com/brave-intl/bat-go/pull/2855
=> Production 2025-05-23_01

services/skus/controllers_test.go, services/skus/model/model.go, services/skus/radom/radom.go, services/skus/service.go, services/skus/service_nonint_test.go
This PR adds a URL to the Radom create checkout session request.
=> refactor: add sub back button url to radom checkout session request

libs/middleware/request_correlation.go, libs/middleware/request_logger.go, services/cmd/serve.go, services/grant/cmd/grant.go
Handling of external id's to be added to the logging.
Related to https://github.com/brave-intl/subscriptions/issues/673.
Edit: Related to https://github.com/brave-intl/subscriptions/issues/650.
=> feat: add external request logging

.github/renovate.json, .github/workflows/codeql-analysis.yml, .github/workflows/generalized-deployments.yaml, libs/middleware/request_correlation.go, libs/middleware/request_logger.go, services/cmd/serve.go, services/grant/cmd/grant.go, services/skus/controllers_test.go, services/skus/model/model.go, services/skus/radom/radom.go, services/skus/service.go, services/skus/service_nonint_test.go
* https://github.com/brave-intl/bat-go/pull/2849
* https://github.com/brave-intl/bat-go/pull/2861
* https://github.com/brave-intl/bat-go/pull/2864
* https://github.com/brave-intl/bat-go/pull/2860
=> Production 2025-06-16_01

services/skus/controllers_test.go, services/skus/radom/radom.go, services/skus/service.go, services/skus/service_nonint_test.go
add sub back button url to radom checkout session top level
=> refactor: add sub back button url to radom checkout session top level

services/skus/controllers_test.go, services/skus/radom/radom.go, services/skus/service.go, services/skus/service_nonint_test.go
* https://github.com/brave-intl/bat-go/pull/2866
=> Production 2025-06-17_01

services/skus/model/model.go, services/skus/model/model_test.go, services/skus/service.go, services/skus/service_test.go
=> fix: use correct expires at for annual subs when time chunking

services/skus/model/model.go, services/skus/model/model_test.go, services/skus/service.go, services/skus/service_test.go
* https://github.com/brave-intl/bat-go/pull/2868
=> Productuion Release 2025-06-18_01

services/skus/service.go, services/skus/service_test.go, services/wallet/controllers_v3.go
* https://github.com/brave-intl/bat-go/pull/2870
* https://github.com/brave-intl/bat-go/pull/2871
* https://github.com/brave-intl/bat-go/pull/2665
* https://github.com/brave-intl/bat-go/pull/2875
=> Production 2025-08-08_01

README.md
* https://github.com/brave-intl/bat-go/pull/2879
=> Production 2025-07-10_01

services/skus/skus.go, services/skus/skus_test.go
This PR adds the necessary sku, orders and mobile mappings for brave origin.
closes https://github.com/brave-intl/bat-go/issues/2885
=> feat: add skus order items and mobile mappings for brave origin

services/wallet/controllers_v3_int_test.go, services/wallet/controllers_v4_test.go
This PR cleans up the wallet controller tests.
=> test: cleanup wallet controller tests

services/wallet/controllers_v4.go, services/wallet/controllers_v4_test.go, services/wallet/model/model.go, services/wallet/model/model_test.go, services/wallet/service.go, services/wallet/storage/storage.go, services/wallet/storage/storage_test.go
=> refactor: add allow list check back to get wallet endpoint

services/skus/controllers.go
This PR improves the order linking logging,
close https://github.com/brave-intl/bat-go/issues/2905
=> reactor: improve order linking logging

services/skus/service_test.go
Temporary fix for flaky time chunk test
=> test: temp fix flaky time chunk

libs/go.mod, libs/go.sum, main/go.mod, main/go.sum, services/go.mod, services/go.sum
This PR updates github.com/segmentio/kafka-go to v0.4.49
=> build: update github.com/segmentio/kafka-go to v0.4.49

.github/workflows/ci.yml, .github/workflows/generalized-deployments.yaml, services/skus/service.go
**Feat**
* https://github.com/brave-intl/bat-go/pull/2936
**Build**
* https://github.com/brave-intl/bat-go/pull/2932
=> Production 2025-09-24_01

services/skus/controllers.go
This PR adds extra error logging to handle the verify creds v1 and v2 endpoints.
closes https://github.com/brave-intl/bat-go/issues/2940
=> refactor: add logging to handle verify creds v1 and v2
