.travis.yml
README.md
bin/create-tokens/main.go
controllers/grants.go
wallet/provider/uphold/errors.go

fixes for go 1.10

---

grant/grant.go
wallet/provider/uphold/errors.go

See https://github.com/brave/browser-laptop/issues/14297

don't take current balance into account

---

Gopkg.lock
Gopkg.toml
bin/create-tokens/main.go
bin/grant-server/main_test.go
grant/grant.go
utils/vaultsigner/vaultsigner.go

updated signing using vault

---

bin/vault-create-wallet/main.go
bin/vault-import-key/main.go
bin/vault-init/main.go
bin/vault-sign-settlement/main.go
bin/vault-unseal/main.go
utils/vaultsigner/vaultsigner_test.go

removed duplicate vault connect code

---

.travis.yml
bin/create-tokens/main.go
bin/create-tokens/main_test.go
bin/grant-server/main_test.go
bin/verify-tokens/main.go
grant/grant.go
grant/grant_test.go
grant/redeem.go
utils/vaultsigner/vaultsigner.go
utils/vaultsigner/vaultsigner_test.go

fix vault signing in create-tokens

---

controllers/grants.go
grant/breaker.go
grant/redeem.go

add new endpoint to check grant redemption status, tweak breaker sentry

---

Gopkg.lock
settlement/settlement.go
settlement/settlement_test.go

So it can be recorded in eyeshade for manual settlements.  Also update Gopkg.lock.
Resolves #58
Related to https://github.com/brave-intl/bat-ledger/pull/523

Add documentId to Transaction struct

---

.gitignore
bin/vault-transfer-funds/main.go

for one-off transactions using vault held keys

add vault-transfer-funds

---

settlement/settlement.go
wallet/provider/uphold/uphold.go

@corymcdonald would you kindly review given your experience with anonymous uphold cards? :)

changes needed to confirm anonymous card transactions

---

wallet/provider/uphold/uphold.go

pulled out cert update to make for quicker merge

updated cert fingerprint

---

migrations/0001_initial_schema.up.sql
promotion/claim.go
promotion/claim_summary.go
promotion/controllers.go
promotion/controllers_test.go
promotion/datastore.go
promotion/datastore_test.go
utils/handlers/handlers.go

Ads count endpoint

---

migrations/0001_initial_schema.up.sql
promotion/claim.go

added promotion platform null constraint

---

promotion/datastore.go

insert wallet on conflict do nothing

---

bin/grant-server/main_test.go
grant/claim.go
middleware/http_signed.go
middleware/http_signed_test.go
promotion/controllers.go
promotion/promotion.go
promotion/wallet.go
promotion/wallet_test.go
utils/ledger/client.go

fixes https://github.com/brave-intl/bat-go/issues/150

disable uuid validation and fix wallet 404

---

controllers/grants.go
promotion/controllers.go
utils/httpsignature/httpsignature.go
utils/requestutils/requestutils.go
wallet/provider/uphold/httpsigned.go
wallet/provider/uphold/uphold.go

added body read limiter

---

docker-compose.yml
grant/datastore.go
migrations/0003_claim_redeemed.down.sql
migrations/0003_claim_redeemed.up.sql
promotion/claim.go
promotion/claim_test.go
promotion/datastore.go

added redeemed_at column

---

Dockerfile
bin/grant-server/main.go

This reverts commit 5c83db08c7b65476590d81a06c03603ede058fa5.

Revert "log commit on start"

---

promotion/controllers_test.go
promotion/datastore.go
promotion/promotion.go

exposed legacy_claimed

---

promotion/controllers.go
promotion/controllers_test.go
promotion/promotion.go

hide legacy claimed promotions unless migrate flag is passed

---

wallet/provider/uphold/uphold.go

```
[user@work:~/source/bat-go]% target/release/get-cert-fingerprint api.uphold.com:443
Dialing api.uphold.com:443
Issuer: CN=CloudFlare Inc ECC CA-2,O=CloudFlare\, Inc.,L=San Francisco,ST=CA,C=US Fingerprint: IYSLsapSKlkofKfi6M2hmS4gzXbQKGIX/DHBWIgstw4=
```

update Uphold cert fingerprint

---

go.mod
go.sum
utils/pindialer/dialer.go
wallet/provider/uphold/uphold_test.go

fixes #224 
as soon as #213 is merged, we should use apperror defined there

return error when cert is not recognized

---

controllers/grants.go
promotion/controllers.go

make claiming unavailable (#239)

---

utils/clients/client.go

logged requests for deep searching

---

promotion/controllers.go
promotion/promotion.go

added promotion exposure counters

---

utils/clients/client.go
utils/handlers/handlers.go

add apperror to the logging context, client fixup

---

promotion/claim_test.go
promotion/drain.go

cherry pick of https://github.com/brave-intl/bat-go/pull/289

fix rounding error falsely triggering drain protection

---

docker-compose.yml
payment/datastore.go

Was getting errors when creating issuers

Fix error with 'expected slice but got struct'

---

bin/grant-server/main.go

added a release to sentry to help track where bugs crop up

added release to sentry

---

payment/credentials.go

Fix JSON tags

---

controllers/grants.go
docker-compose.yml
payment/controllers.go
payment/controllers_test.go
payment/datastore.go
promotion/controllers.go
utils/handlers/handlers.go

Allows for a consumer to pass in an order item ID to get a single credential back.

Get credentials by item id

---

bin/grant-server/main.go
grant/redeem.go
promotion/suggestions.go
settlement/settlement.go
utils/handlers/handlers.go

stack traces are not currently captured and sent to sentry. this should help fix

convereted sentry captures to capture exceptions

---

grant/datastore_test.go
payment/controllers_test.go
payment/order_test.go
promotion/controllers_test.go
promotion/datastore_test.go

fail tests earlier with the appropriate messages

change assert to require in tests

---

datastore/grantserver/postgres.go
migrations/0012_add_sku_to_order_item.down.sql
migrations/0012_add_sku_to_order_item.up.sql
payment/controllers_test.go
payment/datastore.go
payment/order.go
payment/order_test.go
promotion/order.go

Adds the SKU to the order item. This reduces confusion on whether the order item ID is a internally managed ID or the merchant's ID.

Create SKU Field on Order Item

---

grant/datastore.go
promotion/datastore.go
promotion/datastore_test.go

3 month limit claims

---

go.mod
go.sum
payment/controllers.go
payment/credentials.go
payment/datastore.go
payment/vote.go
payment/vote_test.go

utilizing the sku on the order item to determine the vote funding source.

updates to use sku to inform the funding source for votes

---

cmd/macaroon-gen/.gitignore
cmd/macaroon-gen/README.md
cmd/macaroon-gen/example.yaml
cmd/macaroon-gen/main.go
cmd/macaroon-gen/token.go
go.mod

This tool will allow us to easily generate macaroon tokens through a configuration file on the command line.

adding macaroon command line generation utility

---

bin/macaroon-gen/ac_skus.yaml
payment/controllers.go
payment/controllers_test.go
payment/order.go

Since the `FEATURE_ORDERS` will be turned on we should only accept SKUs we know to be valid until we have validation logic programmed in.

Validate hard-coded SKUs

---

bin/grant-server/main.go
go.mod
go.sum
payment/datastore.go
payment/vote.go
utils/context/getters.go
utils/context/keys.go
utils/logging/logging.go

updated logging helper and cleaned up logging

---

middleware/prometheus.go

In flight instrumentation per handler

Add in flight handler to Prometheus 

---

middleware/prometheus.go
promotion/claim.go
promotion/drain.go
promotion/suggestions.go

Add metrics around Goroutines

---

bin/grant-server/main.go
controllers/grants.go
datastore/grantserver/postgres.go
docker-compose.dev-refresh.yml
docker-compose.yml
middleware/prometheus.go
payment/controllers.go
payment/controllers_test.go
payment/service.go
promotion/claim.go
promotion/controllers.go
promotion/drain.go
promotion/suggestions.go
utils/clients/client.go
utils/clients/reputation/proxy.go
utils/inputs/ids.go
utils/validators/validators.go
utils/validators/validators_test.go
wallet/provider/uphold/uphold.go

Adding profiling support, bugfix, sentry.Flush reduction changes, and more instrumentation.

Release 2020-05-06_1

---

.prom-gowrap.tmpl
Makefile
bin/grant-server/main_test.go
go.mod
go.sum
grant/instrumented_datastore.go
grant/instrumented_read_only_datastore.go
payment/instrumented_datastore.go
promotion/controllers_test.go
promotion/datastore.go
promotion/instrumented_datastore.go
promotion/instrumented_read_only_datastore.go
promotion/promotion.go
promotion/service.go
utils/clients/balance/instrumented_client.go
utils/clients/cbr/instrumented_client.go
utils/clients/ledger/instrumented_client.go
utils/clients/ratios/instrumented_client.go
utils/clients/reputation/instrumented_client.go
wallet/service/datastore.go
wallet/service/instrumented_datastore.go
wallet/service/instrumented_read_only_datastore.go

add guard to not return promotion with empty public keys, add worker to create new issuers for promotions missing public keys fixes: #382

Gaurd to prevent empty public keys for promotions

---

.prom-gowrap.tmpl
Makefile
bin/grant-server/main_test.go
cmd/settlement_paypal.go
go.mod
go.sum
grant/instrumented_datastore.go
grant/instrumented_read_only_datastore.go
payment/instrumented_datastore.go
promotion/controllers_test.go
promotion/datastore.go
promotion/instrumented_datastore.go
promotion/instrumented_read_only_datastore.go
promotion/promotion.go
promotion/service.go
utils/clients/balance/instrumented_client.go
utils/clients/cbr/instrumented_client.go
utils/clients/ledger/instrumented_client.go
utils/clients/ratios/instrumented_client.go
utils/clients/reputation/instrumented_client.go
wallet/service/datastore.go
wallet/service/instrumented_datastore.go
wallet/service/instrumented_read_only_datastore.go

- Two fixes to paypal settlement tools
- Guard against empty public keys

Release 2020-05-14

---

middleware/request_logger.go

filter client timeouts from sentry

---

README.md
bin/grant-server/main.go
payment/controllers_test.go
promotion/controllers_test.go
promotion/drain.go
promotion/promotion.go
promotion/service.go
utils/logging/logging.go
wallet/provider/uphold/uphold_test.go

attempt to register metric, and on error, set to existing registered value

Prometheus Promotion Metric Registration

---

payment/credentials.go
payment/credentials_test.go
promotion/suggestions.go
promotion/suggestions_test.go

* deduplicate suggestion claim credential bindings
* deduplicate bindings on votes
* linting cleanup
* remove cbr client deduplication
* adding tests to check the credential bindings deduplications on votes/suggestions

2020-05-21 RC

---

.github/PULL_REQUEST_TEMPLATE/pr.md

Add a pull request template :)

Add pull request template, fixes #364

---

bin/grant-server/main.go
bin/list-transactions/main.go
bin/settlement-submit/main.go
bin/transfer-funds/main.go
grant/service.go
promotion/controllers_test.go
promotion/service.go
wallet/provider/provider.go
wallet/provider/uphold/uphold.go
wallet/provider/uphold/uphold_test.go
wallet/service/service.go

adding a logger wallets, which is derived from context to match the way we setup logger

Uphold Wallet Logger Consistency

---

.gitignore
Makefile
bin/grant-server/main.go
bin/list-transactions/main.go
bin/settlement-submit/main.go
bin/transfer-funds/main.go
datastore/grantserver/postgres.go
grant/service.go
migrations/0015_funding_events.down.sql
migrations/0015_funding_events.up.sql
promotion/controllers.go
promotion/controllers_test.go
promotion/datastore.go
promotion/instrumented_datastore.go
promotion/service.go
utils/errors/errors.go
wallet/provider/provider.go
wallet/provider/uphold/uphold.go
wallet/provider/uphold/uphold_test.go
wallet/service/service.go

Fixes:
- Make uphold wallet logging consistent with everywhere else
Improvements:
- Make backups when generating prometheus interface wrappers
Features:
- Add endpoint for reporting BAT loss events

Release 2020-06-25

---

datastore/grantserver/postgres.go
go.mod
go.sum
migrations/0016_add_platform.down.sql
migrations/0016_add_platform.up.sql
promotion/controllers.go
promotion/controllers_test.go
promotion/datastore.go
promotion/instrumented_datastore.go
utils/errors/errors.go
utils/useragent/useragent.go
utils/useragent/useragent_test.go

added ua checking to populate platform column

---

Makefile
bin/grant-server/main.go
cmd/rewards.go
cmd/root.go
cmd/serve.go
cmd/wallets.go
cmd/wallets_rest_run.go
datastore/grantserver/postgres.go
go.mod
go.sum
middleware/prometheus.go
utils/clients/ledger/client.go
utils/context/keys.go
utils/inputs/decode.go
utils/inputs/inputs.go
utils/inputs/publickey.go
wallet/Dockerfile
wallet/README.md
wallet/controllers.go
wallet/controllers_test.go
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/docker-compose.yml
wallet/inputs.go
wallet/instrumented_datastore.go
wallet/instrumented_read_only_datastore.go
wallet/outputs.go
wallet/service.go

This PR implements a new wallets service which serves the v3 version of the wallet api.  This service is also included in the grant service artifact for fast deploy.

V3 wallets endpoints

---

wallet/controllers.go
wallet/controllers_test.go
wallet/controllers_v3_test.go
wallet/outputs.go

updates for uphold legacy flow and adjusting how wallet responses are rendered
Wallets were not being translated from the model to the required rendered output correctly.  
Wallet uphold creation flow changes to pass through creation request signature checking to uphold.
- [ x ] Bug fix
- [ x ] Does your code build cleanly without any errors or warnings?
- [ x ] Have you used auto closing keywords?
- [ n/a ] Have validated query efficiency for new database queries?
- [ n/a ] Have documented new functionality in README or in comments?
- [ x ] Have you squashed all intermediate commits?
- [ x ] Is there a clear title that explains what the PR does?
- [ x ] Have you used intuitive function, variable and other naming?
- [ x ] Have you performed a self review of this PR?

Wallet Response Formatting

---

wallet/controllers.go
wallet/controllers_test.go
wallet/outputs.go

removes duplicated endpoint and provides a means for converting new wallet structure to `wallet.info` structure

Remove v1 create wallet

---

utils/wallet/wallet.go
wallet/controllers_v3.go
wallet/outputs.go

turned keys into pointers

---

cmd/wallets_rest_run.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/inputs.go

PR to add-wallet-endpoints feature branch to change naming of unclear function.

Change ClaimUpholdWallet to LinkDepositAccount

---

cmd/wallets.go
cmd/wallets_rest_run.go

prod 2020-07-24.2

---

wallet/datastore.go
wallet/instrumented_datastore.go
wallet/service.go

fixes missing provider id for future links

fixed linking

---

wallet/datastore.go
wallet/instrumented_datastore.go
wallet/service.go

* fixed linking
* make new instrumented datastore
Co-authored-by: husobee <husobee@e-ie.io>

fixed linking (#455)

---

wallet/datastore.go

V2 Ledger Wallet APIs blow up if there is no provider ID specified on the wallet.

store provider_id for wallet

---

wallet/datastore.go

store provider_id for wallet (#457)

---

README.md
utils/wallet/provider/uphold/uphold.go

This PR pins the new Uphold API Certificate.
Degraded service due to "invalid" certificate.
Verify that Balance API in /v3/wallet/ endpoints works correctly.

New Uphold Certificate Pinning

---

README.md
utils/wallet/provider/uphold/uphold.go

* fixing uphold tls cert
* restart ci

New Uphold Certificate Pinning (#460)

---

wallet/controllers_test.go
wallet/controllers_v3.go

empty provider id abort

---

bin/grant-server/main.go
cmd/wallets.go
cmd/wallets_rest_run.go
datastore/grantserver/postgres.go
docker-compose.dev-refresh.yml
docker-compose.yml
migrations/0019_wallet_card_id.down.sql
migrations/0019_wallet_card_id.up.sql
promotion/controllers.go
promotion/controllers_test.go
promotion/drain.go
promotion/service.go
utils/wallet/wallet.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/datastore.go
wallet/service.go

Contains changes to store uphold card destination from the transaction.
Validate that on new uphold deposit provider claims we store the "destination" from the transaction.

Production Release 2020-08-17_1

---

middleware/request_logger.go
wallet/controllers_v3.go
wallet/datastore.go

* removing hard requirement for anon-address in api
* destination defaults to '' not null

Prod Release 2020-08-18_1

---

promotion/suggestions.go
wallet/controllers_v3.go
wallet/datastore.go

when
* bad uuid is encountered
* and error is returnable
return the error from uuid parsing instead of panicing unnecessarily (prefer validation error)

preferred returning errors when bad uuid encountered

---

middleware/rate_limiter.go

This is a minor adjustment to the rate limiting configuration.

Adjusting Rate Limit for Balance API calls

---

middleware/rate_limiter.go
promotion/controllers.go
promotion/service.go
promotion/suggestions.go
wallet/controllers_v3.go
wallet/datastore.go

Release Candidate 2020-08-24

---

migrations/0020_add_timestamps_to_wallets.down.sql
migrations/0020_add_timestamps_to_wallets.up.sql

Add migration file to add created_at and updated_at to wallets table

---

utils/errors/errors.go

added unwrap implementation to error bundle

added unwrap

---

migrations/0020_add_timestamps_to_wallets.down.sql
migrations/0020_add_timestamps_to_wallets.up.sql
utils/errors/errors.go

Release Candidate 2020-08-26

---

datastore/grantserver/postgres.go
migrations/0020_add_timestamps_to_wallets.up.sql

Specify 20 as the current migration version so the migration runs.

Bump current migration version in postgres.go

---

bin/settlement-submit/main.go
settlement/settlement.go
utils/logging/logging.go
utils/wallet/provider/uphold/errors.go
utils/wallet/wallet.go
wallet/datastore_test.go

This contains a few fixes for the settlement tooling from the last payout:
1. This adds an additional uphold error code for invalid destination, this is a non-recoverable error and is treated as such.
2. This fixes issues with local logging where diode does not fully flush before the program exits.
3. This adds a guard around one of our datastore tests so it only runs when we run integration tests.
I used this branch for settlement :)

settlement fixes: add uphold error code, fix local logging, integration test

---

promotion/claim.go
promotion/controllers_test.go

returns an app error so that a 410 (gone) is returned instead of another status code
fixes #472

used status gone for inactive promotion and tested

---

utils/pindialer/dialer.go
utils/wallet/provider/uphold/uphold.go

Change to use the intermediate certificate for validation instead of the leaf certificate.
fixes: #470

adding support for and now pinning on uphold intermediate certificate

---

datastore/grantserver/postgres.go
migrations/0022_coded_drains.down.sql
migrations/0022_coded_drains.up.sql
promotion/datastore.go
promotion/drain.go
utils/errors/errors.go
utils/wallet/provider/uphold/errors.go
utils/wallet/provider/uphold/uphold.go

fixes: #493 - adding error codes to drains

Adding Error Code to Drain Workers

---

payment/service.go

prevents an unnecessary warning log

updated prom registration

---

payment/controllers.go
promotion/controllers.go
promotion/service_test.go
utils/inputs/ids.go
wallet/controllers_v3.go

fixes utils/inputs to allow for optional inputs for id

added service test and converted uuid input to pointer

---

Dockerfile
Dockerfile.micro
Makefile
docker-compose.dev-refresh.yml

updated golang and used x509 ignore cn

---

cmd/vault/create_wallet.go
cmd/vault/import_key.go
cmd/vault/init.go
settlement/README.md

updated settlement notes 

---

payment/controllers_test.go
payment/service.go
promotion/controllers_test.go
promotion/service.go
utils/kafka/dialer.go

Make kafka dialer a public util

---

settlement/README.md

Update settlement readme

---

test/secrets/README.md

kafka: Clarify create-certs.sh distinguished name args

---

Makefile
settlement/Dockerfile

Changes to move online settlement submission into Argo.

Online Settlement Supporting Changes

---

datastore/grantserver/postgres.go
migrations/0019_wallet_card_id.down.sql
migrations/0019_wallet_card_id.up.sql
migrations/0023_public_key_index.down.sql
migrations/0023_public_key_index.up.sql

moved migration 23 into 19

---

bin/settlement-submit/main.go
cmd/settlement/gemini.go
utils/context/keys.go
utils/logging/logging.go

fixes: #471 - Improved logging throughout the settlement commands, removed logrus and fmt.Println
Improved logging for settlement tools.  Includes progress reporting, cleaned up logging and improved verbose logging.

Verbose/Progress Logging Settlement Tooling

---

cmd/rewards/rest_run.go
cmd/root.go

Release 2020-10-15 #1

---

datastore/grantserver/postgres.go

check the version and if dirty prior to attempting a migration

Migrate only up

---

README.md
bin/grant-server/main.go
payment/service.go

using logger passed in instead of default logger on server startup, and in payments init
Improves Grant logging in startup, consistent logger.
Make sure that the log lines are consistent on server startup.

Small Logging Corrections

---

cmd/settlement/paypal.go

flag was attached to wrong command. prevented command from running

fixed flag attachment

---

payment/controllers_test.go

fixes: #328 - speed up the e2e sku vote test so it doesnt time out

isolating where e2e payments is taking so long

---

bin/settlement-submit/main.go
cmd/README.md
cmd/root.go
cmd/settlement/gemini.go
go.mod
go.sum
grant/mockdatastore.go
payment/instrumented_datastore.go
settlement/README.md
utils/clients/client.go
utils/clients/errors.go
utils/clients/gemini/client.go
utils/clients/gemini/client_test.go
utils/clients/gemini/instrumented_client.go

added gemini endpoint for checking individual transaction progress

Gemini settlement tweaks

---

cmd/vault/sign_settlement.go

only includes transactions with amounts greater than zero

added a skip for tx amounts not greater than 0

---

settlement/README.md

added envs in readme

---

promotion/controllers_test.go

looped until a status is marked as paid

---

Dockerfile
Makefile
cmd/serve/grant.go

Correcting the dockerfile syntax and adding the new grant cmd line flag for cobra.

Fix Dockerfile and New Grant Flag

---

Dockerfile
Makefile
cmd/serve/grant.go

updates to fix the dockerfile with correct cmd syntax, adding new flag for grants for cobra (#545)

Prod Release 2020-10-21_2

---

cmd/serve/grant.go
docker-compose.dev-refresh.yml
promotion/datastore.go
wallet/service.go

fixing dev-refresh to use new cmd structure, updating promotions to fallback to datastore if no readonly datastore

Cleanup for Local Development (cmd changes)

---

.dependabot/config.yml

added dependabot config. not much in terms of docs: https://dependabot.com/go/
fixes #512

added dependabot

---

go.mod
go.sum
payment/controllers_test.go
payment/instrumented_datastore.go
promotion/claim.go
promotion/controllers.go
promotion/controllers_test.go
promotion/datastore_test.go
promotion/drain.go
promotion/promotion.go
rewards/controllers.go
wallet/controllers.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/datastore.go
wallet/datastore_test.go
wallet/instrumented_datastore.go
wallet/instrumented_read_only_datastore.go
wallet/service.go

Utilize Context in DB Calls

---

wallet/controllers_v3.go
wallet/service.go

Fixes a merge related issue with wallet context in calls to datastore.

fix up context in datastore calls

---

cmd/serve.go
cmd/serve/grant.go
middleware/rate_limiter.go
wallet/service.go

Adds rate limit of 2 wallet creations per IP per minute.

rate limit 2 per minute wallet creations

---

README.md
cmd/serve/grant.go
promotion/datastore.go
promotion/drain.go
wallet/service.go

Allows for UGP draining from iOS promotion to another brave wallet.

UGP Drain for IOS

---

cmd/serve/grant.go
payment/controllers.go

Endpoint for bulk verification of an order's signed credentials, should return error status code if CBP throws one, otherwise return 201 successful

Verify order credentials endpoint 

---

.github/dependabot.yml

updated package ecosystem

---

cmd/serve/grant.go
payment/controllers.go

Places /subscription/verifications behind a feature flag until sec. reviewed

Put subscription verification endpoint behind a feature flag

---

cmd/serve/grant.go
utils/clients/reputation/client.go
utils/context/keys.go

Checks for wallet on a platform in the reputation client.

check attestations happened priorTo in reputation client

---

cmd/serve/grant.go
promotion/controllers_test.go
promotion/datastore.go
promotion/datastore_test.go
promotion/drain.go
promotion/instrumented_datastore.go

Corrects the promotion ids env var for transfers.

Promotion Draining Bugfixes

---

cmd/settlement/uphold.go
cmd/wallets/list_transactions.go

define verbose flags so that the binary doesn't err

fixed verbose flag definitions

---

.github/dependabot.yml
Makefile
cmd/README.md
cmd/generate.go
cmd/rewards/rewards.go
cmd/root.go
cmd/serve.go
cmd/settlement/gemini.go
cmd/settlement/paypal.go
cmd/vault/create_wallet.go
cmd/vault/vault.go

localized flag, used utils

---

Makefile

Bit of cleanup for the settlement tooling build, remove old target - include version info.

remove settlement-submit from Makefile, add version info

---

go.mod
go.sum
payment/controllers.go

Allowing CORS requests on non-production environments to unblock dev on Brave Together

Allow CORS on Sandbox

---

settlement/gemini/sign.go
utils/clients/gemini/client.go

we should not be able create a payload for gemini without the client id. this disallows that situation

added panic for missing param

---

wallet/service.go

provider linking id should match what is in the from wallet, not to wallet in brave case

Provider Linking ID on From Wallet

---

wallet/controllers_v3_test.go
wallet/service.go

Small typo in the wallet linking code that was overlooked.

Bugfix - Brave Wallet Linking Check

---

wallet/controllers_v3_test.go
wallet/service.go

* typo corrected
* correcting bad assumption in test
Bugfix - Brave Wallet Linking Check (#598)

Prod 2020-13-04_2

---

wallet/controllers_v3.go
wallet/controllers_v3_test.go

Disable Brave Wallet Linking Temporarily

---

wallet/controllers_v3.go
wallet/controllers_v3_test.go

PROD 2020-12-07_1

---

cmd/serve/grant.go

Resolve CORS for https://together.bsg.brave.software/

---

cmd/serve.go
cmd/serve/grant.go

Short circuit ratelimiter on dev server 

---

wallet/controllers_v3.go
wallet/controllers_v3_test.go

undoing the 500 on v3 wallet linking

---

wallet/controllers_v3.go
wallet/controllers_v3_test.go

Production 2020-12-16_2

---

promotion/controllers_test.go
promotion/datastore.go

Cleaning up datastore SetMintDrainPromotionTotal

no need to have a tx for one statement

---

promotion/controllers_test.go
promotion/datastore.go

Prod Release 2020-12-17_1

---

promotion/drain.go

removal of specific mint drain call from http handler.

Issue with Cancellation of Context

---

promotion/drain.go

Prod Release 2020-12-17_2

---

promotion/drain.go
promotion/service.go

Increases the number of mint drain workers, decreases time between runs, and runs the mint drain job after submission of claim draining.

updated mint drain worker count and run jobs after submission

---

promotion/drain.go
promotion/service.go

Production Release 2020-12-19_1

---

promotion/controllers_test.go
promotion/datastore.go

Grant summary should not be calculated with any brave transfer promotions.

Exclude brave transfer promos summary

---

promotion/controllers_test.go
promotion/datastore.go

Production Release 2 - updates to grants claim summary endpoint to not show brave transfer promotions.

Production Release 2020-12-19_2

---

promotion/service.go

increse the mint-drain-workers

---

promotion/service.go

Production 2020-12-22_1

---

promotion/datastore.go

correct mint_drain_promotion update query.

update to use the correct mint_drain database table attribute

---

promotion/datastore.go

update to use the correct mint_drain database table attribute (#638)

---

wallet/datastore.go

Bugfix for re-linking attempts.

Relinking Bugfix

---

payment/controllers.go

fix json property to match with sdk

---

payment/datastore.go

errors occur when summing is null, i.e. when no transactions are complete

Transaction Sum Bugfix

---

go.mod
go.sum
payment/datastore.go
utils/altcurrency/altcurrency.go

Production 2021-01-05_1

---

utils/context/getters.go
utils/context/keys.go
utils/logging/logging.go

This adds the ability for callers to specify the default log level either through the context or through a new function signature.

adding ability to specify the default log level for the application

---

cmd/wallets/wallets.go
go.mod
go.sum
utils/context/keys.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go
wallet/inputs.go
wallet/service.go

Adds in user wallet linking for bitflyer integration.

user wallet linking for bitflier

---

docker-compose.dev-refresh.yml
docker-compose.yml
go.sum
rewards/docker-compose.yml
utils/context/getters.go
wallet/controllers_v3_test.go
wallet/inputs.go
wallet/service.go

handle decoding of the hex secret.

Bitflyer user wallet 1

---

docker-compose.dev-refresh.yml
docker-compose.yml
go.sum
rewards/docker-compose.yml
utils/context/getters.go
wallet/controllers_v3_test.go
wallet/inputs.go
wallet/service.go

* updates to correct the bitflyer linking info jwt key format
* fixing tests, pointing at new ratios service

Bitflyer user wallet 1 (#661)

---

settlement/bitflyer/upload_mock_test.go
utils/clients/bitflyer/client.go

adds mocks to round out testing logic

bitflyer mock tests

---

Makefile

added count to force tests to run

---

cmd/settlement/bitflyer.go
cmd/vault/import_key.go
settlement/bitflyer/upload.go
settlement/bitflyer/upload_test.go
utils/clients/bitflyer/client.go

Updated client float check

---

datastore/grantserver/postgres.go
middleware/http_signed.go
migrations/0025_bap_report.down.sql
migrations/0025_bap_report.up.sql
promotion/controllers.go
promotion/controllers_test.go
promotion/datastore.go
promotion/instrumented_datastore.go
utils/errors/errors.go

Provides a mechanism for self reporting of total BAP contained in browser.

BAP Reporting Endpoint

---

wallet/controllers_v3.go
wallet/controllers_v3_test.go

Adding some more id validation to linking handlers.

fixing some id validation in wallet linking

---

cmd/vault/import_key.go
datastore/grantserver/postgres.go
go.mod
go.sum
middleware/http_signed.go
migrations/0025_bap_report.down.sql
migrations/0025_bap_report.up.sql
promotion/controllers.go
promotion/controllers_test.go
promotion/datastore.go
promotion/instrumented_datastore.go
settlement/bitflyer/upload.go
settlement/bitflyer/upload_test.go
utils/clients/bitflyer/client.go
utils/errors/errors.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go

Changes include a BAP self reporting endpoint.

Production 2021-02-19_0

---

promotion/claim.go
promotion/promotion.go
promotion/promotion_test.go

* pushed ads expiration back and allowed legacy claimed to continue claiming
* added promotion methods and test

Prod Release 2021-02-22_0

---

promotion/service.go

put bitflyer behind a feature flag

Added bf flag

---

promotion/service.go

* added flag
* moved token fetch within flag

Production 2021-02-23_0

---

promotion/datastore.go

corrects a db data type to allow for scanning nil values.

hotfix to fix the datatype for BatchID to accomodate nil values

---

promotion/datastore.go

Hotfix for batch id scanning bug.

Production 2021-02-24_1

---

datastore/grantserver/postgres.go
migrations/0026_claim_drain_audit.down.sql
migrations/0026_claim_drain_audit.up.sql
promotion/claim.go
promotion/datastore.go

fixes #652 - Adding timestamps for more metadata around draining, linking drains to claims

Claim Drain to Claim Linkage and Timestamps

---

.github/workflows/golangci-lint.yml
promotion/datastore.go
utils/clients/bitflyer/client.go
utils/kafka/dialer.go

allows better visibility into bf specific error codes

better error handling of bf responses

---

cmd/serve/grant.go

checks the error from an http response failure

check response during job failure

---

wallet/inputs.go

Added validation on linking information token.

validating the token is less than 2 minutes old

---

datastore/grantserver/postgres.go
migrations/0027_bf_req_id.down.sql
migrations/0027_bf_req_id.up.sql
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/inputs.go
wallet/instrumented_datastore.go

adding a check for external account id, adding check for only one use per request_id

More Validations on Linking Info token

---

datastore/grantserver/postgres.go
migrations/0027_bf_req_id.down.sql
migrations/0027_bf_req_id.up.sql
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/inputs.go
wallet/instrumented_datastore.go

More Validations on Linking Info token (#714)
* adding a check for external account id, adding check for only one use per request_id
* fixing tests to prove the new validation
* add created_at with current timestamp to know when request id was inserted

Production 2021-03-12_1

---

wallet/inputs.go

update to check the lower case version of external_account_id for validation

BF External Account ID validation

---

wallet/inputs.go

update to check the lower case version of external_account_id for validation (#717)

prod 2021-03-15_1

---

wallet/datastore.go

added debugging to bf-request-id insertions

Additional Debugging

---

wallet/datastore.go

added debugging to bf-request-id insertions (#719)

prod 2020-03-15_2

---

wallet/datastore.go

hotfix for typo in req id insertions

Hotfix for bf-request-id insertion

---

wallet/datastore.go

hotfix for typo in req id insertions (#721)

prod 2021-03-15_3

---

promotion/controllers_test.go
promotion/drain.go

Check the userdrain send limit for bitflyer.

checking send limits for bf

---

promotion/controllers_test.go
promotion/drain.go

checking send limits for bf (#727)

prod 2021-03-17_1

---

grant/service.go

does not return during metrics collection for grant check

does not block if balance check fails

---

datastore/grantserver/postgres.go
migrations/0028_linking_adjust.down.sql
migrations/0028_linking_adjust.up.sql
utils/inputs/custodian.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/instrumented_datastore.go
wallet/service.go

fixes: #709 
adding linking info apis to give more visibility into limits therein

Linking Limit Info Custodial Accounts

---

wallet/controllers_v3.go

Error handling when wallet does not exist.

check for empty wallet/provider linking id in paymentId provided case

---

promotion/drain.go

correct bf user drain error coding, if error is no inv report to sentry

Alert on BF No INV Error

---

promotion/controllers_test.go
promotion/datastore.go
promotion/datastore_test.go
promotion/drain.go

adding a test to try out no_inv, adding logging, correcting bfe err codification

Adding Test for BF NO_INV

---

go.mod
promotion/controllers_test.go
promotion/datastore.go
promotion/datastore_test.go
promotion/drain.go

Fixes dependencies.  Fixes Error Handling of BF codified errors.  Alerts in sentry when NO_INV error is recieved.

production 2021-03-24_1

---

datastore/grantserver/postgres.go
migrations/0029_claim_drain_job_status.down.sql
migrations/0029_claim_drain_job_status.up.sql
promotion/controllers_test.go
promotion/datastore.go
promotion/drain.go
promotion/mockdrain.go
utils/clients/reputation/client.go
utils/clients/reputation/instrumented_client.go
utils/clients/reputation/mock/mock.go

Check wallet reputation prior to draining.

reputation check on user drain for wallets

---

datastore/grantserver/postgres.go
migrations/0029_claim_drain_job_status.down.sql
migrations/0029_claim_drain_job_status.up.sql
promotion/controllers_test.go
promotion/datastore.go
promotion/drain.go
promotion/mockdrain.go
utils/clients/reputation/client.go
utils/clients/reputation/instrumented_client.go
utils/clients/reputation/mock/mock.go

https://github.com/brave-intl/bat-go/pull/747

production 2021-03-31_1

---

cmd/serve/grant.go
promotion/controllers_test.go
promotion/drain.go
utils/context/getters.go
utils/context/keys.go

feature flag for reputation check on user drain

Feature Flag User Drain Reputation Check

---

cmd/serve/grant.go
promotion/controllers_test.go
promotion/drain.go
utils/context/getters.go
utils/context/keys.go

feature flag for reputation check on user drain (#749)

production deploy 2021-04-01

---

datastore/grantserver/postgres.go
migrations/0030_suggestion_timestamp.down.sql
migrations/0030_suggestion_timestamp.up.sql
promotion/controllers_test.go
promotion/datastore.go
promotion/datastore_test.go
promotion/suggestions.go
utils/clients/cbr/client.go
utils/errors/errors.go

better error codification for suggestion queue including better on failures.
fixes: #761 
fixes: #760

Suggestion Job Runner Improvements

---

datastore/grantserver/postgres.go
migrations/0031_mint_drain_idx.down.sql
migrations/0031_mint_drain_idx.up.sql

setting up indexes for mint_drain relations

Adding Indexes for Mint Drain/Mint Drain Promotion tables

---

payment/controllers_test.go
payment/credentials.go

add missing length check

---

payment/controllers_test.go
payment/credentials.go

Release: add missing length check (#766)

---

settlement/gemini/sign.go

takes a unique address for the item in the loop

fixed gemini request loop

---

cmd/serve.go
cmd/serve/grant.go

Removes access to metrics endpoint.

remove old metrics endpoint

---

payment/controllers.go
payment/controllers_test.go

add missing validators for skus credential verify request, also sets `SetFieldsRequiredByDefault` in payment service controller integration test suite to ensure tests will fail if there are missing validators.

add missing validators for skus credential verify request

---

payment/controllers.go
payment/controllers_test.go

prod release: add missing validators for skus credential verify request see #775

prod release: add missing validators for skus credential verify request (#775)

---

promotion/drain.go
promotion/service.go
utils/clients/gemini/client.go
wallet/controllers_v3.go
wallet/inputs.go

Gemini Updates based on Review

---

promotion/claim.go
promotion/controllers_test.go
promotion/promotion.go
promotion/promotion_test.go

Legacy Claimable attribute is not on promotions, we should be checking on the particular claim instead.

legacy claimed fix for promotion claimability

---

promotion/claim.go
promotion/controllers_test.go
promotion/promotion.go
promotion/promotion_test.go

production 2021-05-03
legacy claimed fix for promotion claimability (#784)

production 2021-05-03

---

wallet/service.go

Gemini Client was not being added to the context after initialization.

adding gemini client to context

---

wallet/service.go

adding gemini client to context (#786)

production 2021-05-03_1

---

middleware/prometheus.go

Duplicate Instrumented Client Metric Registration (#788)

production 2021-05-03_2

---

utils/clients/bitflyer/client.go
utils/clients/cbr/client.go
utils/clients/client.go
utils/clients/gemini/client.go
utils/clients/ratios/client.go
utils/clients/reputation/client.go

creating a query query string interface type for anything that can be converted to a client qs

Client Request "body" Query String Type

---

utils/clients/bitflyer/client.go
utils/clients/cbr/client.go
utils/clients/client.go
utils/clients/gemini/client.go
utils/clients/ratios/client.go
utils/clients/reputation/client.go

Client Request "body" Query String Type (#790)

production 2021-05-04_1

---

wallet/controllers_v3.go
wallet/controllers_v3_test.go
wallet/inputs.go
wallet/service.go

Stub for disconnect verified wallet.
Disconnect Custodial Wallet API Stub (#792)

production 2021-05-06

---

promotion/controllers_test.go
promotion/datastore.go
promotion/drain.go
promotion/suggestions.go
utils/context/keys.go

* adding a flag to skip credential redemption step of suggestion/claim jobs triggered by errcode of failed jobs
* updates based on feedback

Skip Credential Redeem (#796)

---

promotion/drain.go

bitflyer transfer limit codification of error for drain job

bitflyer limit error codification

---

promotion/controllers_test.go
promotion/datastore.go
promotion/drain.go
utils/wallet/provider/uphold/errors.go
utils/wallet/provider/uphold/uphold.go

Various Drain Code fixes:
- bitflyer limit error codification (#800)
- uphold codification (#801)

production 2021-05-11_1

---

promotion/drain.go
utils/clients/bitflyer/client.go

Add Token to FetchPrice BF API

---

promotion/drain.go
utils/clients/bitflyer/client.go

fetch bf price requires token (#803)

Production 2021-05-12_0

---

promotion/drain.go
settlement/bitflyer/upload_mock_test.go
settlement/bitflyer/upload_test.go
utils/clients/bitflyer/client.go
utils/clients/bitflyer/client_test.go
utils/clients/errors.go

the bitflyer error's status was not what it seems, this adds the http protocol status code to the error

Bitflyer HTTP Status Code to Error

---

promotion/drain.go
settlement/bitflyer/upload_mock_test.go
settlement/bitflyer/upload_test.go
utils/clients/bitflyer/client.go
utils/clients/bitflyer/client_test.go
utils/clients/errors.go

* the bitflyer error's status was not what it seems, this adds the http protocol status code to the error
* adding error text for http status code
* adding test for checking http status code from handlebitflyererror
* fixing tests for bferror
* require that the error is a bitflyer error
Bitflyer HTTP Status Code to Error (#806)

production 2021-05-13_0

---

promotion/controllers.go
promotion/drain.go

Adds more logging to the claim drain flow.

Claim Drain Logging Improvements

---

promotion/controllers.go
promotion/drain.go

adding more logging into the claim drain flow (#812)

production 2021-05-19_0

---

payment/service.go

fixes worker running logic for order.

fixing logic for order worker jobs

---

payment/service.go

fixing logic for order worker jobs (#817)

production 2021-05-25_0

---

go.mod
go.sum

updated deps

---

cmd/serve/grant.go

adding new v3 captcha proxy

---

go.mod
go.sum

Update dependencies - fixes: #825 #826

Update more dependencies

---

datastore/grantserver/postgres.go
migrations/0034_multi_custodian_wallet.down.sql
migrations/0034_multi_custodian_wallet.up.sql
promotion/datastore.go
utils/context/keys.go
utils/errors/errors.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/datastore_test.go
wallet/instrumented_datastore.go
wallet/instrumented_read_only_datastore.go
wallet/service.go

production 2021-06-09

---

payment/controllers.go
payment/controllers_test.go
payment/service.go
utils/context/keys.go

Adds Gemini related transaction checking to the orders/skus APIs.  This is to support AC with Gemini.

Gemini AC SKUs Order API

---

cmd/serve/grant.go
utils/clients/gemini/client.go

adding gemini config to entrypoint, correcting client payments url

Gemini Config for Payments Service

---

payment/controllers.go
utils/handlers/handlers.go

Adds debugging and logging to stripe webhook handler.

Stripe Webhook debug and logging

---

datastore/grantserver/postgres.go

setting db max idle connections to 50% the max open conns

Datastore Max Idle Conns

---

datastore/grantserver/postgres.go
payment/controllers.go
utils/handlers/handlers.go

Stripe Webhook debug and logging (#854)
Datastore Max Idle Conns (#855)

production 2021-07-06_1

---

cmd/serve/grant.go
utils/clients/gemini/client.go
utils/context/keys.go

adding gemini signer to checktx method call

Gemini Client CheckTx Signature Requirement

---

cmd/serve/grant.go
utils/clients/gemini/client.go
utils/context/keys.go

Gemini Client CheckTx Signature Requirement (#857)

Gemini Client CheckTx Signature Requirement (#857)

---

wallet/controllers_v3_test.go
wallet/datastore.go
wallet/instrumented_datastore.go
wallet/service.go

changes to allow for multiple custodian linking details

Multi-Custodian Linking Info

---

utils/clients/gemini/client.go

correcting api endpoint for gemini get tx status

Correcting Gemini API Endpoint Location

---

utils/clients/gemini/client.go
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/instrumented_datastore.go
wallet/service.go

Multi-Custodian Linking Info (#841)

production 2021-07-08_1

---

wallet/controllers_v3_test.go
wallet/datastore.go
wallet/service.go

correctly checking error is TooManyCards

Correcting Error Code for Too Many Wallets Linked

---

wallet/controllers_v3_test.go
wallet/datastore.go
wallet/service.go

Correcting Error Code for Too Many Wallets Linked (#860)

production 2021-07-09

---

wallet/controllers_v3_test.go
wallet/datastore.go

check linking limit only if the user wallet has not been linked before

Wallet Linking Limit Check If Not Prior Linked

---

wallet/controllers_v3_test.go
wallet/datastore.go

* check linking limit only if the user wallet has not been linked before
* change in code branching required mock tests to be updated

production 2021-07-09-1

---

promotion/datastore.go
promotion/datastore_test.go
promotion/promotion.go

tweak the query used to get available promotions for a wallet

---

promotion/datastore.go
promotion/datastore_test.go
promotion/promotion.go

tweak the query used to get available promotions for a wallet (#865)

production 2021-07-12-1

---

payment/order.go

see https://stripe.com/docs/billing/subscriptions/discounts/codes#adding-promotion-codes-to-checkout

add promo code flag to stripe checkout

---

payment/order.go
wallet/datastore.go

will not 500 if a wallet attempts an unlink when not in linked state.

production 2021-07-19_1

---

utils/clients/gemini/client.go
utils/clients/gemini/instrumented_client.go
utils/clients/gemini/mock/mock.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go
wallet/inputs.go
wallet/service.go

Pull deposit id from the request on claiming

Gemini Deposit Destination

---

utils/clients/gemini/client.go
utils/clients/gemini/instrumented_client.go
utils/clients/gemini/mock/mock.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go
wallet/inputs.go
wallet/service.go

Gemini Deposit Destination (#871)

production 2021-07-19_2

---

utils/clients/gemini/client.go

correcting http method  to match specification for gemini client check tx

Gemini Client Method Bugfix

---

utils/clients/gemini/client.go

correcting to match specification (#873)

production 2021-07-21_1

---

utils/clients/client.go

fix debug logging to include the full http request

Use httputil dumprequestout to dump full debugging

---

utils/clients/client.go

fixes logging of headers, and redacts certain headers.

fixing header redaction

---

wallet/controllers_v3_test.go
wallet/inputs.go

changing linking param attribute name for linking gemini

changing linking param attribute name for linking gemini

---

utils/clients/client.go
wallet/controllers_v3_test.go
wallet/inputs.go

fixing header redaction (#878)

production 2021-07-21_3

---

utils/clients/gemini/client.go

Corrects gemini signature header.  gemini payload needs to be base64 prior to signature

Gemini Signature Header Correction

---

utils/clients/gemini/client.go

gemini payload needs to be base64 prior to signature (#883)

production 2021-07-26_1

---

payment/service.go

lowercase status from gemini for transaction table updates

Lowercase Gemini Status Value 

---

payment/service.go

lowercase status from gemini for transaction table updates (#885)

productio 2021-07-27_1

---

promotion/drain.go
promotion/service.go

correct the configuration for user drain gemini, no longer double b64 encode gemini payload

Correct Userdrain Gemini Conf

---

promotion/drain.go
promotion/service.go

correct the configuration for user drain gemini, no longer double b64… encode gemini payload (#887)

production 2021-07-27_2

---

promotion/drain.go

random tx 'settlement' id for gemini user drain

Userdrain TX ID Gemini

---

promotion/drain.go

production 2021-07-28_1

---

wallet/outputs.go

Corrects the get wallet endpoint to send back the card identifier (used to be provider_id)

Correct Get Wallet Endpoint Result

---

wallet/outputs.go

wrong value for result of wallet get (#895)

production 2021-07-30_1

---

datastore/grantserver/postgres.go
migrations/0036_order_time.down.sql
migrations/0036_order_time.up.sql
payment/controllers.go
payment/datastore.go
payment/instrumented_datastore.go
payment/order.go
payment/service.go
promotion/order.go

adding expires_at on order, and handle renewals from stripe webhook

Stripe Renewals and Expires At

---

datastore/grantserver/postgres.go
migrations/0036_order_time.down.sql
migrations/0036_order_time.up.sql
payment/controllers.go
payment/datastore.go
payment/instrumented_datastore.go
payment/order.go
payment/service.go
promotion/order.go

Stripe Renewals and Expires At (#894)

production 2021-07-30_2

---

payment/controllers_test.go
payment/service.go

One credential per day for the duration of "valid for" based on the sku.

1 per day time limited creds

---

middleware/http_signed.go
middleware/http_signed_test.go
promotion/controllers_test.go
utils/httpsignature/algorithm.go
utils/httpsignature/hmac.go
utils/httpsignature/hs2019.go
utils/httpsignature/httpsignature.go
utils/httpsignature/httpsignature_test.go
utils/wallet/provider/uphold/httpsigned.go
utils/wallet/provider/uphold/uphold.go
wallet/controllers.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go

**NOTE** PR description + base copied from: https://github.com/brave-intl/bat-go/pull/890
Added fully HS2019 (HMAC-SHA512) support to the `httpsigning` package
I have added tests and verified that the tests work
I have tried to add comments on the code that I changed
Meant to be reviewed by @evq based on private discussions in Slack

hmac-sha512 support added to httpsignature

---

payment/controllers.go

since issuerID will automatically be "checked" in the hmac derivation, there's no need to have an inner copy. this brings the skus sdk and skus service into parity

drop extra issuer and just derive from merchant and sku

---

payment/service.go

logging error conditions for transactions

---

payment/service.go

logging error conditions for transactions (#909)

production 2021-08-10_1

---

payment/controllers.go
payment/order.go

webhook check invoice updated/paid for stripe purchase.

webhook check invoice updated/paid

---

payment/controllers.go
payment/order.go

webhook check invoice updated/paid (#911)

production 2021-08-10_2

---

payment/order.go
promotion/order.go

fixing json on order structure to be consistent

Order JSON changes

---

payment/controllers_test.go
payment/order.go
payment/service.go
promotion/order.go

fixing time structure in json response for orders

No NullTime on Order Response

---

payment/order.go

order should be paid if status is canceled and order expires at is in future

Canceled Still Paid prior to Expiry

---

payment/datastore.go

Orders Last Paid At

---

payment/datastore.go

bugfix column is last_paid_at (#923)

production 2021-08-16_1

---

promotion/drain.go
utils/clients/client.go

detailed gemini drain error logging

Detailed Gemini Drain Logging

---

promotion/drain.go
utils/clients/client.go

removes request header from error bundle data.

More gemini drain log detail

---

promotion/drain.go
utils/clients/client.go

detailed gemini drain error logging (#927)

production 20021-08-24_1

---

payment/controllers_test.go
promotion/drain.go

checking 'result' in gemini bulkPay for OK in userdrain

Gemini Result Userdrain Status

---

payment/controllers_test.go
promotion/drain.go

Gemini Result Userdrain Status (#930)

production 2021-08-31_1

---

cmd/serve/grant.go
middleware/rate_limiter.go
utils/context/keys.go

updating rate limiter to allow bursting

Rate Limit Bursting

---

cmd/serve/grant.go
middleware/rate_limiter.go
utils/context/keys.go

updating rate limiter to allow bursting (#933)

production 2021-09-02_1

---

datastore/grantserver/postgres.go
migrations/0037_order_item_valid_for.down.sql
migrations/0037_order_item_valid_for.up.sql
payment/controllers_test.go
payment/datastore.go
payment/order.go
payment/service.go
promotion/order.go
utils/time/duration.go
utils/time/duration_test.go

correcting valid-for to match subscription in stripe, adding additional day of creds as last day is truncated

Correcting ValidFor Logic Credentials

---

payment/controllers_test.go
payment/order.go
payment/service.go
utils/time/duration.go
utils/time/duration_test.go

a better iso duration utility, not based solely on time.Now

Handle ISO Durations

---

datastore/grantserver/postgres.go
migrations/0038_deposit_dest_drain.down.sql
migrations/0038_deposit_dest_drain.up.sql
payment/controllers_test.go
payment/service.go
promotion/datastore.go

adding the deposit destination to the claim_drain to know where drained to for user support

Record the Deposit Destination for Claim Drain

---

middleware/http_signed.go

include error information about why the http signature failed to validate in our error response

include error information from http signature

---

cmd/wallets/transfer_funds.go

Fix transfer funds

---

datastore/grantserver/postgres.go
middleware/http_signed.go
migrations/0039_free_trial_order.down.sql
migrations/0039_free_trial_order.up.sql
payment/controllers.go
payment/controllers_test.go
payment/datastore.go
payment/instrumented_datastore.go
payment/order.go
payment/service.go
promotion/controllers_test.go
promotion/order.go

updates a free trial for talk.brave.com in stripe checkout session

Stripe Free Trial on Subscription

---

cmd/serve/grant.go
middleware/request_host.go
utils/httpsignature/httpsignature.go
utils/requestutils/requestutils.go

adding httpsignature host support when proxy

Proxy HttpSig Host Support

---

cmd/serve/grant.go
cmd/wallets/transfer_funds.go
datastore/grantserver/postgres.go
middleware/http_signed.go
middleware/request_host.go
migrations/0038_deposit_dest_drain.down.sql
migrations/0038_deposit_dest_drain.up.sql
migrations/0039_free_trial_order.down.sql
migrations/0039_free_trial_order.up.sql
payment/controllers.go
payment/controllers_test.go
payment/datastore.go
payment/instrumented_datastore.go
payment/order.go
payment/service.go
promotion/controllers_test.go
promotion/datastore.go
promotion/order.go
utils/requestutils/requestutils.go

production 2021-09-30_1

---

payment/order.go
payment/service.go

Set trial functionality was not using the correct email field from the checkout session.

Set Trial to re-use existing Customer in Stripe

---

payment/order.go

Set Trial to re-use existing Customer in Stripe (#956)

production 2021-10-04_1

---

promotion/datastore.go
promotion/datastore_test.go
promotion/drain.go
promotion/instrumented_datastore.go

moving error processing async for claim draining
fixes: #958

Error Processing for Mismatched Wallets

---

cmd/serve/grant.go
utils/clients/gemini/client.go

no need to panic if we can't get wallet balance for gemini

---

cmd/macaroon/brave-search/production-captcha-single-use.yaml
cmd/macaroon/brave-search/staging-captcha-single-use.yaml

adding prod and stg captcha sku meta

search captcha skus

---

cmd/serve/grant.go
payment/controllers_test.go
utils/wallet/provider/uphold/uphold_test.go

init keys regardless of merchant feature

init keys regardless of merchant feature

---

payment/service.go
utils/clients/cbr/client.go

if we have a bad request or conflict from CBR we need to propogate that as invalid credentials in payments

Correct Response Code Single-Use Credentials Payments

---

cmd/vault/init.go
middleware/http_signed.go
middleware/http_signed_test.go
payment/service.go
utils/clients/cbr/client.go
utils/clients/ratios/client_test.go

production 2021-11-08_1

---

wallet/datastore.go
wallet/service.go

more wallet linking error message improvements (#1015)

production 2021-11-09_1

---

utils/clients/gemini/client.go
wallet/datastore.go
wallet/service.go

Recover in the event there is a timeout to fetch balance

Recover in the event there is a timeout to fetch balance

---

utils/clients/gemini/client.go

more wallet linking error message improvements

production 2021-11-09_02

---

payment/datastore.go

updates to check for an expired checkout session

Handle Null CheckoutSession on GetOrder

---

utils/clients/ratios/client_test.go
wallet/controllers_test.go
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/datastore_test.go
wallet/instrumented_datastore.go
wallet/instrumented_read_only_datastore.go
wallet/service.go

adding metadata about the other linked wallets (datetimes/active/etc)
fixes: #995
fixes: #994
fixes: #996

Linking Support

---

utils/closers/panic.go

adding error logging and checking for nil param

Logging Around Panic Closer

---

payment/datastore.go
utils/closers/panic.go
wallet/controllers_test.go
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/datastore_test.go
wallet/instrumented_datastore.go
wallet/instrumented_read_only_datastore.go
wallet/service.go

https://github.com/brave-intl/bat-go/pull/1019
https://github.com/brave-intl/bat-go/pull/1007
https://github.com/brave-intl/bat-go/pull/1020

production 2021-11-11_1

---

payment/datastore.go
utils/closers/panic.go

update go, and ignore context cancelled errors on body close (#1022)

production 2021-11-12_1

---

utils/closers/panic.go

the error from close is similar to context canceled

the error from close is similar to context canceled

---

utils/closers/panic.go

the error from close is similar to context canceled (#1024)

---

utils/clients/bitflyer/client.go

if the closer panics the service will not start

bF client panic halts service

---

utils/clients/client.go

redact signatures for http clients in debug logs

redact signatures for http clients in debug logs

---

datastore/grantserver/postgres.go
migrations/0042_normalize_creds.down.sql
migrations/0042_normalize_creds.up.sql

create a normalized view of credentials in claim_drain

create a normalized view of credentials in claim_drain

---

utils/clients/client.go

add new cancelation to context used in client requests

Context Canceled Prematurely

---

utils/clients/client.go

only dump request/response if debug is set

dump client request/response if debug 

---

utils/clients/client.go

add new cancelation to context used in client requests (#1035)

production 2021-11-30_1

---

go.mod
go.sum

updates for dependabot

---

.gitignore
payment/order_test.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/datastore_test.go
wallet/service.go

Add locking to prevent  wallet custodian link unique exception

Investigate wallet custodian link unique exception

---

promotion/drain.go

return batch id when we insert erred claim drain due to mismatched wallet

Batch ID on Mismatched

---

promotion/controllers_test.go
promotion/datastore.go

Set updated_at on claim_drain upon insert

---

.gitignore
go.mod
go.sum
payment/order_test.go
promotion/controllers_test.go
promotion/datastore.go
promotion/drain.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/controllers_v3_test.go
wallet/datastore.go
wallet/datastore_test.go
wallet/service.go

production 2021-12-01

---

utils/clients/client.go

fixing connection based errors from simple http client

Check Response Client Error

---

utils/clients/client.go

fixing connection based errors from simple http client (#1042)

production 2021-12-02_1

---

promotion/service.go
promotion/service_test.go

added random topic for test
Implements claim drain retry worker that updates failed drain jobs to be retried

kafka consumer signalling drain retry

---

promotion/datastore.go
promotion/datastore_test.go
promotion/mockdrain.go

added check for no rows to account for nothing to process

Investigate job worker issue in dev environment

---

promotion/datastore.go
utils/clients/bitflyer/client.go
utils/clients/client.go

update to get appropriate error message to sentry

Correct Failed Drain Error Processing

---

promotion/datastore.go
promotion/service.go
utils/clients/bitflyer/client.go
utils/clients/client.go
utils/kafka/dialer.go

removed offset
feat(1010): kafka consumer signalling drain retry (#1057)

production 2021-12-16_1

---

promotion/suggestions.go

added check for nil values coming back from GetIssuerByPublicKey and GetPromotion

Investigate invalid memory address error suggestions

---

promotion/drain.go
promotion/suggestions.go

consolidates bf on transaction level.
nil pointer checks

production 2021-12-16_2

---

payment/key_test.go
promotion/avro.go
promotion/drain.go
promotion/service.go
utils/clients/client.go
utils/kafka/dialer.go

fixed linter

---

promotion/drain.go
utils/clients/client.go

use the batch id as idempotency key bf consolidation

bf tx consolidation tx id

---

payment/key_test.go
promotion/avro.go
promotion/drain.go
promotion/service.go
utils/clients/client.go
utils/kafka/dialer.go

production 2021-12-21_1

---

middleware/request_logger.go
middleware/request_logger_test.go

added stacktrace to request logger

promotion nil pointer fix

---

utils/wallet/provider/uphold/uphold.go

corrects conversion:  https://github.com/brave-intl/bat-go/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmaster

correcting the conversion of a string to int type

---

.github/workflows/generalized-deployments.yaml

adds the generalized deployments github action with an attempted hack to align it with the current bat-go branching and deployment strategy:
- both `dev` and `master` will push to one combined ECR repo
- `prod` will push to it's own ECR repo

add generalized deployments github action

---

.github/workflows/generalized-deployments.yaml

attempts to fix #1072, overriding `GITHUB_REF` didnt' work - so a new version of the action was released that looks for `GITHUB_REF_OVERRIDE`.

use new generalized deployments version and set override

---

cmd/vault/create_wallet.go
utils/clients/coingecko/client_test.go

adding the logger and setting debug mode for create-wallet vault command

---

ratios/service.go

replace redis Dial with DialURL

---

ratios/cache.go
utils/clients/coingecko/client.go
utils/closers/log.go

adding log closer, and using in ratios and coingecko client

Log Closer

---

ratios/mapping.go
ratios/service.go

fix ratios timeframe_change

---

cmd/vault/create_wallet.go
utils/wallet/provider/uphold/uphold.go

remove calls to uphold.New, is not supported for creating a wallet

---

utils/clients/client.go
utils/wallet/provider/uphold/uphold.go

Getting invalid token trying to upload uphold settlements

add support for uphold client credentials

---

ratios/mapping.go
ratios/service.go

adding a filter to remove any keys that were not requested

Remove Unrequested Currencies Relative response

---

cmd/vault/sign_settlement.go
settlement/settlement.go
settlement/settlement_test.go

ads settlement fixes: adsDirectDeposit txn type, txn parsing fixes

---

payment/controllers.go
payment/controllers_test.go
payment/service.go
ratios/controllers_test.go
utils/wallet/provider/uphold/uphold.go

attempt to recheck tx status for uphold incase it is processing

recheck uphold tx status

---

cmd/vault/sign_settlement.go

improvements to settlement tooling so we can drop hacky workarounds

add support for multiple input files, custom output dir, merging txns

---

utils/clients/gemini/client.go

check if payload in header is already base64

---

promotion/controllers.go
promotion/controllers_test.go
promotion/datastore.go
promotion/datastore_test.go
promotion/instrumented_datastore.go
promotion/mockdatastore.go
promotion/service_test.go
utils/errors/errors.go
utils/handlers/handlers.go

User support tool to toggle drain jobs for retry
https://github.com/brave/security/issues/703
https://github.com/brave-intl/bat-go/pull/1083

User support drain retry

---

cmd/settlement/uphold.go
cmd/vault/create_wallet.go
cmd/vault/sign_settlement.go
cmd/wallets/list_transactions.go
settlement/paypal/transform.go
settlement/settlement.go

- removes local debug / verbose flags since there is now a global flag
- fix duplicate payout check, it should apply to all settlements

unify debug and fix duplicate payout check

---

promotion/controllers.go

changed response to just write header

support tool user drain retry

---

cmd/serve/grant.go
utils/clients/gemini/client.go
utils/context/keys.go

checking response country code in validate
fixes: https://github.com/brave-intl/bat-go/issues/1117

Validation Gemini Improvements

---

README.md
payment/datastore.go

Added improved error messages order job

improve errors for order job

---

README.md
cmd/serve/grant.go
payment/datastore.go
promotion/controllers.go
utils/clients/gemini/client.go
utils/context/keys.go
utils/wallet/provider/uphold/errors.go

production 2022-01-03_1

---

utils/clients/gemini/client.go

added nil pointer check to gemini watch
fix #1125

fix watch gemini nil pointer

---

utils/clients/gemini/client.go

bug(#1125) fix watch gemini nil pointer (#1126) added nil pointer check

production 2022-01-18_1

---

cmd/settlement/uphold.go
cmd/vault/create_wallet.go
cmd/wallets/create.go
cmd/wallets/list_transactions.go
cmd/wallets/transfer_funds.go
grant/service.go
payment/controllers_test.go
payment/service.go
promotion/controllers_test.go
promotion/drain.go
settlement/settlement.go
settlement/settlement_test.go
utils/wallet/provider/uphold/uphold.go
utils/wallet/provider/uphold/uphold_test.go
utils/wallet/wallet.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/service.go

fix uphold debug request logging by bringing the uphold client more in line with our others.

rework uphold client so context is passed on most methods, in-line with others

---

grant/service.go

adding a logger to the base service ctx

adding a logger to the base service ctx

---

cmd/ratios/rest_run.go
ratios/controllers.go
ratios/mapping.go

override eth symbol mapping, add debug endpoint for mapping

---

cmd/ratios/rest_run.go
cmd/settlement/uphold.go
cmd/vault/create_wallet.go
cmd/wallets/create.go
cmd/wallets/list_transactions.go
cmd/wallets/transfer_funds.go
go.mod
go.sum
grant/service.go
payment/controllers_test.go
payment/service.go
promotion/controllers_test.go
promotion/datastore.go
promotion/drain.go
ratios/controllers.go
ratios/mapping.go
settlement/settlement.go
settlement/settlement_test.go
utils/wallet/provider/uphold/uphold.go
utils/wallet/provider/uphold/uphold_test.go
utils/wallet/wallet.go
wallet/controllers_test.go
wallet/controllers_v3.go
wallet/service.go

production 2022-01-24_1

---

datastore/grantserver/postgres.go
migrations/0043_normalize_claim_creds.down.sql
migrations/0043_normalize_claim_creds.up.sql
promotion/claim.go
promotion/datastore.go

add created_at, updated_at columns to claim creds

---

datastore/grantserver/postgres.go
migrations/0043_normalize_claim_creds.down.sql
migrations/0043_normalize_claim_creds.up.sql
promotion/claim.go
promotion/datastore.go

* add created_at, updated_at columns to claim creds
* bump schema version
* fix up migration sql syntax
* replace view name
* set update_at to a better date

add created_at, updated_at columns to claim creds (#1152)

---

promotion/drain.go

set the deposit id first, before checking exceeded limit, otherwise we have an empty deposit id

Hotfix BF limit exceeded bug

---

promotion/drain.go

production 2022-01-25_1

---

promotion/controllers_test.go
promotion/drain.go
promotion/drain_test.go
utils/clients/bitflyer/client.go

This PR fixes an issues where we were not returning the correct errcode from bitflyer
resolves #1154

bitflyer insufficient funds error

---

settlement/bitflyer/upload.go
settlement/bitflyer/upload_mock_test.go
settlement/bitflyer/upload_test.go
settlement/settlement.go
utils/clients/bitflyer/client.go

prepare request tests

---

cmd/vault/init.go
go.mod
go.sum

follow up from https://github.com/brave/security/issues/710

switch to hashicorp openpgp to align with vault

---

promotion/datastore.go

adds error handling for failed suggestion job
fixes #1142

failed to commit transaction

---

cmd/ratios/ratios.go
cmd/ratios/rest_run.go
cmd/serve.go
utils/context/keys.go

adding non-default rate limit

---

utils/errors/errors.go
utils/errors/errors_test.go

corrects the unwrapping behavior for multi-error

Fixing MultiError Unwrap

---

cmd/vault/sign_settlement.go
settlement/bitflyer/upload.go

introduce breakOutTransactions function

---

settlement/bitflyer/upload.go

removes `getSettlementGroup` which seems to be causing issues, it's not needed anymore as batching was added elsewhere

remove getSettlementGroup since Amir added batching elsewhere

---

cmd/serve/grant.go
utils/clients/bitflyer/client.go
utils/clients/bitflyer/instrumented_client.go
utils/clients/bitflyer/mock/mock.go

This PR adds a metric to help monitor the current balance of an associated account
resolves #1151

feat: get the inventory for bf and create metric to tell when we are low

---

payment/controllers.go
payment/controllers_test.go
payment/datastore.go
payment/instrumented_datastore.go
payment/service.go

handling a reposting of an external transaction id gracefully, and updating the status on re-submission

handle resubmission external transaction

---

utils/wallet/provider/uphold/uphold.go

flush out Uphold beneficiary struct more

---

cmd/settlement/bitflyer.go
cmd/vault/sign_settlement.go
settlement/bitflyer/upload.go
settlement/settlement.go
utils/clients/bitflyer/client.go
utils/clients/bitflyer/instrumented_client.go

move quoting and requesting to per batch

---

.github/workflows/generalized-deployments-reproducible.yaml
Makefile
go.mod
go.sum

fixes: #1183 - adding kaniko reproducable build to makefile

---

.github/workflows/generalized-deployments-reproducible.yaml

fixing github env to include reproducible var

---

promotion/datastore.go
promotion/drain.go
promotion/instrumented_datastore.go
promotion/mockdatastore.go

This PR resolves #1191 by adding a metric to count complete/failed claim drain status partitioned by custodian

feat: claim drain success error metric

---

.github/workflows/generalized-deployments-reproducible.yaml
Makefile
go.mod
go.sum
promotion/controllers_test.go
promotion/datastore.go
promotion/datastore_test.go
promotion/drain.go
promotion/drain_test.go
promotion/instrumented_datastore.go
promotion/mockdatastore.go

production 2022-02-04_1

---

ratios/controllers_test.go

use mock coingecko for integration tests in ratios service

use mock coingecko for integration tests in ratios service

---

promotion/datastore.go

feat: handle failed Gemini settlements

---

settlement/gemini/upload.go

add balance check before uploading

---

promotion/datastore.go
promotion/drain.go
promotion/mockdrain.go

production_2022_02_14_01

---

go.mod
go.sum
payment/controllers.go
payment/order.go
payment/service.go

move stripe checkout session checks to a transform order function

Check CheckoutSession on Order Get

---

utils/clients/gemini/client.go

adds metric to count country code validation

feat: add metric to count account validation by country code

---

go.mod
go.sum
payment/controllers.go
payment/order.go
payment/service.go
utils/clients/gemini/client.go

production 2022-02-14_2

---

promotion/drain.go
promotion/drain_test.go

resolves #1227  add logic to handle gemini not found transactions

feat: gemini check status not found

---

ratios/mapping.go

new cg coin mapping

---

ratios/mapping.go

adding explicit dai mapping (#1230)

production 2022-02-21_1

---

wallet/controllers_v3_test.go
wallet/datastore.go
wallet/service.go

adding check on linking for unusual activity

Unusual Activity Check

---

wallet/controllers_v3_test.go
wallet/datastore.go
wallet/service.go

Unusual Activity Check (#1238)

production 2022-02-28_1

---

cmd/serve/grant.go
promotion/datastore.go
promotion/datastore_test.go
promotion/drain.go
promotion/instrumented_datastore.go
promotion/instrumented_read_only_datastore.go
promotion/mockdatastore.go
promotion/mockdrain.go
utils/clients/reputation/client.go
utils/clients/reputation/instrumented_client.go
utils/clients/reputation/mock/mock.go
utils/context/keys.go

adding withdrawal limits

---

wallet/datastore.go
wallet/datastore_test.go
wallet/instrumented_datastore.go
wallet/instrumented_read_only_datastore.go

changes to seperate out linking limits for custodians

Custodian Independent Linking Limits.

---

datastore/grantserver/postgres.go
docker-compose.dev-refresh.yml
docker-compose.yml
migrations/0046_swap_rewards_kafka.down.sql
migrations/0046_swap_rewards_kafka.up.sql
promotion/avro.go
promotion/claim.go
promotion/controllers.go
promotion/controllers_test.go
promotion/datastore.go
promotion/instrumented_datastore.go
promotion/mockclaim.go
promotion/mockdatastore.go
promotion/mockservice.go
promotion/promotion.go
promotion/service.go
promotion/service_test.go
utils/kafka/dialer.go

Kafka consumer for swap-rewards project.
Information still needs to be fleshed-out.
Also thought that https://github.com/brave-intl/bat-go/blob/master/utils/kafka/dialer.go#L49 probably wasn't the default we want for everything.... I used a sentinel wallet that we could insert in a migration (I can throw that in 46 or we could do another approach).
Sorry for merging this into another branch.

Swap-rewards kafka consumer

---

wallet/datastore_test.go

fixing failed tests due to merge

fixing failed tests due to merge

---

cmd/settlement/gemini.go
utils/clients/gemini/client.go

gemini-404 from https://github.com/brave-intl/bat-go/pull/1137

gemini-404 from https://github.com/brave-intl/bat-go/pull/1137

---

cmd/serve/grant.go
cmd/settlement/gemini.go
promotion/datastore.go
promotion/datastore_test.go
promotion/drain.go
promotion/instrumented_datastore.go
promotion/instrumented_read_only_datastore.go
promotion/mockdatastore.go
promotion/mockdrain.go
utils/clients/gemini/client.go
utils/clients/reputation/client.go
utils/clients/reputation/instrumented_client.go
utils/clients/reputation/mock/mock.go
utils/context/keys.go
wallet/datastore.go
wallet/datastore_test.go
wallet/instrumented_datastore.go
wallet/instrumented_read_only_datastore.go

withdrawal limits
independent linking limits per custodian.

production 2022-03-01_1

---

promotion/datastore.go
promotion/datastore_test.go

fixes #1252 by adding check to only update successful transactions in the batch payment job

bug: investigate failed bitflyer drains

---

promotion/datastore.go

fixing query to get the claim by id instead of claim_id

fixing query to get the claim by id instead of claim_id

---

promotion/datastore.go

another sql issue with withdrawal limits

withdrawal limit hotfix

---

promotion/datastore.go

another sql issue with withdrawal limits (#1257)

production 2022-03-04-3

---

utils/clients/reputation/client.go

hotfix correct promotion id in client (#1259)

production 2022-03-04-4

---

go.mod
go.sum

production 2022-03-07-1

---

cmd/settlement/bitflyer.go
cmd/settlement/gemini.go
cmd/vault/sign_settlement.go
promotion/drain.go
promotion/service.go
settlement/bitflyer/upload.go
settlement/bitflyer/upload_mock_test.go
settlement/bitflyer/upload_test.go
settlement/settlement.go
settlement/settlement_test.go
utils/clients/bitflyer/client.go
utils/clients/bitflyer/instrumented_client.go
utils/clients/bitflyer/mock/mock.go
utils/clients/reputation/client.go
utils/clients/reputation/instrumented_client.go
utils/clients/reputation/mock/mock.go

use cohorts in withdrawal limit check

production 2022-03-07-2

---

utils/httpsignature/httpsignature.go

handle host header off the request's host, header is overwritten

HTTPSignature Host Correction

---

promotion/datastore.go

bonus is already part of approximate_value

remove bonus from withdrawal limit calc

---

promotion/datastore.go
utils/httpsignature/httpsignature.go

corrects host header issue in httpsignature
fixes approximate_value and bonus in withdrawal calc

production 2022-03-08-1

---

utils/httpsignature/httpsignature.go

host header might be in header map, if not use req.host for signing string

hotfix - httpsignature signing string host

---

promotion/drain.go
promotion/drain_test.go

added processing status for Gemini check status

feat: add new processing status for Gemini check status endpoint

---

middleware/http_signed_test.go

alter e2e test for http signature including the request Host value

Verify Host in HTTPSignature

---

cmd/settlement/uphold.go
settlement/settlement.go
utils/logging/logging.go
utils/wallet/provider/uphold/errors.go
utils/wallet/provider/uphold/uphold.go

Only log progress if there is progress
Do not serialize signed transactions
Make settlement use app `logger` instead of `fmt.Printf`
#1273 
#1274 
#1287

Log improvement

---

cmd/settlement/uphold.go

Replace panic with info log to avoid completion status confusion

Replace panic with info log to avoid completion status confusion

---

cmd/settlement/uphold.go

Initialize progress with a non-zero length and fix loop to actually trigger

Initialize progress with a non-zero length and fix loop to actually trigger

---

utils/backoff/backoff.go
utils/backoff/backoff_test.go
utils/backoff/retrypolicy/factory.go
utils/backoff/retrypolicy/retrypolicy.go

added correctly formatted comments

style: fix linter errors for backoff retry code

---

promotion/drain.go

added logging when calling gemini

bug: user drain gemini not found error

---

.github/workflows/generalized-deployments-reproducible.yaml
.github/workflows/generalized-deployments.yaml

bumps generalized deploy action tag

bump tag generalized deploy

---

.github/workflows/generalized-deployments-reproducible.yaml
.github/workflows/generalized-deployments.yaml

Adds `REPRODUCIBLE` flag to both generalized deployment files

Update Github Workflows to have reproducibility flag

---

.github/workflows/generalized-deployments-reproducible.yaml
.github/workflows/generalized-deployments.yaml

bump version of gen dep action to 1.0.8

bump version of gen dep action to 1.0.8

---

.github/workflows/generalized-deployments-reproducible.yaml
.github/workflows/generalized-deployments.yaml

update to v1.0.9 for gen deploy version

update to v1.0.9 for gen deploy version

---

.github/workflows/generalized-deployments-reproducible.yaml
.github/workflows/generalized-deployments.yaml
cmd/serve/grant.go
cmd/settlement/uphold.go
skus/datastore.go
skus/service.go
utils/clients/coingecko/client.go
utils/clients/gemini/client.go
utils/logging/logging.go
utils/wallet/provider/uphold/errors.go
utils/wallet/provider/uphold/uphold.go

up order creds worker cadence
add reproducible build action

prod 2022-03-17_1

---

Dockerfile

using a scratch image as the base for artifact, reproducible certs download in builder

Reproducible Dockerfile

---

utils/wallet/provider/uphold/errors.go
utils/wallet/provider/uphold/errors_test.go

appending the restrictions to the uphold_forbidden coded error

appending the restrictions to the uphold_forbidden coded error

---

wallet/controllers_v3.go
wallet/service.go

passing through region not supported error

passing through region not supported error

---

Dockerfile
utils/wallet/provider/uphold/errors.go
utils/wallet/provider/uphold/errors_test.go
wallet/controllers_v3.go
wallet/service.go

includes region not supported.
reproducible builds for bat-go

production 2022-03-29_1

---

cmd/vault/sign_settlement.go
settlement/uphold/prepare.go
settlement/uphold/prepare_test.go

Merge transactions where provider is Uphold and the Uphold wallet ID matches for multiple payout addresses.

Merge Uphold Addresses

---

Dockerfile

some deployments are counting on tools

dockerfile changes

---

Dockerfile

some deployments are counting on tools (#1345)

production 2022-04-01_1

---

Dockerfile

add bash to builder for docker-dev

add bash to builder for docker-dev

---

cmd/settlement/uphold.go
settlement/settlement.go
settlement/uphold/prepare_test.go

Remove an extraneous HTTP GET request when attempting to confirm an Uphold transaction.

Remove unneeded transaction get request in confirmation flow

---

go.mod
go.sum

dep updates - fixes: #1354 #1353

dep updates - fixes: #1354 #1353

---

.github/workflows/ci.yml

reducing extra CI, only care about PR to master/prod branches

---

promotion/drain.go
utils/clients/bitflyer/instrumented_client.go
utils/clients/reputation/client.go
utils/clients/reputation/instrumented_client.go
utils/clients/reputation/mock/mock.go
wallet/controllers_v3_test.go
wallet/datastore.go

cohort too young shouldnt block drain

too young is okay for drain

---

promotion/datastore.go
promotion/datastore_test.go
promotion/drain.go
promotion/mockdrain.go

uses claim drain deposit destination everywhere
fixes #1369

bug: gemini deposit destination fix

---

cmd/settlement/uphold.go
settlement/settlement.go

Uphold settlement bug fixes

---

ratios/service.go

updates to ratios to prevent div by 0

updates to ratios to prevent div by 0

---

promotion/service.go

adds a flag to check the if gemini is enabled and therefore enable/disable gemini check status based on this

feat: disable check status

---

promotion/promotion.go

panic if invalid promotion credential value for suggestions

panic if invalid promotion credential value for suggestions

---

nitro-shim/tools/kafkaproxy/go.mod
nitro-shim/tools/kafkaproxy/go.sum

Update dependency for ia2's message format.

---

nitro-shim/scripts/build.sh
nitro-shim/scripts/run.sh
nitro-shim/scripts/start-proxies.sh

The service ia2 needs a viproxy configuration that differs from our
payment service.  It also needs socksproxy and kafkaproxy.

WIP: Set up proxy tools for ia2.

---

nitro-shim/scripts/build.sh
nitro-shim/scripts/run.sh
nitro-shim/scripts/sleep.sh

This instructs bash to exit execution if any part of a pipe fails.

Remove 'set -o pipefail'.

---

promotion/claim.go
promotion/claim_test.go

fix the blinded creds check on claim

fixing claim creds check

---

promotion/claim.go
promotion/claim_test.go

fixing claim creds check (#1399)

production 2022-04-22_1
