brave-intl/bat-go

- .gitignore
- .travis.yml
- Gopkg.lock
- Gopkg.toml
- Makefile
- README.md
- bin/create-tokens/main.go
- bin/get-cert-fingerprint/main.go
- bin/vault-create-wallet/main.go
- bin/vault-sign-settlement/main.go
- controllers/grants.go
- grant/grant_test.go
- settlement/README.md
- settlement/config.hcl
- utils/kv/kv.go
- utils/kv/kv_test.go
- utils/pindialer/dialer.go
- wallet/provider/uphold/uphold.go
- wallet/provider/uphold/uphold_test.go
for context we pin the Uphold cert - they've switched their prod cert to digicert.
this PR adds a new tool for easily querying the current cert fingerprint needed to pin, and updates the pin for their production environment.
there are also some README tweaks and changes to the makefile to make cross compiling the settlement tools for non-mac easier
> update uphold prod pin, tweak settlement README, xc settlement tools

- .gitignore
- Makefile
- bin/create-tokens-ads/README.md
- bin/create-tokens-ads/main.go
Resolves #62 
Resolves https://github.com/brave-intl/internal/issues/75
The binary takes in a ads payout csv and creates grants that are bound to the (providerId, BAT amount) pairs provided in the payout csv.
> Add create-tokens-ads binary

- promotion/controllers_test.go
due to a client bug claims were unable to be redeemed. here we report the state detected client side to store the identifier and begin the redemption process manually.
these are some tests to make sure that the endpoint and migrations work correctly
> added clobbered claim report checks

- promotion/datastore.go
It was originally disabled in https://github.com/brave-intl/bat-go/pull/239
Then changed when normal claims were re-enabled https://github.com/brave-intl/bat-go/pull/242
> re-enable legacy promotion (re)claim

- datastore/grantserver/postgres.go
- grant/datastore.go
- payment/datastore.go
- promotion/datastore.go
rolling back a transaction should happen once, when the transaction is first created. 
otherwise we leave ourselves open to too many connections to the db if we forget to rollback and never commit.
> added tx rollback abstraction

- bin/grant-server/main.go
- go.mod
- go.sum
- middleware/request_id.go
- utils/clients/client.go
- utils/context/wrap.go
- utils/handlers/handlers.go
- utils/requestutils/requestutils.go
It would be useful to be able to track a request from end to end, and through requests as a client
added a middleware and used in client request code, logging where appropriate
> add x request id to middleware and clients

- datastore/grantserver/postgres.go
- migrations/0011_add_properties_to_order.down.sql
- migrations/0011_add_properties_to_order.up.sql
- payment/datastore.go
- payment/order.go
- payment/order_test.go
- payment/service.go
- promotion/order.go
- utils/datastore/models.go
All locations in the order item should be from the same place. Orders should have the ability to report the location of the order items. Items should have a description.
> Add description/location to order and items

- payment/datastore.go
- payment/order.go
This adds a fix where on some legacy SKU tokens the price was specified in the field "amount". We will be able to remove this in the future, but for our initial MVP it's helpful to have this be included in the order item.
Another issue was that when inserting into the database the location was `null`. This was a result of the type being `NullString`
> Fix location and amount for order item

- Makefile
- README.md
- docker-compose.cory.yml
- docker-compose.dev-refresh.yml
a docker container named grant-dev-refresh service will start up a grant server bound to host port 3334 which allows one to do `docker restart grant-dev-refresh` when the user wants to "restart" the service running new code.  This is especially helpful when you hook it up to `fswatch` type utilities, causing a re-run of `go run` every time a file changes.
> Dev refresh compose

- payment/controllers.go
- payment/datastore.go
We previously had accepted status in the list of credentials but we should also have it in `/credentials/:id`
> Return Accepted by get id 

- payment/datastore.go
- payment/order.go
We were setting and reading the encrypted secret key from our database during the initial read
Also I removed most of the `select *` code we have in our payment service ☺️
> Don't set secret key when don't need to

- payment/controllers.go
- payment/vote.go
- payment/vote_test.go
if one vote credential is invalid, stop processing the other votes, and send a validation error to caller.
> Error on invalid sku tokens AC Vote

- payment/key_test.go
```
github.com/brave-intl/bat-go/payment/key.go:31:                 SetSecretKey                    80.0%
github.com/brave-intl/bat-go/payment/key.go:42:                 encryptSecretKey                76.9%
github.com/brave-intl/bat-go/payment/key.go:69:                 decryptSecretKey                70.6%
github.com/brave-intl/bat-go/payment/key.go:101:                randomString                    80.0%
github.com/brave-intl/bat-go/payment/key.go:113:                GenerateSecret                  0.0%
```
> adding success domain tests for key operations

- bin/grant-server/main.go
- datastore/grantserver/postgres.go
- promotion/claim.go
- promotion/drain.go
- utils/clients/reputation/proxy.go
https://godoc.org/github.com/getsentry/sentry-go#Flush
```
Flush should be called before terminating the program to avoid unintentionally dropping events.
Do not call Flush indiscriminately after every call to CaptureEvent, CaptureException or CaptureMessage.
```
> Sentry Recommends defer-ing Flush right after Init

- bin/grant-server/main.go
- middleware/rate_limiter.go
- middleware/request_logger.go
- payment/controllers.go
- payment/service.go
- payment/vote.go
- promotion/service.go
- utils/handlers/healthcheck.go
- utils/logging/logging.go
…r (#384)
updating payment/healthcheck/ratelimit to all use zerolog logger from context
updated payment service to use zerolog for kafka logger and in init functions
updates promotion service kafka client to use zerolog logger
move logging get out of every request, now only get logger once on initialization
adding instrumentation around number of dropped logs
re-arrange middlewares in grant server, removed extra recovery middleware
updates to request logger to not get logger from context twice
> Release 2020-05-08_1

- cmd/settlement_paypal.go
currently it is far to easy to run this command on the original settlement file, before rates and thus amounts are dialed in. with this guard we can help ensure the correct amounts are propagated to the completed report
> add guard against misuse of paypal settlement complete

- promotion/claim.go
- promotion/claim_test.go
- promotion/controllers.go
If wallet/grant combination already has a claim, and the claim credentials do not match the original attempt, respond with a conflict to the caller.
> Claim creds conflict

- utils/wallet/provider/uphold/uphold.go
- wallet/controllers_v3.go
- wallet/service.go
This makes sure the KYC flow is the same for various wallet providers by using the signed transaction "Destination" instead of using the ProviderID on record in the uphold wallet provider case.
> Correct KYC Flow for Linking Wallets

- wallet/datastore.go
- wallet/instrumented_datastore.go
- wallet/service.go
This PR will not allow updates to Anonymous Addresses on wallets.  Based on add-wallet-endpoints feature branch.
> never update anon address on wallets

- cmd/wallets.go
- cmd/wallets_rest_run.go
While migration is occurring it is possible that one might go over their linking limit if the wallet has not been migrated yet.  This PR adds a flag to disable the endpoint while migration is in progress.
- [ x ] Bug fix
When env variable is set the linking endpoint should 404.
> No Linking While Migrating

- bin/grant-server/main.go
- cmd/wallets.go
- cmd/wallets_rest_run.go
- datastore/grantserver/postgres.go
- docker-compose.dev-refresh.yml
- docker-compose.yml
- migrations/0019_wallet_card_id.down.sql
- migrations/0019_wallet_card_id.up.sql
- promotion/controllers.go
- promotion/controllers_test.go
- promotion/drain.go
- promotion/service.go
- utils/wallet/wallet.go
- wallet/datastore.go
- wallet/service.go
1. Adds a flag "ENABLE_LINKING_DRAINING" which when set to false will disable linking of wallets and draining of grants.
2. Stores the card id (tx.destination) as provider_id in the database
3. Draining will transfer to provider_id (tx.destination) instead of anon address.
> Store card id and feature flag to enable linking/draining

- middleware/request_logger.go
- wallet/controllers_v3.go
- wallet/datastore.go
Anon Address is no longer required input from the API.  We are not removing the field completely, just no longer panic-ing if it is not in the request.
Validate in development/staging that this attribute is no longer required.
> removing hard requirement for anon-address in api

- promotion/controllers.go
- promotion/service.go
ParseBool does not recognize the empty string as a synonym of "false", so check to see if the env variable is empty prior to parsing as bool
> Check if ENABLE_LINKING_DRAINING is empty string

- bin/grant-server/main.go
- promotion/service_test.go
Fix to allow viper bind env to be run in grants binary, as we were no longer importing the cmd/wallets package.
Validate that the /v3/wallets endpoints are visible.
> Read Wallet Env Vars in Grant Bin

- cmd/rewards/rest_run.go
- cmd/root.go
The logging in api.rewards was defaulting to 'local' style logging for all environments.  This corrects the issue by setting up the context with 'environment' prior to creation of the logger. 
Watch logs in a non-local environment to make sure they are correctly formatted as json.
> Setup Context for Rewards Server prior to Logger Creation

- payment/controllers_test.go
- payment/service.go
- payment/vote_test.go
- promotion/controllers_test.go
- promotion/service.go
- promotion/suggestions_test.go
- utils/context/keys.go
- utils/kafka/dialer.go
- utils/kafka/instrument.go
move metrics out of init so they will not bleed into services for which not applicable.
Validate that metrics not applicable for rewards sub-command are not present.
> Metrics Bleed across Subcommands

- .dependabot/config.yml
- .github/dependabot.yml
Per https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
> You can see the update logs that used to be on the Dependabot.com dashboard by going to your repository’s Insights page, clicking the Dependency graph tab on the left, and then clicking Dependabot.
Tried checking the logs and noticed that it hadn't picked up our config. There was a button to create a new config - so migrated our settings to the location it suggested.
> Relocate dependabot config

- cmd/serve/grant.go
- promotion/controllers_test.go
- promotion/datastore.go
- promotion/datastore_test.go
- promotion/drain.go
- promotion/instrumented_datastore.go
#454 # Summary
* promotion ids env var is a list of strings, not a string
* break the promotion id loop on success case
* adding legacy claimed in create claim promotion method
> Promotion Draining Bugfixes (#569)

- wallet/service.go
In the event an iOS device attempts to link to a desktop wallet that will make the desktop wallet exceed it's linking limit we want to return a failure before the client attempts to transfer vg.
> update status code to cause error when ios linking limit is exceeded

- .github/workflows/golangci-lint.yml
- datastore/grantserver/postgres.go
- migrations/0023_mint_drain.down.sql
- migrations/0023_mint_drain.up.sql
- promotion/controllers_test.go
- promotion/datastore.go
- promotion/drain.go
- promotion/instrumented_datastore.go
- promotion/service.go
Adds a new drain queue for brave to brave wallet draining.
> Adding a Brave to Brave Wallet Drain Job

- cmd/serve/grant.go
- datastore/grantserver/postgres.go
- migrations/0024_drain_poll.down.sql
- migrations/0024_drain_poll.up.sql
- promotion/controllers.go
- promotion/controllers_test.go
- promotion/datastore.go
- promotion/datastore_test.go
- promotion/drain.go
- promotion/instrumented_datastore.go
- promotion/instrumented_read_only_datastore.go
This PR enables a caller (client) to receive a drain id from submission of tokens, and provides the ability to query a new get drain poll endpoint to look up the status of the draining request.
> Token Drain Status Polling Endpoint

- cmd/settlement/uphold.go
- settlement/settlement.go
Workaround for spurious 502s we're seeing on the Uphold API. There are two problems at play here. One is that we should have an explicit failed state for transfers that cannot continue - e.g. for transfers to an invalid destination, currently we retry these during each run which adds unnecessary load. The second is that we consider unknown errors on the submit endpoint to be as dangerous as those on the confirm endpoint. Since an unhandled return for submit can never result in a duplicate transfer we can safely attempt to submit other transfers.
> better handle case where destination is invalid and unknown errors during submit

- cmd/settlement/uphold.go
- cmd/vault/sign_settlement.go
- settlement/settlement.go
When making transfers to Uphold cards denominated in currencies they have disabled purchasing for seemingly valid quotes are returned, however they have a TTL of 0 meaning they cannot be confirmed. This PR works around this oddity and treats quotes that are immediately invalid as a permanent failure. It also includes a missing flag definition for the vault signing command.
> workaround returned ttl of 0 when making transfers to disabled currencies

- promotion/claim.go
- promotion/promotion.go
- promotion/promotion_test.go
allow claims
- never if `Active = false`
- always if `LegacyClaimed = true`
- allow ads claims up to… a year? - or better to only check expires at
- allow non ads claims up to 3 months (current)
> pushed ads expiration back and allowed legacy claimed to continue claiming

- cmd/rewards/rest_run.go
- cmd/serve/grant.go
This PR serves a copy of the metrics handler for grant and rewards serve on it's own dedicated http.Server / port (9090). This is part 1 of 2, once we deploy this and change our configured scraping port we can commence part 2 which involves removing the metrics handler served on the primary API port.
```
root@8a2bc5757110:/src# curl localhost:3333/v1/promotions
{"promotions":[]}
root@8a2bc5757110:/src# curl -s localhost:9090/metrics | grep api
api_requests_total{code="200",handler="GetAvailablePromotions",method="get"} 1
client_api_requests_total{code="200",method="get",service="uphold"} 2
root@8a2bc5757110:/src# curl -s localhost:3333/metrics | grep api
api_requests_total{code="200",handler="GetAvailablePromotions",method="get"} 1 …
```
> copy metrics for grant and rewards serve to own port

- go.mod
- go.sum
- middleware/rate_limiter.go
- middleware/rate_limiter_test.go
- Adds RateLimiterRedisStore which synchronizes the existing rate limiting behavior among multiple instances
- Adds the ability to specify a surge limit in addition to the per minute limit in the new limiter with Redis store
> Add Rate Limiter with Redis Store

- settlement/settlement.go
- utils/errors/helpers.go
Fixes two settlement tooling issues:
1. There's more subtlety to the TTL 0 handling then originally expected as TTL 0 is expected when a quote is indefinitely valid ( e.g. in the case of BAT -> BAT transfers.
2. There's a new unauthorized error which can occur when confirming transactions.
> fix ttl 0 handling as only LBA / XAU transfers are invalid, unauthorized

- middleware/prometheus.go
fix instrument round tripper for clients so it doesn't panic when called more than once.  Currently if you have multiple http clients instanciated using the transport that is instrumented, it will cause the container to panic due to prometheus.MustRegister.  This will set the value of the instrumented values to what was previously registered.
> Duplicate Instrumented Client Metric Registration

- wallet/controllers_v3.go
- wallet/controllers_v3_test.go
- wallet/inputs.go
- wallet/service.go
Phase 1 of #712, just the API interface, not hooked up to datastore.  This PR includes an API endpoint in the wallets service which will allow for disconnecting of custodian wallets.
> Disconnect Custodial Wallet API Stub

- wallet/datastore.go
remove error generation when no rows updated on wallet/wallet custodian tables on disconnect.  Instead of propogation of a 500 we will now return OK in the event we were unable to update the wallet information in the database.  The end goal of being disconnected still succeeded.
> Disconnect Wallet 500s Due to Disconnect on No Linkage 

- cmd/vault/init.go
vault doesn't support this case, but we can workaround by generating a single unseal share and just encrypting it for all keys passed to init
> add support for vault init threshold = 1, keys > 1

- promotion/service.go
- utils/kafka/dialer.go
removed offset for use with kafka reader and group id
> kafka consumer signalling drain retry

- cmd/vault/sign_settlement.go
- cmd/wallets/transfer_funds.go
- payment/controllers_test.go
- settlement/settlement.go
- settlement/settlement_test.go
- utils/wallet/provider/uphold/uphold.go
- utils/wallet/provider/uphold/uphold_test.go
- wallet/controllers_test.go
these fields were added by Uphold several months back and are required for large transfers. 
support for these fields was previously added in:
https://github.com/brave-intl/bat-go/pull/955/files
unfortunately, the approach there is not mergable as said values were hardcoded for all transfers.
> add purpose and beneficiary fields for Uphold prepared transfers

- ratios/cache.go
- ratios/inputs.go
- ratios/mapping.go
- ratios/service.go
restores prior ratios behavior which preserves the coin input ( symbol or contract address ) and matches the output from coingecko to it
> preserve relative coin input and match output

- utils/wallet/provider/uphold/errors.go
currently we have defined a `ForbiddenError` interface in the `IsErrForbidden` helper, but there is no impl :(
```
[user@work:~/source/bat-go]% rg ForbiddenError
utils/errors/helpers.go
60:             ForbiddenError() bool
63:     return ok && te.ForbiddenError()
[user@work:~/source/bat-go]% 
```
> add uphold forbidden error impl

- promotion/controllers_test.go
- promotion/datastore.go
- promotion/datastore_test.go
- promotion/drain.go
- promotion/drain_test.go
- promotion/instrumented_datastore.go
- promotion/mockdatastore.go
This resolves #1186 where claim drains were being processed before they were ready for batching
> bitflyer batch payment concurrency issue

- utils/wallet/provider/uphold/uphold.go
If beneficiary country and state are provided, but left empty, Uphold will fail to validate and prevent transaction upload.
> Omit beneficiary information that breaks uphold validation

- cmd/ratios/rest_run.go
- docker-compose.yml
- ratios/controllers.go
- ratios/controllers_test.go
- ratios/inputs.go
- ratios/service.go
- utils/clients/client.go
- utils/clients/coingecko/client.go
- utils/clients/coingecko/client_test.go
- utils/clients/coingecko/instrumented_client.go
- utils/clients/coingecko/mock/mock.go
Resolves https://github.com/brave-intl/bat-go/issues/1225
Add ratios endpoint to proxy calls to Coingecko coin markets endpoint
Client calls to new ratios endpoint `/v2/market/provider/coingecko` will be proxied to`/api/v3/coins/markets` on [coingecko](https://www.coingecko.com/en/api/documentation).  The ratios endpoint currently supports two query string parameters `limit` which specifies the number of results (max 250), and `vsCurrency` which specifies the currency the results are denominated in.
The results for a given call are saved on Redis for one hour.  During that time, calls to the same endpoint will be routed to the Redis cache, not coingecko.
Both the path and query supported query strings are flexible, so let me know if something else is desired.
```
$ curl …
```
> Add ratios endpoint to proxy calls to Coingecko coin markets endpoint

- promotion/datastore.go
fixing query to get the claim by id instead of claim_id (#1255)
> production 2022-03-04-2

- utils/clients/reputation/client.go
for some reason the url query string library is breaking up the uuid …into an array of bytes, turing the promotion_id into a string to avoid
> hotfix correct promotion id in client

- cmd/settlement/uphold.go
attempts to better optimize the case where we have to rerun a settlement upload multiple times by snapshotting the fully caught up state of the settlement log.
fixes #1275
> snapshot the settlement log file, fixes #1275

- cmd/settlement/uphold.go
- settlement/settlement.go
Since uphold settlements now enter a `processing` state on confirm, on average there are many more transactions that must be retried manually. This change relies on the fact that transactions which enter the processing state will either eventually fail ( we assume permanently ) or complete successfully. 
>  Otherwise, the request is completed successfully and the response body will contain a status property with value processing. In the meantime, we perform another set of validations that can lead to a transaction’s status becoming failed or completed
https://uphold.com/en/developer/api/documentation/
Essentially we reframe the original loop through transactions with submit and confirm as a way to attempt to get as many transactions as possible into the pending state. This PR adds a …
> automatically poll all settlements in the processing state to finalization

- utils/clients/coingecko/client.go
We always fetch 250 results from coingecko, but return a subset of those results to the client depending on the `limit` parameter the client sets.  The problem is that we are not caching all 250 results in Redis, just the subset.  This can cause problems if the client requests with limit=25, then limit=50.  The second call would fetch the results from the cache, but only the first 25 are cached.
The fix in this pull request is to always cache 250 results, and apply the limit after updating the cache and before returning to the client.
> Ratios: Cache coin markets reponse in Redis before applying limit

- skus/datastore.go
- skus/service.go
removes sentry message capture and extra logging for order jobs
resolves #1474
> bug: cleanup order job extra logging error

- services/ratios/service.go
Reverts brave-intl/bat-go#1577 since this would likely cause label cardinality issues
> Revert "[ratios] Add prometheus counter to track cache hit rate for GetRelative (coingecko)"

- libs/clients/reputation/client.go
- services/wallet/controllers_v4.go
- services/wallet/controllers_v4_test.go
This PR removes response data from wallet info that is no longer needed for v4 endpoints
resolves #1599
> feat: cleanup response data v4 endpoints

- serverless/email/template.yaml
- fixing go.work files
- addressing review concerns
- go mod tidy
- more go mod tidy
- Update SAM template for Events Lambda (#1627) (#1629)
- Fixed SAM Template to remove incorrect Fn::GetAtt reference
Fix for the following error:
```
2022-09-23 16:25:41,834 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create changeset for the stack: bravex-frontend, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Template error: instance of Fn::GetAtt references undefined resource EmailUnsubscribeFunctionRole
```
> Update SAM template to remove incorrect Fn::GetAtt reference

- serverless/email/template.yaml
Resolves the following error:
```
2022-10-02 05:04:42,189 | Unable to export
Traceback (most recent call last):
File "/home/runner/work/_temp/setup-sam-bCZaXp/.venv/lib/python3.8/site-packages/samcli/lib/package/packageable_resources.py", line 127, in export
self.do_export(resource_id, resource_dict, parent_dir)
File "/home/runner/work/_temp/setup-sam-bCZaXp/.venv/lib/python3.8/site-packages/samcli/lib/package/packageable_resources.py", line 149, in do_export
uploaded_url = upload_local_artifacts(
File "/home/runner/work/_temp/setup-sam-bCZaXp/.venv/lib/python3.8/site-packages/samcli/lib/package/utils.py", line 177, in upload_local_artifacts
raise InvalidLocalPathError(resource_id=resource_id, property_name=property_name, local_path=local_path) …
```
> Remove ReadmeUrl from SAM Template

- libs/clients/gemini/client.go
A 404 error using checkstatus on Gemini payouts would cause a crash, this pushes the check further down.
> Fix using checkstatus erroring out on 404

- services/wallet/controllers_v3_test.go
- services/wallet/datastore.go
force eviction of prior linked custodian linking on new linking
fixes: https://github.com/brave-intl/tickets-ledger/issues/75
> disconnect on new custodian linking

- services/ratios/mapping.go
Price of BOO token on Solana is incorrect. Add a mapping in ratios service to prevent collisions.
Resolves https://github.com/brave/brave-browser/issues/29359
https://ratios.rewards.brave.com/v2/relative/provider/coingecko/boo/usd/1d should return [Boo (Solana)](https://www.coingecko.com/en/coins/boo) price.
> Add coingecko mapping for BOO token on Solana

- libs/clients/coingecko/client.go
- services/ratios/cache.go
- services/ratios/controllers.go
- services/ratios/controllers_test.go
- services/ratios/service.go
We want to have browser clients use the browser's HTTP cache in order to reduce network requests when the data doesn't change.  This capability was added in the browser here https://github.com/brave/brave-browser/issues/29071.  In order to be able to use this, the server needs to set the Cache-Control header, which is currently not set.
This PR adds the cache control header to the `/v2/relative/provider/coingecko/{coinIDs}/{vsCurrencies}/{duration}` endpoint.  It sets it to the to match when the rates expire in the server cache and would be fetched from Coingecko again, at most 15 minutes.
> Add Cache-Control header to /v2/relative/provider/coingecko/{coinIDs}/{vsCurrencies}/{duration}

- libs/clients/coingecko/client.go
- services/ratios/controllers.go
- services/ratios/controllers_test.go
Same as https://github.com/brave-intl/bat-go/pull/1812 and https://github.com/brave-intl/bat-go/pull/1813, but for the market tab data endpoint.
Small refactor to use seconds instead of hours as the units when referring to cache durations since that's what the Cache-Control header uses.
> Add Cache-Control header for /v2/market/provider/coingecko

- libs/clients/bitflyer/client.go
- libs/clients/bitflyer/client_test.go
This PR removes a status code check which prevent the bf error from being desearilaized.
resolves https://github.com/brave-intl/tickets-ledger/issues/117
> investigate failing bitFlyer drains

- libs/datastore/postgres.go
- migrations/0060_order_item_history.down.sql
- migrations/0060_order_item_history.up.sql
Similar to #1829 and #1831, this PR adds functionality for tracking history of order items, and partially addresses #1824. This is implemented inside the database and is transparent for the application code.
- The history of order item changes is kept in a separate table, `order_item_history`.
- The table is automatically populated by a set of three triggers – each for `INSERT`, `UPDATE` and `DELETE`.
- Data is captured before and after a change.
- The value fields correspond to the operation that has resulted in a change:
- `INSERT` -> `value_before` is `NULL`, `value_after` contains the inserted data.
- `UPDATE` -> `value_before` contains data prior to the change, `value_after` contains data after the change.
- `DELETE` -> `value_before` contains data before the deletion, `value_after` …
> Implement Database-Side History For Order Items

- libs/datastore/postgres.go
- migrations/0059_transaction_history.down.sql
- migrations/0059_transaction_history.up.sql
- migrations/0060_order_item_history.down.sql
- migrations/0060_order_item_history.up.sql
Similar to #1829, this PR adds functionality for tracking history of transactions, and partially addresses #1824. This is implemented inside the database and is transparent for the application code.
- The history of transaction changes is kept in a separate table, `transaction_history`.
- The table is automatically populated by a set of three triggers – each for `INSERT`, `UPDATE` and `DELETE`.
- Data is captured before and after a change.
- The value fields correspond to the operation that has resulted in a change:
- `INSERT` -> `value_before` is `NULL`, `value_after` contains the inserted data.
- `UPDATE` -> `value_before` contains data prior to the change, `value_after` contains data after the change.
- `DELETE` -> `value_before` contains data before the deletion, `value_after` is …
> Implement Database-Side History For Transactions

- libs/datastore/postgres.go
- migrations/0058_order_history.down.sql
- migrations/0058_order_history.up.sql
- migrations/0059_transaction_history.down.sql
- migrations/0059_transaction_history.up.sql
- migrations/0060_order_item_history.down.sql
- migrations/0060_order_item_history.up.sql
This PR adds functionality for tracking history of orders order items and transactions, and partially addresses #1824. This is implemented inside the database and is transparent for the application code.
- The history of order-related changes is kept in three separate tables:
- `orders` -> `order_history`
- `oder_items` -> `oder_item_history`
- `transactions` -> `transaction_history`
- Data is written to the history tables automatically, by a set of triggers, 1 per each history table, executed on `INSERT`, `UPDATE` or `DELETE`.
- Data is captured before and after a change.
- The value fields in the history tables correspond to the operation that has resulted in a change:
- `INSERT` -> `value_before` is `NULL`, `value_after` contains the inserted data.
- `UPDATE` -> `value_before` contains …
> Implement Database-Side History For Orders And Related Data

- libs/datastore/models.go
- services/grant/cmd/grant.go
- services/skus/controllers_test.go
- services/skus/credentials_test.go
- services/skus/datastore.go
- services/skus/datastore_test.go
- services/skus/key_test.go
- services/skus/model/model.go
- services/skus/order.go
- services/skus/order_test.go
- services/skus/service.go
- services/skus/storage/repository/order_history.go
- services/skus/storage/repository/order_item.go
- services/skus/storage/repository/order_item_test.go
- services/skus/storage/repository/repository.go
- services/skus/storage/repository/repository_test.go
- services/skus/vote_test.go
This PR introduces a set of changes aimed at eventually improving the coherence and health of the SKUs service.
- First steps towards better structure with packages.
- The order and order items functionality has been moved to `storage/repository` from the massive `skus.Postgres` datastore.
- Data model types have been moved to the `model` package, and made backward-compatible (for now) via type aliases.
- A couple of cosmetic and quality of life improvements, such as neat bulk insert for items instead of the manual loop.
Read on to learn more about this.
The changes can be grouped in the following few categories.
At present, the SKUs  service is made of one package where all different moving parts are together. This poses a number a challenges, such as with testing, development, and …
> Decouple Operations on Order Data From The Rest

- .github/workflows/ci.yml
- Dockerfile
- Makefile
This PR slightly improves the tests run time in CI by utilising GitHub Actions cache for Go modules.
With this PR, the overall run time for a full CI starting from the second push to a branch with a PR is around 12 minutes (I saw a couple of runs going as low as 11:47).
Our current development and CI tooling is unnecessarily complicated – Docker is abused without strict need for it in CI. That means we can't simply benefit, for example,  from caching.
However, I've managed to find a way to use cache. It does not speed things up too much, because the majority of time is spent in tests, but we at least no longer have to re-download dependencies on subsequent pushes to a branch with a PR.
One place that is still not using cached modules is the build step in the Dockerfile. Ideally, that …
> Use Go Module Cache For Tests in CI

- create_dbs.sh
- docker-compose.dev.yml
- docker-compose.yml
This PR updates the local dev environment to use one Postgres for the `web` and `challenge-bypass` services instead of two.
Although computers get more powerful, software does not have to be wasteful in how it consumes resources. The official [Postgres image](https://hub.docker.com/_/postgres#Initialization-scripts) that we use has for a long time supported customisation through initialisation scripts (there is a similarly called section in the linked page).
With a custom initialisation script we can create as many users and databases as we like. This is what I do in this PR.
PS: I am not yet sure about the Reputations docker-compose file, if it's even used. If that is, we can add a database for it too, and ditch that third (!) Postgres.
NOTE on migrating: In order for changes from this …
> Use One Postgres Container Locally

- Makefile
- docker-compose.ext.yml
This PR allows the `dev` and `web` containers communicate with other services via an external network. No changes to the existing flows.
> Declare External Network in Compose

- libs/datastore/postgres.go
- migrations/0061_wallet_custodian_check_custodian.down.sql
- migrations/0061_wallet_custodian_check_custodian.up.sql
- services/wallet/controllers_v3_test.go
- services/wallet/datastore.go
- services/wallet/inputs.go
- services/wallet/service.go
> Cust linking xyzabc 3

- libs/clients/gemini/client.go
- libs/clients/gemini/clientx_test.go
When I saw #1897, a few things attracted my attention:
1. While looping over document precedence and valid documents, we compared a desired document from the precedence slice to a issuing country. This is odd.
- I think we should be comparing a document type from precedence to the type of the document in the list.
2. At the end of the loop, the `issuingCountry` variable will be the equal to the country from the _last_ document matched, not the first. This is because we are breaking out only of the inner loop. The outer loop continues.
- I think the intent is to pick the first match based on the precedence regardless of the order of the documents, and the first preferred match should be the value for `issuingCountry`.
So this PR fixes that with a bit of refactoring and tests.
> Possible Fixes For 1897

- docker-compose.yml
- services/skus/controllers.go
- services/skus/controllers_test.go
- services/skus/handler/handler.go
- services/skus/handler/handler_test.go
- services/skus/model/model.go
- services/skus/order.go
- services/skus/service.go
This PR refactors `CreateOrder` into `handler.Order`, in accordance with what'd been described in #1825.
💎 A new package, `handler`, has been added to the `skus` service. This is new home for _types_ that are handlers. A method on a handler type becomes a handler for one [or more] endpoints.
💎 A new _handler_, `Order`, has been added that currently has only one method, `Create`. It reads as `order.Create`.
💎 The new handler has been supplied with tests for `Create`.
💠 Adjusted the `pg_isready` command (used in local and test environments) to stop misleading errors complaining about `root` user not found.
💠 The order create request types have been moved to the `model` package.
> Bundles XX – Refactor CreateOrder

- nitro-shim/Dockerfile
- nitro-shim/scripts/build.sh
- nitro-shim/tools/eifbuild/Makefile
- nitro-shim/tools/eifbuild/go.mod
- nitro-shim/tools/eifbuild/main.go
Adds eifbuild tool to the nitro-shim which allows for specifying command and env. I made it so it's only used when the env vars EIF_PASS_ENV and EIF_COMMAND are set.
Sample invocation for eifbuild:
```
[user@work:nitro-shim/tools/eifbuild]% export FOO=BAR
[user@work:nitro-shim/tools/eifbuild]% export COMMAND="echo \$FOO"
[user@work:nitro-shim/tools/eifbuild]% ./eifbuild -pass-env FOO -docker-uri busybox -output-file foo.eif -- sh -c \"$COMMAND\"    
Image: busybox 
Output: foo.eif 
Command: [sh -c "echo $FOO"] 
Env:
FOO = BAR
Building...
```
> Add eifbuild that allows for specifying command and env

- services/wallet/controllers_v3.go
- services/wallet/controllers_v3_test.go
- services/wallet/service.go
This PR resolves [#133](https://github.com/brave-intl/payment-services/issues/133)  return a users country code in the linking endpoint.
When a user connects their wallet to a custodian the country code will now be returned in the response body. 
This applies to all custodians and both the `/claim` and `/connect` routes; there is no change to the current status codes or error responses.
An example response for the Gemini connect route is shown below -
```
POST v3/wallet/gemini/{paymentID}/connect
Code 200 // this is the current success status code
Response Body
{
geoCountry : <string>
}
```
> Return a users country code in linking endpoint

- services/skus/service.go
numPerInterval for Leo sku is 192, 2 is default
this will do until  https://github.com/brave-intl/bat-go/issues/1997 is fixed.
> numPerInterval for Leo sku is 192, 2 is default

- libs/httpsignature/nitro.go
Pass nil instead of empty byte array in nitro attestation optional fields as currently we're failing validity checks due to array length == 0.
> pass nil instead of empty byte array in nitro attestation

- libs/payments/submit.go
- services/payments/controllers.go
always return an AppError from submit endpoint, this solves serialization issues with PaymentError and makes the return type consistent in all cases
> always return an AppError from submit endpoint

- services/payments/templates/sign-policy.tmpl
it should not be possible to use the sign operation unless the PCR value check passes...
also removes `ImageSha384` since this corresponds to PCR0 per https://docs.aws.amazon.com/kms/latest/developerguide/conditions-nitro-enclaves.html#conditions-kms-recipient-image-sha
> remove signing privilege except through PCR check

- services/payments/templates/decrypt-policy.tmpl
removes ImageSha384 since this corresponds to PCR0 per https://docs.aws.amazon.com/kms/latest/developerguide/conditions-nitro-enclaves.html#conditions-kms-recipient-image-sha
> removes ImageSha384 check in decrypt policy

- services/skus/controllers.go
- services/skus/service.go
Changes include -
------
**TLV2 Multi Redeem**
We return the unique token id to the caller in order to allow them to differentiate distinguish a retry of the initial redemption and provide idempotent behaviour
* break apart verification for tlv1 and blinded token SKU credentials
* allow for multiple redemptions of time limited v2 credentials
* refactor changes from 1995
* change method parameter name from req to cred
* log in controller
------
> Time limited v2 multi redeem (#1995)

- services/skus/service.go
> fix: multi redeem tlv2 success response

- services/skus/controllers.go
- services/skus/controllers_test.go
- services/skus/credentials.go
- services/skus/datastore.go
this PR allows for automatic single device refresh of credentials once all existing credentials have expired. to do so it:
- moves request id generation and checks for existing credentials in preparation for adding endpoint variants that operate on a request id basis. ( NOTE: this changes the response code for credential conflict - I have verified that the SKU SDK does not depend on it. )
- checks the `time_limited_v2_order_creds` table instead of `signing_order_request_outbox` when rejecting tlv2 signing attempts due to existing credentials, this allows us to easily take the credential expiry into account. ( NOTE: this creates a potential race condition between clients when submitting, however only one can succeed. I've left more thorough notes about this race in a comment within the PR. …
> allow single device refresh

- services/skus/controllers.go
- services/skus/credentials.go
- services/skus/order.go
- services/skus/service_nonint_test.go
This PR adjusts `DeleteOrderCreds` such that it can handle orders that have multiple items in them. It resolves #2161.
The method deletes credentials by the order id. In case an order has got more than one item, we've got a few possibilities:
- items are of the same credential type:
- `single-use` -> credentials are deleted by the order id, therefore one deletion is sufficient;
- `time-limited` -> no-op, early successful termination;
- `time-limited-v2` -> credentials are deleted by the order id, therefore one deletion is sufficient;
- items are of different credential types:
- nothing will be done for `time-limited`, as before;
- in accordance with the description above, credentials of the corresponding types will be deleted, followed by the deletion of the signing request, as before.
> Multiple Items vs DeleteOrderCreds

- services/skus/controllers.go
- services/skus/credentials.go
- services/skus/datastore.go
This PR resolves #2171. Improves #2163.
This PR initially was my feedback to #2163 but it had not been merged prior to the original PR making its way to `master`. I continued looking at `CreateOrderCreds` and `CreateOrderItemCredentials` in the lights of making sure that it supports multiple items.
As a result, I conclude the method works on a per-item basis, and it _should_ work for a multi-item order (since there will be signing requests per item). Along the way, I've tidied up the things that attracted my attention.
> Multiple Items vs CreateOrderCreds

- services/wallet/controllers_v3.go
- services/wallet/controllers_v3_test.go
- services/wallet/controllers_v4_test.go
- services/wallet/keystore_test.go
- services/wallet/metric/metric.go
- services/wallet/model/model.go
- services/wallet/service.go
- services/wallet/service_test.go
This PR will 
* Add new metric to count the number of successful or failed wallet linking partitioned by country code
* Move the parse ZebPay verification token into its own function
Related to: [Set up linking dashboard for ZebPay in Grafana](https://github.com/brave-intl/payment-services/issues/136)
Resolves [#179](https://github.com/brave-intl/payment-services/issues/179)
> Add ZebPay linking metrics

- nitro-shim/Dockerfile
> Shim libssl issue

- .github/workflows/ci.yml
Subj.
This PR has to be force-merged using admin privilege. cc @husobee
> Remove Mention of Go 1.18 From CI

- services/skus/controllers.go
- services/skus/controllers_test.go
- services/skus/credentials.go
- services/skus/datastore.go
- services/skus/instrumented_datastore.go
- services/skus/mockdatastore.go
- services/skus/model/model.go
- services/skus/model/model_test.go
- services/skus/service.go
Add Endpoints for Submitting and Fetching Credentials Based on Request ID (#2183)
> production 2023-12-18_1

- services/wallet/gemini_test.go
> refactor: rename geminix test

- services/ratios/mapping.go
Querying price for Bonk reports incorrect result:
```sh
$ curl -s https://ratios.rewards.brave.com/v2/relative/provider/coingecko/bonk/usd/1d | jq '.payload.bonk.usd'
0.01289504  # expected 0.00001355
```
Correct price and price history should be visible in Brave Wallet for Bonk Coin (BONK) token on Solana.
> Add bonk mapping for ratios service

- services/wallet/controller_v3_test.go
- services/wallet/controllers_v4.go
- services/wallet/controllers_v4_test.go
- services/wallet/outputs.go
- services/wallet/service.go
This PR adds the self custody available field to get wallet endpoint.
The endpoint should the below response with the new `selfCustodyAvailable` field. 
```
{
"paymentId": "af5f35a5-1809-4e73-91c4-59b8dbe3a42f",
"walletProvider": {
"id": "",
"name": "brave"
},
"altcurrency": "BAT",
"publicKey": "485c991e35fea0a174786eb9062a76ba6aa7c8bedf1d438a200205475f73db4f",
"selfCustodyAvailable": {
"solana": true
}
}
```
this is a map of providers, currently we only have one Solana.
Please see the spec in the linked issue for more detail.
resolves [168](https://github.com/brave-intl/payment-services/issues/168)
> Add self custody available field to get wallet endpoint

- services/skus/input.go
The `googleVendor` constant has been improperly typed – instead of being given `Vendor` type, as the other constant, it was left untyped. The code worked anyway as untyped constants do automatically get a type, if possible, when are passed.
> Fix: Set Proper Type for Android Vendor

- services/skus/controllers.go
fixes a bug introduced in https://github.com/brave-intl/bat-go/pull/2183, the return type for the legacy credentials by id endpoint was changed from an `OrderCreds` object to `[]OrderCreds`.
> fix: fix legacy creds by item id

- services/wallet/service.go
- services/wallet/storage/storage.go
- services/wallet/storage/storage_test.go
This PR implements a job to remove expired challenges from the database.
Currently the interval is hard codded to 5 minutes which was specified in the spec. This can be parameterised in a future PR if necessary.
resolves [#185](https://github.com/brave-intl/payment-services/issues/185)
> feat: remove expired challenges from the database

- services/wallet/controllers_v4.go
- services/wallet/controllers_v4_test.go
- services/wallet/model/model.go
- services/wallet/model/model_test.go
This PR adds an is allowed method to the allow list entry model and use this in the `GET v4/wallets` endpoint to determine whether self custody is available.
> fix: add is allowed check to allow list entry

- services/skus/controllers.go
- services/skus/credentials.go
- services/skus/credentials_noint_test.go
- services/skus/datastore.go
- services/skus/instrumented_datastore.go
- services/skus/mockdatastore.go
- services/skus/order.go
Review and feedback for #2281:
- Extracted the deletion logic for TLV2;
- Fixed types and arguments for the deletion logic;
- Added tests (thanks to extraction).
> Patches 2281

- services/skus/controllers.go
- services/skus/credentials.go
- services/skus/datastore.go
- services/skus/datastore_test.go
> Patches For 2281

- services/skus/model/model.go
> fix: return order_id instead of id in json

- services/wallet/controllers_v3.go
govalidator returns a false positive when checking the payment id so replace with an equals check.
resolves [#2338](https://github.com/brave-intl/bat-go/issues/2338)
> fix: use equals check for payment id validation instead of govalidator on challenge endpoint

- services/skus/datastore.go
- services/skus/datastore_noint_test.go
- services/skus/datastore_test.go
This is a fix for https://github.com/brave-intl/bat-go/pull/2331, when a request id is accidentally re-used - the request id will be present with a different set of credentials than the ones in the attempted submission.
> fix query to check for request id conflict case ( mismatch )

- services/skus/datastore.go
- services/skus/datastore_noint_test.go
- services/skus/datastore_test.go
Take #2344 to staging ( and then production. )
> production release: fix query to check for request id conflict case

- services/skus/controllers.go
- services/skus/controllers_test.go
- services/skus/input.go
- services/skus/model/model.go
- services/skus/model/model_test.go
- services/skus/order.go
- services/skus/service.go
- services/skus/service_nonint_test.go
This PR updates the processing of an iOS webhook so that it only cancels an order in SKUs, and does not attempt to cancel it in Stripe, because there is obviously no such subscription.
There are many issues with the existing code for handling iOS webhook, but for now this is only to fix the cancelation. Other improvements will be made at a different time.
> fix: don't attempt to cancel sub in Stripe for iOS orders

- services/skus/controllers.go
- services/skus/model/model.go
- services/skus/order.go
- services/skus/service.go
This PR prevents SKUs from moving orders to `pending` on `invoice.updated` events.
Fixes https://github.com/brave-intl/payment-services/issues/207.
> fix: don't move order to pending on invoice update

- services/skus/controllers.go
- services/skus/datastore.go
- services/skus/instrumented_datastore.go
- services/skus/mockdatastore.go
- services/skus/model/model.go
- services/skus/service.go
This PR updates the `submit-receipt` endpoint to return a 409 when an existing linked order has been found. Additionally, it removes the no longer used (nor needed) methods.
Fixes https://github.com/brave-intl/payment-services/issues/214.
> refactor: return 409 on repeated receipt submission

- libs/wallet/provider/uphold/uphold_test.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/skus.go
- services/skus/skus_test.go
This PR adds extends functionality for creating mobile orders with support for the VPN products. This is necessary for switching the order linking for VPN from the legacy process to the new built for Leo.
> feat: support VPN in creating anon orders

- services/skus/controllers_test.go
- services/skus/receipt.go
- services/skus/receipt_test.go
This PR updates the iOS receipt validation code so that it checks `latest_receipt_info` if the expected purchase was not found in the receipt data.
> fix: search for ios purchase in latest_receipt_info

- services/skus/receipt.go
- services/skus/receipt_test.go
- services/skus/skus.go
- services/skus/skus_test.go
This PR updates iOS receipt validation with legacy values that the iOS client might send from releases predating Leo.
> fix: check for legacy subscription_id values in iOS receipt validation

- services/skus/receipt.go
- services/skus/receipt_test.go
This PR addresses the problem when the iOS client sends `bravevpn.monthly` when linking a `bravevpn.yearly` product.
> fix: address inconsistency in ios client with vpn linking

- services/skus/datastore.go
- services/skus/service.go
This PR addresses a potential issue where a client might not be able to fetch enough credentials when it's close to the order expiration date.
The grace period had been set on credentials, but they would be filtered out when stored in the database.
> fix: take grace period into account in credentials

- libs/datastore/postgres.go
- migrations/0067_tlv2_request_id_not_null.down.sql
- migrations/0067_tlv2_request_id_not_null.up.sql
- migrations/0068_tlv2_request_id_uniq.down.sql
- migrations/0068_tlv2_request_id_uniq.up.sql
- services/skus/controllers_test.go
- services/skus/credentials_test.go
- services/skus/datastore_test.go
- services/skus/skustest/skustest.go
- services/skus/storage/repository/order_item_test.go
- services/skus/vote_test.go
This PR updates the `time_limited_v2_order_creds_unique` constraint on the `time_limited_v2_order_creds` table, thus allowing credentials for multiple unique batches within the same period, which is necessary for Multi Device Refresh.
> feat: change request_id to disallow null and update index

- libs/clients/coingecko/client_test.go
- libs/clients/stripe/client_test.go
- libs/wallet/provider/uphold/uphold.go
- libs/wallet/provider/uphold/uphold_test.go
- services/skus/controllers_test.go
- tools/vault/cmd/create_wallet.go
uphold.IsUserKYC() is used only for online checks but not for payments.
So skip certificate fingerprint checks to prevent outages in online
checks when Uphold changes the certificate.
- [x ] Bug fix
- [ x] Development
- [ x] Does your code build cleanly without any errors or warnings?
- [ x] Have you used auto closing keywords?
- [ x] Have you added tests for new functionality?
- [ x] Have you squashed all intermediate commits?
- [ x] Have you used intuitive function, variable and other naming?
- [ x] Have you performed a self review of this PR?
> Avoid fingerprint verification when checking IsUserKYC

- Makefile
- tools/payments/git-hooks/post-merge
- tools/payments/ipython-profile/startup/00-setup.py
despite the improvements made to the reproducible docker build caching, it is still a bit slow - this makes it so that we end up caching the entire target on a Makefile basis and adds a git hook to clear the tar file post-merge
> cache output of reproducible docker build target via image tar

- services/skus/service.go
- services/skus/service_nonint_test.go
This PR adds a 24-hour leeway to the expiry time on a mobile subscription. This is to make sure that, if there is a delay in webhook processing, users do not experience disruption in Premium services.
> feat: add leeway for expiry time on mobile webhooks

- services/grant/cmd/grant.go
- services/skus/controllers.go
Use `io.ReadAll` instead of `requestutils.ReadJSON` and increase the read timeout for grants server.
resolves https://github.com/brave-intl/bat-go/issues/2598
> fix: io read timeout on create item creds endpoint

- services/skus/controllers.go
- services/skus/order.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/stripe.go
- services/skus/stripe_test.go
- services/skus/testdata/stripe_invoice_paid.json
- services/skus/testdata/stripe_sub_deleted.json
This PR updates the handling of the Stripe webhooks, improving on how it's done as well as setting the expiry time on orders more accurately.
- the `invoice.updated` webhook is now completely ignored, as it has never had any useful processing;
- the order expiry date is now set up to the expiry date from an `invoice.paid` event plus a leeway (for the case if the next billing cycle's event has been delayed for whatever reason);
- the code is prepared for handling the subscription cancellation events.
---
> fix: set proper expiry time for stripe orders

- services/skus/appstore.go
- services/skus/playstore.go
- services/skus/playstore_test.go
- services/skus/receipt.go
- services/skus/service.go
- services/skus/service_nonint_test.go
This PR improves how expiry time is acquired from the App Store or Play Store data, and cleans up some maintenance code.
> fix: unify use of expiry time

- libs/context/keys.go
This PR removes unused Gemini skus ctx key values.
resolves https://github.com/brave-intl/bat-go/issues/2625
> refactor: remove unused gemini skus ctx key values

- services/skus/appstore.go
- services/skus/appstore_test.go
- services/skus/receipt.go
- services/skus/receipt_test.go
This PR updates the receipt handling for iOS such that `latest_receipt_info` is checked before the given `receipt`. This is because the latter might contain outdated information, the latest has to be consulted with first.
> fix: search latest receipt info first

- libs/httpsignature/httpsignature.go
- libs/middleware/http_signed_test.go
- services/promotion/controllers.go
- services/skus/key.go
- services/wallet/keystore.go
Fix the signature of the LookupVerifier method of the Keystore interface to return Verifier interface directly, not a pointer to it to simplify implementations of the method.
> fix: LookupVerifier returns interface (#2631)

- services/skus/controllers.go
- services/skus/controllers_test.go
- services/skus/model/model.go
- services/skus/model/model_test.go
- services/skus/order.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/storage/repository/mock.go
- services/skus/xstripe/mock.go
- services/skus/xstripe/xstripe.go
- services/skus/xstripe/xstripe_test.go
This PR fixes code that could update an order associated with Stripe purchases while getting the order. This could happen in a situation where:
- either an existing session has expired, and a new had been created;
- or when the existing or new session has been paid, which would then result in marking the order as paid, and setting it's expiry time as a consequence.
That last path is important because it used to extend an order by the hardcoded one month. This is wrong for a few reasons, mainly because:
- it can be set precisely using the end of a subscription from Stripe;
- it prevented us from sully supporting annual products in Stripe.
This PR also fixes a bug where a new session could be ignored to be checked for payment status.
This PR also refactors interactions with Stripe. The …
> fix: use proper expiry time in getorder endpoint

- libs/httpsignature/httpsignature.go
- libs/middleware/http_signed_test.go
- services/promotion/controllers.go
- services/skus/controllers.go
- services/skus/controllers_test.go
- services/skus/key.go
- services/skus/model/model.go
- services/skus/model/model_test.go
- services/skus/order.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/storage/repository/mock.go
- services/skus/xstripe/mock.go
- services/skus/xstripe/xstripe.go
- services/skus/xstripe/xstripe_test.go
- services/wallet/keystore.go
> Production 2024-08-14_01

- services/skus/credentials.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/storage/repository/mock.go
- services/skus/storage/repository/tlv2.go
- services/skus/storage/repository/tlv2_test.go
Subj. This optimises the query performance by limiting the size of the dataset we're searching in.
> fix: use order id and item id in submission report

- services/skus/controllers.go
- services/skus/service.go
If redemption failed for regular Leo because of the wrong issuer, try requesting it with the annual.
> fix: use leo annual issuer if redemption fails for regular leo

- services/skus/credentials.go
- services/skus/datastore.go
- services/skus/datastore_test.go
- services/skus/instrumented_datastore.go
- services/skus/mockdatastore.go
This PR makes the original query to use `order_id` as well as `item_id`, because it's readily available at the call site, and there is a compound index by order and item id on the table. The query currently uses only item id, which is not indexed on, and the query takes quite a bit of DB resources.
The original query was:
```sql
select request_id, order_id, item_id, completed_at, message_data from signing_order_request_outbox where item_id = $1
```
And now it's:
```sql
SELECT request_id, order_id, item_id, completed_at, message_data FROM signing_order_request_outbox WHERE order_id=$1 AND item_id=$2
```
> fix: use order id and item id in get_signing_order_request

- services/skus/model/model.go
Subj. The code was not updated for the annual version which results in wrong number of credentials per day.
> fix: use correct value for numPerInterval for leo annual

- services/skus/skus.go
- services/skus/skus_test.go
> feat: update leo annual ios product id

- services/grant/cmd/grant.go
- services/skus/controllers.go
- services/skus/controllers_test.go
- services/skus/handler/cred.go
- services/skus/handler/cred_test.go
- services/skus/handler/handler.go
- services/skus/handler/handler_test.go
- services/skus/model/model.go
- services/skus/service.go
- services/skus/service_nonint_test.go
This PR adds a new endpoint which works similar to the existing one for cancelling orders expect for it does not handle subscription cancellations in Stripe. Instead, it just updates the order status to `canceled`.
I've considered going with `PUT` and/or using `204` response, but rejected those options because they did not fit this use case. So had to stick with `DELETE` and `200` in response, with an empty body.
Also, for some tests `.ErrorIs` and `.Nil` for errors were not applicable, details for which I could provide if needed. Had to use the simple `.Equal` because it simply works, and does the comparison the way I need it.
Hopefully the points above provide the necessary context during review.
> feat: add endpoint for cancelling orders

- libs/wallet/provider/uphold/uphold.go
- services/grant/cmd/grant.go
- services/skus/controllers.go
- services/skus/controllers_test.go
- services/skus/handler/cred.go
- services/skus/handler/cred_test.go
- services/skus/handler/handler.go
- services/skus/handler/handler_test.go
- services/skus/model/model.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- #2656
- https://github.com/brave-intl/bat-go/pull/2661
> Production 2024-09-23_01

- libs/datastore/postgres.go
- migrations/0069_order_items_add_sku_variant.down.sql
- migrations/0069_order_items_add_sku_variant.up.sql
- services/skus/controllers_test.go
- services/skus/handler/handler_pvt_test.go
- services/skus/handler/handler_test.go
- services/skus/model/model.go
- services/skus/order.go
- services/skus/order_test.go
- services/skus/service.go
- services/skus/service_test.go
- services/skus/storage/repository/order_item.go
- services/skus/storage/repository/order_item_test.go
- services/skus/storage/repository/repository_test.go
- services/skus/storage/repository/tlv2_test.go
This PR adds support for a new `sku_variant` field for order items. The scope of this PR is to only add the field and store it for new orders.
The migration `0069` adds the new column, but leaves the actual update to be executed manually due to the number of records. It's important to not delay the start up of the service, therefore the update will take place outside of the migration.
> feat: add sku_variant field

- libs/datastore/postgres.go
- migrations/0069_order_items_add_sku_variant.down.sql
- migrations/0069_order_items_add_sku_variant.up.sql
- services/skus/controllers_test.go
- services/skus/handler/handler_pvt_test.go
- services/skus/handler/handler_test.go
- services/skus/model/model.go
- services/skus/order.go
- services/skus/order_test.go
- services/skus/service.go
- services/skus/service_test.go
- services/skus/storage/repository/order_item.go
- services/skus/storage/repository/order_item_test.go
- services/skus/storage/repository/repository_test.go
- services/skus/storage/repository/tlv2_test.go
> Production 2024-10-23_01

- services/skus/skus.go
- services/skus/skus_test.go
This is a follow up for https://github.com/brave-intl/bat-go/pull/2673 in which I forgot to also make sure that `sku_variant` is set when creating orders from mobile linking. This fixes that, and should be released before any further changes.
> fix: set sku_variant when linking mobile orders

- services/skus/skus.go
- services/skus/skus_test.go
Subj. Annual VPN on mobile has historically been linked to a monthly VPN SKU due to the absence of the annual SKU to link with. As the annual product has been created, now it's possible to link it correctly.
This might also be needed to avoid issues with detecting and displaying linked subscriptions on the Premium website.
> fix: link annual vpn to annual sku

- services/rewards/cmd/rest_run.go
- services/rewards/controllers_test.go
- services/rewards/handler/handler.go
- services/rewards/handler/handler_test.go
- services/rewards/model/model.go
- services/rewards/service.go
- services/rewards/service_test.go
This PR adds a new endpoint `GET v1/cards`.
It will return the json stored in S3 bucket with the key `cards.json`.
N.B. caching will be added in a subsequent PR.
resolves https://github.com/brave-intl/bat-go/issues/2688
> feat: add new get cards endpoint

- services/skus/service.go
This PR improves the way email is handled when creating a Stripe checkout session.
In rare instances, the email might not be supplied (if it was not fetched during attempts to recreate a session, which could happen either when getting an order or when setting trial days).
Otherwise, the code will continue trying to search for the customer associated with the email, and if found will additionally explicitly set the `CustomerEmail` field to have it populated on the checkout page.
If the customer was not found for the given email, then the behaviour remains the same, and the supplied email is used to populate the field on the checkout page.
> fix: improve email handling when creating a stripe checkout session

- services/rewards/cmd/rest_run.go
- services/rewards/controllers.go
- services/rewards/controllers_test.go
- services/rewards/handler/handler.go
- services/rewards/handler/handler_test.go
- services/rewards/model/model.go
- services/rewards/service.go
- services/rewards/service_test.go
- services/skus/service.go
- services/skus/stripe.go
**Changes:**
Rewards Service -
- https://github.com/brave-intl/bat-go/pull/2684
- https://github.com/brave-intl/bat-go/pull/2683
- https://github.com/brave-intl/bat-go/pull/2695
- https://github.com/brave-intl/bat-go/pull/2690
SKU Service - 
- https://github.com/brave-intl/bat-go/pull/2697
- https://github.com/brave-intl/bat-go/pull/2698
> Production 2024-10-30_01

- .github/workflows/ci.yml
- .github/workflows/golangci-lint.yml
- .golangci.yaml
- Dockerfile
- docker-compose.dev-refresh.yml
- services/rewards/docker-compose.yml
- services/skus/docker-compose.payment-refresh.yml
- services/skus/docker-compose.yml
- services/wallet/docker-compose.yml
- tools/Dockerfile
There would not have been a need for this, but there are 6 security issues that require updating `hashicorp/vault` to `v1.17` and `1.18`, which in turn requires Go runtime of `1.22` or above.
This PR updates the requirements for the runtime to `1.22`. Unfortunately, Go `1.22` also brings changes to the `go` directive in `go.mod`, as well as adds `toolchain`.
After this PR, anyone working with the code base should have at least Go `1.22.5`. If it's desired to remain in control of the version of Go used locally, then it's also advised to have `GOTOOLCHAIN=local` instead of `auto`.
The [dependency update PR](https://github.com/brave-intl/bat-go/pull/2662) requires this to be merged first.
> chore: upgrade go runtime to 1.22

- .github/workflows/ci.yml
- Dockerfile
- Makefile
- cmd/go.mod
- cmd/go.sum
- docker-compose.dev-refresh.yml
- docker-compose.yml
- libs/go.mod
- libs/go.sum
- main/go.mod
- main/go.sum
- nitro-shim/tools/gvproxy/go.mod
- nitro-shim/tools/gvproxy/go.sum
- nitro-shim/tools/viproxy/go.mod
- nitro-shim/tools/viproxy/go.sum
- services/go.mod
- services/go.sum
- services/rewards/docker-compose.yml
- services/skus/docker-compose.payment-refresh.yml
- services/skus/docker-compose.yml
- services/wallet/docker-compose.yml
- tools/Dockerfile
- tools/go.mod
- tools/go.sum
Subj.
Fixes https://github.com/brave-intl/bat-go/security/dependabot/119.
Fixes https://github.com/brave-intl/bat-go/security/dependabot/120.
Fixes https://github.com/brave-intl/bat-go/security/dependabot/121.
Fixes https://github.com/brave-intl/bat-go/security/dependabot/122.
Fixes https://github.com/brave-intl/bat-go/security/dependabot/123.
Fixes https://github.com/brave-intl/bat-go/security/dependabot/124.
> chore: update x/net to v0.23.0

- services/skus/controllers.go
- services/skus/datastore.go
- services/skus/instrumented_datastore.go
- services/skus/mockdatastore.go
- services/skus/model/model.go
- services/skus/model/model_test.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/storage/repository/mock.go
- services/skus/storage/repository/repository.go
- services/skus/storage/repository/repository_test.go
This PR improves handling of the customer email on a Stripe checkout session when setting trial days on an order and session.
https://github.com/brave-intl/bat-go/pull/2698 improved handling, but that was not enough. When we're setting trial days on a session, the caller already has the correct email. SKUs attempts to work out the email based on the old session. Because the two calls (the creation of the initial session and setting trial days) happen very close to each other, the customer record might not be ready yet or miss information.
This PR makes use of the passed email address, and falls back to the old behaviour (i.e. takes the email from on old session) only if it was not passed.
This should address the majority of cases where the checkout page for products with trial might be …
> fix: set email when creating new session for trial days

- services/skus/model/model.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/xstripe/mock.go
- services/skus/xstripe/xstripe.go
- services/skus/xstripe/xstripe_test.go
This PR makes it possible for the known customer to be passed when creating a premium order. Additionally, this makes use of the customer information obtained from the old session when recreating one (mainly as part of the set trial days call).
> feat: use customer id when present whilst creating a premium order

- services/skus/controllers.go
- services/skus/credentials.go
- services/skus/vote.go
This PR fixes a panic when the issuer wasn't found whilst voting.
There has been a spike in panics due to not found issuer because the datastore method returns `nil, nil` when not found, and the caller does not check the result for nil-ness.
> fix: don't panic when issuer wasn't found for vote

- services/skus/controllers.go
- services/skus/credentials.go
- services/skus/model/model.go
- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/vote.go
- services/skus/xstripe/mock.go
- services/skus/xstripe/xstripe.go
- services/skus/xstripe/xstripe_test.go
- services/wallet/controllers_v3.go
- #2715
- #2720
- #2721
- #2723
> Production 2024-12-10_01

- services/skus/handler/handler_test.go
- services/skus/model/model.go
- services/skus/service.go
- services/skus/service_nonint_test.go
This PR adds initial support for passing Stripe coupons to use as discounts at checkout. Additionally, it allows passing extra metadata. This is only allowed in the authenticated endpoint for creating orders used by us.
> feat: add initial support for passing stripe discounts

- services/ratios/controllers.go
- services/ratios/controllers_test.go
- services/ratios/inputs.go
- services/ratios/service.go
Our CoinGecko API usage is through the roof, putting us at risk of service discontinuation unless we significantly reduce our requests. This PR aims to reduce Coingecko API usage.
The way clients query token prices using the Ratios service is as follows:
1. Collect the Coingecko IDs to fetch prices for
2. Split them in batches, and request the Ratios service for each batch (say, with size 25).
3. If any of the batched requests fail, the system falls back to fetching prices individually for each ID in the batch.
A batched request can fail for invalid/unknown Coingecko IDs in the request, but rejecting the entire batch for even a single such ID is sub-optimal. This PR ensures that such IDs are ignored and we return prices for the remaining valid Coingecko IDs in the request (if any).
```sh …
```
> fix(ratios): ignore invalid and empty coingecko ids

- services/ratios/service.go
`GetRelative` appears to be triggering a request to fetch market chart for single coingecko id requests, for a piece of data which doesn't seem to be that useful to Brave Wallet.
We'll now always be copying the 24H % change to `<currency>_timeframe_change` field, ignoring whatever `duration` is specified by the caller. In the future, we'll remove `duration` as a parameter to the corresponding controller since it doesn't make semantic sense to have it.
Related to https://github.com/brave/brave-browser/issues/44557
Ensure hitting the endpoint returns the 24h change regardless of the duration. For example, the following endpoints should have the same result for `usd_timeframe_change`:
- http://ratios.bsg.brave.com/v2/relative/provider/coingecko/ethereum,neon/usd/live
- …
> feat(ratios): always return 24h change in GetRelative service

- services/skus/service.go
- services/skus/service_nonint_test.go
- services/skus/storage/repository/mock.go
- services/skus/storage/repository/repository.go
- services/skus/storage/repository/repository_test.go
This PR uses a Radom subscription id instead of the external id in orders metadata.
closes https://github.com/brave-intl/bat-go/issues/2824
related issue https://github.com/brave-intl/bat-go/pull/2718
> refactor: use radom subscription id in metadata instead of external id

- services/skus/service.go
- services/skus/service_nonint_test.go
This PR reset payment failed metadata on radom renew and cancel events.
closes  https://github.com/brave-intl/bat-go/issues/2854
> refactor: reset payment failed on radom renew and cancel events

- libs/time/duration.go
- libs/time/duration_test.go
- services/skus/service_test.go
This pull request fixes a bug where the time passed to the ISODuration From method was not being used. 
The parameter [t](https://github.com/brave-intl/bat-go/compare/master...fix-ios-duration-from#diff-af9e3847fd48f1c7587f06b242b99099dff940b959660a27b45cb40dd5d2ce01R51) was being passed into the From function however it was not being used and the call to duration function [here](https://github.com/brave-intl/bat-go/compare/master...fix-ios-duration-from#diff-af9e3847fd48f1c7587f06b242b99099dff940b959660a27b45cb40dd5d2ce01L105) 
created a [new time based from now](https://github.com/brave-intl/bat-go/compare/master...fix-ios-duration-from#diff-af9e3847fd48f1c7587f06b242b99099dff940b959660a27b45cb40dd5d2ce01L130) hence we were getting the wrong number of tokens as the time was not being …
> fix: use correct time when calling iso duration from method

- services/wallet/controllers_v3_int_test.go
- services/wallet/mock.go
- services/wallet/service.go
- services/wallet/service_test.go
- services/wallet/xslack/mock.go
- services/wallet/xslack/xslack.go
- services/wallet/xslack/xslack_test.go
This PR adds functionality to send a slack notification when a user tries to link a Solana sanctioned address to their rewards wallet.
closes https://github.com/brave-intl/bat-go/issues/2921
> feat: add solana sanctioned address slack notifier

- services/wallet/controllers_v3_int_test.go
- services/wallet/service.go
- services/wallet/service_test.go
This PR removes the `ADDRESS_CHECKER_ENABLED` feat flag as it is no longer needed.
closes https://github.com/brave-intl/bat-go/issues/2924
> refactor: remove address checker enabled feat flag
